CFLAGS=-UC:/Poker/SMBIOS "-UC:\Program Files\DevExpress VCL\ExpressEditors Library\Sources"
CFLAGS+="-UC:\Program Files\DevExpress VCL\Library\Delphi16"
CFLAGS+=-AComObj=System.Win.ComObj -NSWinapi -NSSystem -NSVcl -Uforms -NSData -NSVcl.Imaging
CFLAGS+=-Umodules/playerinfo -Umodules/clubinfo -Umodules/gameinfo -Umodules/protobuf/objects
CFLAGS+=-U3rdparty/protobufs -Umodules/protobuf -Umodules/server_settings -Umodules/tables -UC:/poker/syngdiplus
CFLAGS+=-Umodules/avatars -UC:/Poker/icsv8w/Lib/Debug/Win32/XE2 -Umodules/encryption -UC:/Poker/Dec/Part_I
CFLAGS+=-Umodules/socketclient -Umodules/settings -UC:/Poker/SuperObject -Umodules/message_container
CFLAGS+=-UC:\Poker\Graphics32 "-UC:/Program Files/madCollection/madExcept/BDS9/win32"
CFLAGS+="-IC:/Program Files/DevExpress VCL/Library/Delphi16"
GCC=dcc32

%.dcu: %.pas
	${GCC} ${CFLAGS} $< -q
%.dcu: %.dpr
	${GCC} ${CFLAGS} $< -q
