CFLAGS="-UE:\Program Files\DevExpress VCL\ExpressEditors Library\Sources"
CFLAGS+="-UE:\Program Files\DevExpress VCL\Library\RS16"
CFLAGS+=-AComObj=System.Win.ComObj -NSWinapi -NSSystem -NSVcl -Uforms -NSData -NSVcl.Imaging -NSSystem.Win
CFLAGS+=-Umodules/playerinfo -Umodules/clubinfo -Umodules/gameinfo -Umodules/protobuf/objects
CFLAGS+=-U3rdparty/protobufs -Umodules/protobuf -Umodules/server_settings -Umodules/tables -UC:/poker/syngdiplus
CFLAGS+=-Umodules/avatars -UE:/Poker/icsv8w/Source -Umodules/encryption -UC:/Poker/Dec/Part_I
CFLAGS+=-Umodules/socketclient -Umodules/settings -UC:/Poker/SuperObject -Umodules/message_container
CFLAGS+=-UC:\Poker\Graphics32 "-UC:\Program Files (x86)\madCollection\madExcept\BDS9\win32"
CFLAGS+="-UC:\Program Files (x86)\madCollection\madBasic\BDS9\win32"
CFLAGS+="-UC:\Program Files (x86)\madCollection\madDisAsm\BDS9\win32"
CFLAGS+="-IE:/Program Files/DevExpress VCL/Library/RS16"
CFLAGS+="-UE:/Poker/AsphyreSphinx304/Source"
CFLAGS+="-IE:/Poker/AsphyreSphinx304/Source"
CFLAGS+="-UE:\Poker\AsphyreSphinx304\Source\Delphi"
CFLAGS+="-UE:\Poker\AsphyreSphinx304\Source\Providers"
CFLAGS+="-UE:\Poker\AsphyreSphinx304\Source\Headers" -U3rdparty/icsv8
CFLAGS+="-UE:\Poker\RichView v13.12.1 FS\1-TrichView" -IE:\Poker\icsv8w\Source
CFLAGS+=-OC:/Poker/mORMot/SQLite3 -UC:/Poker/mORMot -UC:/Poker/mORMot/SQLite3 -IC:/Poker/mORMot
GCC=dcc32

%.dcu: %.pas
	${GCC} ${CFLAGS} $< -q
%.dcu: %.dpr
	${GCC} ${CFLAGS} $< -q
