#include <google/protobuf/compiler/plugin.h>
#include <google/protobuf/compiler/code_generator.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>
#include <google/protobuf/io/zero_copy_stream.h>
#include <iostream>

// hack
#include <stdio.h>

#include "strutil.h"

using namespace std;
using namespace google::protobuf::compiler;
using namespace google::protobuf;

// taken from cpp_helpers.cc in protobuf
string StripProto(const string& filename) {
	if (HasSuffixString(filename, ".protodevel")) {
		return StripSuffixString(filename, ".protodevel");
	} else {
		return StripSuffixString(filename, ".proto");
	}
}
string PrivateFieldName(const FieldDescriptor *field) {
	// FIXME, prefix with F
	string out = field->camelcase_name();
	string::iterator i = out.begin();
	if ('a' <= *i && *i <= 'z') *i += 'A' - 'a';
	return out;
}
string PropertyName(const FieldDescriptor *field) {
	//cerr << "getting name for " << field->full_name() << "\n";
	if (field->name() == "_id") return "MongoId";
	string out = field->camelcase_name();
	string::iterator i = out.begin();
	if ('a' <= *i && *i <= 'z') *i += 'A' - 'a';
	return out;
}
void CreateArguments(io::Printer *printer,const Descriptor *message) {
	bool first = true;
	bool tick = false;
	for (int j=0; j<message->field_count(); j++) {
		const FieldDescriptor *field = message->field(j);
		if (!first) {
			if (tick) printer->Print("; ");
		} else first = false;
		tick = false;
		if (field->type() == FieldDescriptor::TYPE_BYTES) {
			if (field->label() != FieldDescriptor::LABEL_REPEATED) {
				printer->Print("const A$name$: TBytes","name",PrivateFieldName(field));
				tick = true;
			}
		} else if (field->type() == FieldDescriptor::TYPE_INT32) {
			if (field->label() != FieldDescriptor::LABEL_REPEATED) {
				printer->Print("const A$name$: Integer","name",PrivateFieldName(field));
				tick = true;
			}
		} else if (field->type() == FieldDescriptor::TYPE_STRING) {
			if (field->label() != FieldDescriptor::LABEL_REPEATED) {
				printer->Print("const A$name$: AnsiString","name",PrivateFieldName(field));
				tick = true;
			}
		} else if (field->type() == FieldDescriptor::TYPE_BOOL) {
			if (field->label() != FieldDescriptor::LABEL_REPEATED) {
				printer->Print("const A$name$: Boolean","name",PrivateFieldName(field));
				tick = true;
			}
		}
	}
}
// some code based on http://sourceforge.net/p/protobuf-delphi/wiki/Example/
class DelphiGenerator : public CodeGenerator {
	bool Generate(const FileDescriptor* file, const string& parameter, GeneratorContext* generator_context, string* error) const {
		//*error = "unfinished";
		cerr << file->name() << "\n";
		//StripProto(file->name());

		for (int i=0; i<file->message_type_count(); i++) {
			const Descriptor *message = file->message_type(i);
			cerr << "message#" << i << " " << message->name() << "\n";
			scoped_ptr<io::ZeroCopyOutputStream> output(generator_context->Open("uPB_" + message->name() + ".pas"));
			io::Printer printer(output.get(), '$');
			printer.Print(
				"// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
				"// source: $filename$\n"
				"\n",
				"filename",file->name()
				);
			printer.Print(
				"unit uPB_$name$;\n"
				"interface\n"
				"uses\n"
				"  WinApi.Windows, System.Classes, System.SysUtils, System.Generics.Collections, pbOutput, uProtobufBaseObject, uProtobufReader","name",message->name());
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_MESSAGE) {
					const Descriptor *subtype = field->message_type();
					printer.Print(",uPB_$name$","name",subtype->name());
				}
			}
			printer.Print(";\n"
				"type\n"
				"  TPB_$name$ = class(TProtobufBaseObject)\n"
				"  private\n"
				"    const\n",
				"name",message->name());
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				char hack[10];
				snprintf(hack,9,"%d",field->number());
				string name = field->name();
				UpperString(&name);
				printer.Print("      FN_$name$ = $id$;\n","name",name,"id",hack);
			}
			printer.Print(
				"    var\n");
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_INT32) {
					printer.Print("      F$name$: Integer;\n","name",PrivateFieldName(field));
				} else if (field->type() == FieldDescriptor::TYPE_STRING) {
					printer.Print("      F$name$: AnsiString;\n","name",PrivateFieldName(field));
				} else if (field->type() == FieldDescriptor::TYPE_BOOL) {
					printer.Print("      F$name$: Boolean;\n","name",PrivateFieldName(field));
				} else if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
//							"      F$name$_bytes: const APointer;\n"
//							"      F$name$_size: const Integer;\n"
							"      F$name$: TArray<TBytes>;\n"
							,"name",PrivateFieldName(field));
					} else {
						printer.Print(
							"      F$name$: TBytes;\n"
//							"      F$name$_size: Integer;\n"
							,"name",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_MESSAGE) {
					const Descriptor *subtype = field->message_type();
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
							"      F$name$: TPB_$subname$s;\n"
						//	"     function Get$name$count: integer;\n"
						//	"     function Get$name$(Index: integer): TPBR_$subname$;\n"
							,"name",field->name(),"subname",subtype->name());
					} else {
						printer.Print(
							"      F$name$: TPB_$subname$;\n"
							,"name",field->camelcase_name(),"subname",subtype->name());
					}
				}
			}
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() == FieldDescriptor::LABEL_REQUIRED) {
//						printer.Print(
//							"      function Get$name$_hex: String;\n"
//							"      function Get$name$_base64: String;\n"
//							,"name",field->camelcase_name());
					}
				}
			}
			printer.Print(
//				"    procedure Read(const AStream: TStream);\n"
//				"    procedure Write: TProtoBufOutput;\n"
				"  public\n"
				"    constructor Create("
				);
			CreateArguments(&printer,message);
			printer.Print(
				"); overload;\n"
				"    destructor Destroy; override;\n"
				"    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;\n"
				"    function GetProtobuf: TProtoBufOutput; override;\n"
				"\n");
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_INT32) {
					printer.Print("    property $name$: Integer read F$name$ write F$name$;\n","name",PropertyName(field));
				} else if (field->type() == FieldDescriptor::TYPE_STRING) {
					printer.Print("    property $name$: AnsiString read F$name$ write F$name$;\n","name",PropertyName(field));
				} else if (field->type() == FieldDescriptor::TYPE_BOOL) {
					printer.Print("    property $name$: Boolean read F$name$ write F$name$;\n","name",PropertyName(field));
				} else if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
							"    property $name$: TArray<TBytes> read F$name$;\n"
							,"name",PropertyName(field));
					} else {
						printer.Print(
							"    property $name$: TBytes read F$pname$ write F$pname$;\n"
//							"    property $name$_base64: String read Get$name$_base64;\n"
							,"name",PropertyName(field)
							,"pname",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_MESSAGE) {
					const Descriptor *subtype = field->message_type();
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
							"    property $name$: TPB_$subname$s read F$name$;\n"
							,"name",PropertyName(field),"subname",subtype->name());
					} else {
						printer.Print(
							"    property $name$: TPB_$subname$ read F$name$;\n","name",field->name(),"subname",subtype->name());
					}
				}
			}
			printer.Print(
				"  end;\n"
				"\n"
				"  TPB_$name$s = TObjectList<TPB_$name$>;\n"
				"\n"
				"implementation\n"
				"\n"
				"uses\n"
				"  pbPublic, uCommon;\n"
				"\n"
				"\n"
				"constructor TPB_$name$.Create("
				,"name",message->name());
			CreateArguments(&printer,message);
			printer.Print(");\nbegin\n");
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() != FieldDescriptor::LABEL_REPEATED) {
						printer.Print("  F$name$ := A$name$;\n","name",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_INT32) {
					if (field->label() != FieldDescriptor::LABEL_REPEATED) {
						printer.Print("  F$name$ := A$name$;\n","name",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_STRING) {
					if (field->label() != FieldDescriptor::LABEL_REPEATED) {
						printer.Print("  F$name$ := A$name$;\n","name",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_BOOL) {
					if (field->label() != FieldDescriptor::LABEL_REPEATED) {
						printer.Print("  F$name$ := A$name$;\n","name",PrivateFieldName(field));
					}
				}
			}
			printer.Print(
				"end;\n"
//				"{ TPBR_$name$ }\n"
				"destructor TPB_$name$.Destroy;\n"
				"begin\n"
				,"name",message->name());
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_MESSAGE) {
					if (field->label() == FieldDescriptor::LABEL_REQUIRED) {
						printer.Print("  if Assigned(F$name$) then F$name$.Free;\n","name",field->camelcase_name());
					} else if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print("  F$name$.Free;\n","name",field->camelcase_name());
					}
				}
			}
			printer.Print(
				"  inherited;\n"
				"end;\n"
				"procedure TPB_$name$.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);\n"
				"var\n"
				"  tag,field_number,wire_type,endpos,SizeTemp : Integer;\n"
				"begin\n"
				"  endpos := AProtobufReader.getPos + ASize;\n"
				"  while (AProtobufReader.getPos < endpos) and\n"
				"        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin\n"
				"    case field_number of\n",
				"name",message->name());
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				string name = field->name();
				UpperString(&name);
				if (field->type() == FieldDescriptor::TYPE_INT32) {
					printer.Print(
						"      FN_$name$:\n"
						"        begin\n"
						"          Assert(wire_type = WIRETYPE_VARINT);\n"
						"          F$pname$ := AProtobufReader.readInt32;\n"
						"        end;\n","name",name
						,"pname",PrivateFieldName(field));
				} else if (field->type() == FieldDescriptor::TYPE_STRING) {
					printer.Print(
						"      FN_$name$:\n"
						"        begin\n"
						"          Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);\n"
						"          F$pname$ := AProtobufReader.readString;\n"
						"        end;\n"
						,"pname",PrivateFieldName(field)
						,"name",name);
				} else if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
						"      FN_$name$:\n"
						"        begin\n"
						"          Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);\n"
						"          SetLength(F$pname$, Length(F$pname$) + 1);\n"
						"          AProtobufReader.readBytes(F$pname$[Length(F$pname$)-1]);\n"
						"        end;\n"
						,"name",name
						,"pname",PrivateFieldName(field));
					} else {
						printer.Print(
						"      FN_$name$:\n"
						"        begin\n"
						"          Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);\n"
						"          SizeTemp := AProtobufReader.readInt32;\n"
						"          SetLength(F$pname$,SizeTemp);\n"
						"          AprotobufReader.readRawBytes(F$pname$[0],SizeTemp);\n"
						"        end;\n"
						,"name",name
						,"pname",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_MESSAGE) {
					const Descriptor *subtype = field->message_type(); 
					if (field->label() == FieldDescriptor::LABEL_REPEATED) {
						printer.Print(
							"        FN_$name$:\n"
							"          begin\n"
							"            Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);\n"
							"            if not Assigned(F$pname$) then\n"
							"              F$pname$ := TPB_$subname$s.Create;\n"
							"            F$pname$.Add(TPB_$subname$.Create(AProtobufReader,AProtobufReader.readInt32));\n"
							"          end;\n"
							,"name",name
							,"pname",PrivateFieldName(field)
							,"subname",subtype->name());
					} else {
						printer.Print(
							"      FN_$name$:\n"
							"        begin\n"
							"          Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);\n"
							"          if not Assigned(F$name$) then\n"
							"            F$name$ := TPB_$subname$.Create;\n"
							"          F$name$.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);\n"
							"        end;\n"
							,"name",name
							,"subname",subtype->name());
					}
				}
			}
			printer.Print(
				"      else\n"
				"        AProtobufReader.skipField(tag);\n"
				"    end;\n"
//				"    tag := AProtobufReader.readTag;\n"
				"  end;\n"
				"end;\n"
				"function TPB_$name$.GetProtobuf: TProtoBufOutput;\n"
				"var\n"
				"  pboutput: TProtoBufOutput;\n"
				"begin\n"
				"  pboutput := TProtoBufOutput.Create;\n","name",message->name());
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				string name = field->name();
				UpperString(&name);
				if (field->type() == FieldDescriptor::TYPE_INT32) {
					if (field->label() == FieldDescriptor::LABEL_OPTIONAL) {
						printer.Print(
							"  if F$pname$ <> 0 then\n"
							"    pboutput.writeInt32(FN_$name$,F$pname$);\n"
							,"name",field->name()
							,"pname",PrivateFieldName(field));
					} else {
						printer.Print("  pboutput.writeInt32(FN_$name$,F$pname$);\n",
						"name",name
						,"pname",PrivateFieldName(field));
					}
				} else if (field->type() == FieldDescriptor::TYPE_STRING) {
					if (field->label() == FieldDescriptor::LABEL_OPTIONAL) {
						printer.Print(
							"  if F$pname$ <> '' then\n"
							"    pboutput.writeString(FN_$name$,F$pname$);\n"
							,"name",field->name()
							,"pname",PrivateFieldName(field));
					} else {
						printer.Print(
							"  pboutput.writeString(FN_$name$,F$pname$);\n"
							,"name",name
							,"pname",PrivateFieldName(field));
					}
				}
			}
			printer.Print(
				"  result := pboutput;\n"
				"end;\n");
			for (int j=0; j<message->field_count(); j++) {
				const FieldDescriptor *field = message->field(j);
				if (field->type() == FieldDescriptor::TYPE_BYTES) {
					if (field->label() == FieldDescriptor::LABEL_REQUIRED) {
//						printer.Print(
//							"function TPB_$name$.Get$type$_hex: String;\n"
//							"var\n"
//							"  C1 : Integer;\n"
//							"begin\n"
//							"  result := '';\n"
//							"  for C1 := 0 to F$type$_size - 1 do\n"
//							"    result := result + IntToHex(F$type$_bytes[C1],2);\n"
//							"  result := LowerCase(result);\n"
//							"end;\n"
//							"function TPB_$name$.Get$type$_base64: String;\n"
//							"begin\n"
//							"  result := EncodeBase64(F$type$_bytes,F$type$_size)\n"
//							"end;\n"
//							,"name",message->name()
//							,"type",field->camelcase_name()
//						);
					}
				}
			}
			printer.Print(
				"end.\n");
		}
		for (int i=0; i<file->enum_type_count(); i++) {
			const EnumDescriptor *type = file->enum_type(i);
			string name = type->name();
			//cerr << name;
			for (int j=0; j<type->value_count(); j++) {
				const EnumValueDescriptor *value = type->value(j);
				//cerr << value->name() << " = " << value->number() << "\n";
			}
		}
		return true;
	}
};
int main(int argc, char *argv[]) {
	DelphiGenerator *gen = new DelphiGenerator();
	return google::protobuf::compiler::PluginMain(argc,argv,gen);
}
