package Poker;

import "common.proto";
import "extra.proto";

enum ServerCodes {
	srNotImplemented = 0;
	srHello = 1;
	srLoginReply = 2;
	srRegisterReply = 3;
	srCreateClubReply = 4;
	srJoinClubReply = 5;
	srLeaveClubReply = 6;
	srChangeClubDetailsReply = 7;
	srLogout = 8;
	srKickPlayerReply = 11;
	srSetAvatarReply = 12;
	srChangeMailReply = 13;
	srGetPlayers = 14;
	srSubscriptionPlanChange = 15;
	srOwnershipGiveAwayNotOwner = 16;
	srOwnershipGiveAwayInvalidPlayerId = 17;
	srOwnershipGiveAwayInvalidClubId = 18;
	srOwnershipGiveAwayOk = 19;
	srClubDisbandOk = 20;
	srTournamentOpenTable = 21;
	srChangePasswordOk = 23;
	srCreateGameOk = 24;
	srDeleteGameOk = 25;
	srTableSitOk = 27;
	srTableSitSeatTaken = 28;
	srTableStandUpOk = 29;
	srPong = 30;
	srSuspendPlayerOk = 31;
	srReinstatePlayerOk = 32;
	srTableAddonOk = 33;
	srTableAddonOverLimit = 34;
	srTableStatsReply = 35;
	srContactUsOk = 36;
	srTableBuyinLessThanCashout = 37;
	srInvalidTableBuyin = 38;
	srPlayerLimitOk = 39;
	srResetPlayerBalanceOk = 40;
	srClubBalanceReached = 41;
	srHandHistoryMsg = 42;
	srQueryAssetsReply = 43;
	srNotSitting = 44;
	srTournamentReply = 45;
	srTournamentDetails = 46;
	
	seChat = 50;
	seSecondaryLoginDetected = 51;
	seAccountConfirmed = 52;
	seClubChange = 53;
	seClubDeleted = 54;
	seGameChange = 55;
	seGameCreate = 56;
	seGameDelete = 57;
	seTableStatus = 58;
	seTournamentList = 59;
	seUserChange = 60;
	seTournamentPlayerFinished = 61;
	seTournamentPlayerTransfer = 62;
	sePlayerClubStatus = 63;
	
	scHello = 70;
	scLogin = 71;
	scTournamentRegister = 72;
	scRegister = 73;
	scForgotPassword = 74;
	scLogout = 75;
	scCreateClub = 76;
	scJoinClub = 77;
	scKickPlayer = 78;
	scLeaveClub = 79;
	scGiveClubOwnership = 80;
	scChangeClubDetails = 81;
	scDeleteClub = 82;
	scSubscriptionPlanChange = 83;
	scChangeEmail = 84;
	scChangePassword = 85;
	scSetAvatar = 86;
	scCreateGame = 87;
	scCloseGame = 88;
	scTableJoin = 89;
	scTableLeave = 90;
	scTableSit = 91;
	scTableStandUp = 92;
	scPing = 93;
	scSuspendPlayer = 94;
	scGetPlayers = 95;
	scFold = 96;
	scPutChips = 97;
	scTableAddOn = 98;
	scTablePlayNow = 99;
	scTableSitOutNextHand = 100;
	scTableSitOutNextBB = 101;
	scResendVerificationMail = 102;
	scShowCards = 103;
	scQueryTableStats = 104;
	scContactUs = 105;
	scSetPlayerLimit = 106;
	scResetPlayerBalance = 107;
	scQueryAssets = 108;
	scTournamentUnregister = 109;
	scTournamentLobbyOpen = 110;
	scTournamentLobbyClose = 111;
	scTournamentQueryInfo = 112;
	scTableSitOpen = 113;
	scResetPlayerBalances = 114;
	scDeleteTableStats = 115;
	scMutePlayer = 116;
	scChangePlayerManagerState = 117;
	scSplitTableCards = 118;
}

message StringSizes {
	required int32 email = 1;
	required int32 password = 2;
	required int32 clubname = 3;
	required int32 invcode = 4;
	required int32 username = 5;
	required int32 gamename = 6;
	required int32 ContactMessage = 7;
}

message ValidCharsRegex {
    required string email = 1;
    required string username = 2;
    required string password = 3;
    required string clubname = 4;
    required string clubpassword = 5;
    required string gamename = 6;
}

message HelloReply {
	required StringSizes stringSizes = 1;
	required int32 ChangeExpireTime = 2;
	required int32 ForgotExpireTime = 3;
	required int32 max_play_time = 4;
	required int32 max_timebank = 5 [ default = 60000 ];
	required StringSizes minSizes = 6;
	repeated UpdateFileInfo update_files = 7;
	required ValidCharsRegex valid_chars_regex = 8;
}

message HelloParams {
	required bool debug = 1;
	repeated UpdateFileInfo files = 2;
}

message UpdateFileInfo {
	enum UpdateFileType {
		ufFull = 0;
		ufDiff = 1;
		ufRemove = 2;
	}
	required string path = 1;
	optional bytes hash = 2;
	optional string url = 3;
	optional UpdateFileType file_type = 4;
	optional uint32 file_size = 5;
}

message LoginParams {
	required string username = 1;
	required string password = 2;
}

message RegisterParams {
	required string email = 1;
	required string password = 2;
	required string displayName = 3;
}

message ForgotPasswordParams {
	required string email = 1;
}

message LoginReply {
	enum LoginStatus {
		lrSuccess = 0;
		lrInvalid = 1;
	}
	required LoginStatus login_status = 1;
	repeated TableStatus reconnect_tables = 3;
	repeated TournamentInfo tournament_infos = 4;
	repeated bytes registered_tournaments = 5 [(ObjectId)=true];
	repeated Club clubs = 6;
	repeated User users = 7;
	optional User self = 8;
	repeated Game games = 9;
	repeated PlayerClubStatus player_club_statuses = 10;
}

message ClubMember {
	required bytes _id = 1 [(ObjectId)=true];
	optional bool suspended = 2;
	optional uint32 balance_limit = 3;
	optional int32 club_balance = 4;
	optional bool unlimited_limit = 5;
	optional bool muted = 6;
	optional bool manager = 7;
}

message Club {
	optional bytes _id = 1 [(ObjectId)=true];
	repeated ClubMember members = 2;
	optional string name = 3;
	optional bytes owner = 4 [(ObjectId)=true];
	optional string password = 5;
	optional bool is_private = 6;
	optional int32 seq = 7;
	optional bool has_password = 8;
	optional uint32 rake = 9;
	optional uint32 default_balance_limit = 10;
	optional bool unlimited_default_balance = 11;
	optional uint32 buyin_reset = 12;
}

message User {
	enum PlayerSubscriptionPlan {
		pspBasic = 0;
		pspNormal = 1;
		pspSuper = 2;
	}
	required bytes _id = 1 [(ObjectId)=true];
	optional bytes avatar = 2;
	required string displayname = 3;
	
	optional string email = 5;
	optional bool authed = 6;
	optional PlayerSubscriptionPlan subscription_plan = 7;
}

message SubscriptionPlanChange {
	required User.PlayerSubscriptionPlan subscription_plan = 1;
	optional string url = 2;
	optional string stripe_token = 3;
}

message Game {
	enum GameLimit {
		glNoLimit = 0;
		glPotLimit = 1;
		glFixedLimit = 2;
	}
	enum GameType {
		gtHoldem = 0;
		gtOmaha = 1;
		gtRotationNLHPLO = 2;
	}
	enum GameState {
		gsActive = 0;
		gsClosing = 1;
		gsClosed = 2;
		gsEmpty = 3;
	}
	
	enum GameBlinds {
		gb1x2 = 0;
		gb5x5 = 1;
		gb5x10 = 2;
		gb10x25 = 3;
		gb25x50 = 4;
		gb50x100 = 5;
		gbOther = 6;
	}
	
	optional bytes _id = 1 [(ObjectId)=true];
	optional bytes creator_mongo_id = 2 [(ObjectId)=true];
	optional string gamename = 3;
	optional bytes club_mongoid = 4 [(ObjectId)=true];
	optional GameType game_type = 5;
	optional GameLimit game_limit = 6;
	optional GameBlinds blinds = 7;
	optional int32 seats = 9;
	optional int32 sitting = 10;
	optional uint32 buyin_min = 11;
	optional uint32 buyin_max = 12;
	optional GameState state = 13;
	optional uint32 closetime = 14;
	optional uint32 lasthandid = 15;
	optional bytes tournament = 16 [(ObjectId)=true];
	optional uint32 small_blind = 17;
	optional uint32 big_blind = 18;
	optional bool final_table = 19;
}

message ListClubsReply {
	repeated Club clubs = 1;
}

message KickPlayerParams {
	required bytes club_mongo_id = 1 [(ObjectId)=true];
	required bytes player_mongo_id = 2 [(ObjectId)=true];
}

message GiveClubOwnershipParams {
	required bytes club_mongo_id = 1 [(ObjectId)=true];
	required bytes player_mongo_id = 2 [(ObjectId)=true];
}

message ChangeEMailParams {
	required string new_mail = 1;
}

message ChangePasswordParams {
	required string new_password = 1;
}

message SetAvatarParams {
	required bytes avatar_id = 1;
}
message SetAvatarReply {
	enum SetAvatarStatus {
		saSuccess = 0;
		saNotFound = 1;
	}
	required SetAvatarStatus status = 1;
}

message ChatEvent {
	enum EventType {
		ceUserMessage = 0;
		ceServerMessage = 1;
	}
	required EventType event = 1;
	required ChatMessage msg = 2;
	optional bytes table_id = 3 [(ObjectId)=true];
}

message ChatMessage {
	optional bytes _id = 1 [(ObjectId)=true];
	optional string username = 2;
	required string msg = 3;
	optional uint32 timestamp = 4;
}

service Server {
	rpc Login (LoginParams) returns (LoginReply);
}

message PingParams {
	required uint32 uptime = 1;
}

message PingReply {
	required uint32 uptime = 1;
	required uint64 servertime = 2;
}

message TableSit {
	required bytes game_id = 1 [(ObjectId)=true];
	optional int32 seat_index = 2;
	required uint32 chips = 3;
}

message Pot {
	required uint32 value = 1;
	repeated int32 members = 2;
	repeated TableEvent.WinnerData WinnerData = 3;
	optional uint32 rake = 4;
}

message TableStatus {
	enum TableState {
		tsIdle = 0;
		tsPreFlop = 1;
		tsFlop = 2;
		tsTurn = 3;
		tsRiver = 4;
		tsWinning = 5;
		tsWinning2 = 6;
	}

	enum TableType {
		ttLive = 0;
		ttTournament = 1;
		ttHandReplay = 2;
	}
	
	required bytes table_mongo_id = 1 [(ObjectId)=true];
	repeated SeatInfo seats = 2;
	required TableState state = 3;
	required int32 dealer = 4;
	required int32 current_seat = 5;
	repeated uint32 bets = 6;
	required bool locked = 11;
	optional int32 seq = 12;
	optional uint32 minimum_bet = 13;
	optional uint32 maximum_raise = 14;
	optional uint32 small_blind = 15;
	optional uint32 big_blind = 16;
	optional uint32 handid = 17;
	optional uint64 time = 18;
	repeated TableEvent events = 19;
	repeated Pot pots = 20;
	optional uint32 rake_percent = 21;
	optional Game.GameType current_game = 22;
	optional uint32 rotation = 23;
	optional Game.GameLimit game_limit = 25;
	optional uint32 minimum_raise = 26;
	required TableType table_type = 27;
	repeated TableMessage table_message = 28;
}

message SeatInfo {
	enum PlayerStatus {
		psOutOfPlay = 0;
		psOutOfHand = 1;
		psInHand = 2;
		psFolded = 3;
		psAllIn = 4;
	}
	required int32 seat_index = 1;
	required bytes player_mongo_id = 2 [(ObjectId)=true];
	required uint32 chips = 3;
	optional int32 card_count = 4;
	optional bytes cards = 5;
	required PlayerStatus status = 6;
	required uint32 timebank = 7;
	required bool cards_visible = 8;
	required bool disconnected = 9;
	optional bool can_show = 10;
	optional bool autoplay = 11;
}

message ChangeClubPlayerFlag {
	required bytes club_mongo_id = 1 [(ObjectId)=true];
	required bytes player_mongo_id = 3 [(ObjectId)=true];
	required bool flag = 2;
}

message RegisterReply {
	enum RegisterStatus {
		regSuccess = 0;
		regDuplicateEmail = 1;
		regDupUsername = 2;
		regInvalidEmail = 3;
		regInvalidName = 4;
	}
	required RegisterStatus status = 1;
}

message ClubCommandReply {
	enum ClubStatus {
		csSuccess = 0;
		csInvalidName = 1;
		csInvalidPassword = 2;
		csNameExists = 3;
		csInvalidClubId = 4;
		csAlreadyMember = 5;
		csInvalidPlayerId = 6;
	}
	required ClubStatus status = 1;
	optional Club club = 2;
	repeated Game games = 3;
}

message ChangeMailReply {
	enum ChangeMailStatus {
		cmSuccess = 0;
		cmDuplicateMail = 1;
		cmInvalidEmail = 2;
	}
	required ChangeMailStatus status = 1;
}

message GetUserParams {
	repeated bytes user_mongo_ids = 1 [(ObjectId)=true];
	repeated User users = 2;
}

message TableEvent {
	enum TableEventType {
		teFold = 0;
		teSit = 1;
		teStandUp = 2;
		teWinning = 3;
		teDealing = 4;
		teCheck = 5;
		teCall = 6;
		teRaise = 7;
		teAllIn = 8;
		teFlop = 9;
		teTurn = 10;
		teRiver = 11;
		tePostRiver = 12;
		tePreWin = 13;
		teExistingCards = 14;
		teDisconnect = 15;
		teSB = 16;
		teBB = 17;
		teForced = 18;
	}
	message WinnerData {
		enum CardRankings {
			crRoyalFlush = 0;
			crStraightFlush = 1;
			cr4OfKind = 2;
			crFullHouse = 3;
			crFlush = 4;
			crStraight = 5;
			crThreeOfKind = 6;
			crTwoPair = 7;
			crOnePair = 8;
			crHighCard = 9;
		}
		required int32 seat = 3;
		required string msg = 4;
	}
	required TableEventType event = 1;
	optional int32 seat = 2;
	repeated Pot pots = 4;
	repeated uint32 bets = 5;
	optional bytes cards = 6;
}

message PutChips {
	required bytes table_mongo_id = 1 [(ObjectId)=true];
	required uint32 chip_amount = 2;
	required TableStatus.TableState current_state = 3;
}

message TableBoolFlag {
	required bytes table_mongo_id = 1 [(ObjectId)=true];
	required bool flag = 2;
}

message UserChangeParams {
	repeated User users = 1;
}

message CloseGameData {
	enum CloseGameTime {
		cgtCurrentHand = 0;
		cgtFiveMinutes = 1;
		cgtFifteenMinutes = 2;
	}
	required bytes gameid = 1 [(ObjectId)=true];
	required CloseGameTime timestamp = 2;
}

message QueryTableStats {
	repeated bytes gameid = 1 [(ObjectId)=true];
}

message TableStatsReplies {
	repeated TableStatsReply reply = 1;
	repeated User players = 2;
	repeated ClubStatsReply club_stats = 3;
}

message TableStatsReply {
	required bytes clubid = 1 [(ObjectId)=true];
	required bytes gameid = 2 [(ObjectId)=true];
	repeated TablePlayerStats playerstats = 3;
	optional uint32 hands = 4;
}

message TablePlayerStats {
	required bytes userid = 1 [(ObjectId)=true];
	optional int32 balance = 3;
	repeated uint32 buyins = 4;
	repeated uint32 cashouts = 5;
	optional uint32 rakecontrib = 6;
	optional uint32 secondsplayed = 7;
	optional uint32 chipsinplay = 8;
	optional uint32 hands = 9;
}

message ClubStatsReply {
	required bytes clubid = 1 [(ObjectId)=true];
	repeated ClubPlayerStats player_stats = 2;
}

message ClubPlayerStats {
	required bytes userid = 1 [(ObjectId)=true];
	required int32 club_balance = 2;
}

message ContactMessage {
	enum ContactReason {
		cmQuestions = 0;
		cmSuggestions = 1;
		cmBugReport = 2;
		cmOther = 3;
	}
	required ContactReason reason = 1;
	required string message = 2;
}

message BuyinError {
	required bytes game_id = 1 [(ObjectId)=true];
	required uint32 last_cashout = 2;
}

message PlayerLimitParams {
	required bytes clubid = 1 [(ObjectId)=true];
	optional bytes userid = 2 [(ObjectId)=true];
	optional uint32 limit = 3;
	optional bool unlimited = 4;
}

message HandHistoryReply {
	optional bytes club_id = 1 [(ObjectId)=true];
	required bytes gameid = 2 [(ObjectId)=true];
	repeated HandHistory rows = 3;
	//repeated GameEventHistory events = 4;
	optional bytes tournament_id = 4 [(ObjectId)=true];
}

message HandHistory {
	message PlayerHandHistory {
		required bytes _id = 1 [(ObjectId)=true];
		required int32 seat = 2;
		optional bytes cards = 3;
		required uint32 chips = 4;
		required string nick = 5;
		optional bool muck = 6;
		required SeatInfo.PlayerStatus status = 7;
	}
	message HandHistoryMove {
		repeated TableEvent.TableEventType code = 1;
		optional uint32 bet = 2;
		optional int32 seat = 3;
		repeated Pot WinnerPotData = 4;
		repeated Pot pots = 5;
	}
	required bytes _id = 1 [(ObjectId)=true];
	required uint32 seq = 2;
	required uint32 totalrake = 3;
	repeated PlayerHandHistory players = 4;
	required bytes cards = 5;
	required uint32 endtime = 6;
	repeated int32 balance_changes = 7;
	repeated HandHistoryMove moves = 8;
	required uint32 dealer = 9;
	optional Game game = 10;
	optional Game.GameType current_game = 11;
	required int32 rake = 12;
}

message AssetList {
	repeated UpdateFileInfo assets = 1;
}

message TournamentList {
	repeated TournamentInfo items = 1;
}

message TournamentDetails {
	required bytes _id = 1 [(ObjectId)=true];
}

message TournamentMember {
	required bytes _id = 1 [(ObjectId)=true];
	required string displayname = 2;
	required uint32 chips = 3;
	optional bytes gameid = 4 [(ObjectId)=true];
	optional int32 position = 5;
	optional uint32 seat_index = 6;
}

message TournamentInfo {
	enum TournamentState {
		tnsOpen = 0;
		tnsInProgress = 1;
		tnsCancelled = 2;
		tnsOnBreak = 3;
		tnsStarting = 4;
		tnsFinished = 5;
	}
	required bytes _id = 1 [(ObjectId)=true];
	required string name = 2;
	required string description = 3;
	required Game.GameType gametype = 4;
	required Game.GameLimit limit = 5;
	required uint32 seats_per_table = 6;
	required uint32 minplayers = 7;
	required uint32 maxplayers = 8;
	required uint32 startingchips = 9;
	required uint32 timeperlevel = 10;
	required uint32 registered_players = 11;
	required uint32 start_time = 12;
	repeated TournamentMember players = 13;
	required TournamentState state = 14;
	repeated Game games = 15;
	repeated GameBlinds blind_structure = 16;
	optional uint32 current_blind_level = 17;
	optional uint64 current_blind_level_end_time = 18;
	repeated TournamentPrize prizes = 19;
}

message TournamentCommandParams {
	enum TournamentCommandEnum {
		tceRegisterOk = 0;
		tceAlreadyRegistered = 1;
		tceRegisterLimitReached = 2;
		tceRegisterFailed = 3;
		tceUnregisterOk = 4;
		tceNotOpen = 5;
	}
	required bytes _id = 1 [(ObjectId)=true];
	optional TournamentCommandEnum reply_status = 2;
}

message TournamentTableStart {
	required Game game = 1;
	required TableStatus table_status = 2;
}

message TournamentPlayerFinished {
	required bytes tournament_id = 1 [(ObjectId)=true];
	required bytes player_id = 2 [(ObjectId)=true];
	required int32 place = 3;
	optional TournamentPrize prize = 4;
	required bytes table_id = 5 [(ObjectId)=true];
}

message GameBlinds {
	required uint32 sb = 1;
	required uint32 bb = 2;
}

message TableMessage {
	enum TableMessageType {
		tmtClosing = 0;
		tmtTournamentBreak = 1;
		tmtTournamentStart = 2;
	}
	
	required TableMessageType message = 1;
	optional uint64 end_time = 2;
}

message TournamentPlayerTransfer {
	required bytes game_source = 1 [(ObjectId)=true];
	required bytes game_destination = 2 [(ObjectId)=true];
	required bytes user_id = 3 [(ObjectId)=true];
	required uint32 seat_source = 4;
	required uint32 seat_destination = 5;
}

message TournamentPrize {
	required int32 place = 1;
	required string name = 2;
}

message PlayerClubStatus {
	required bytes clubid = 1 [(ObjectId)=true];
	optional bytes tableid = 2 [(ObjectId)=true];
	optional uint32 buyin_min = 3;
	optional uint32 buyin_max = 4;
}

message DeleteTableStats {
	required bytes club_id = 1 [(ObjectId)=true];
	repeated bytes table_id = 2 [(ObjectId)=true];
}