package Poker;

option optimize_for = LITE_RUNTIME;

import "common.proto";

enum ServerCodes {
	srNotImplemented = 0;
	srHello = 1;
	srLoginReply = 2;
	srRegisterReply = 3;
	srCreateClubReply = 4;
	srJoinClubReply = 5;
	srLeaveClubReply = 6;
	srChangeClubDetailsReply = 7;
	srLogout = 8;
	srListClubs = 9;
	srStatus = 10;
	srKickPlayerReply = 11;
	srSetAvatarReply = 12;
	srChangeMailReply = 13;
	srGetPlayers = 14;
	srTableSitNoChips = 15;
    srOwnershipGiveAwayNotOwner = 16;
    srOwnershipGiveAwayInvalidPlayerId = 17;
    srOwnershipGiveAwayInvalidClubId = 18;
    srOwnershipGiveAwayOk = 19;
    srClubDisbandOk = 20;
    srTransferChipsOk = 21;
	srTransferChipsInvalidAmount = 22;
    srChangePasswordOk = 23;
    srCreateGameOk = 24;
    srDeleteGameOk = 25;
    srEditGameOk = 26;
    srTableSitOk = 27;
    srTableSitSeatTaken = 28;
    srTableStandUpOk = 29;
	srPong = 30;
    srSuspendPlayerOk = 31;
    srReinstatePlayerOk = 32;
	srTableAddonOk = 33;
	srTableAddonOverLimit = 34;
	srTableStatsReply = 35;
	srContactUsOk = 36;
	srTableBuyinLessThanCashout = 37;
	srInvalidTableBuyin = 38;
	srPlayerLimitOk = 39;
	srResetPlayerBalanceOk = 40;

    seChat = 50;
    seSecondaryLoginDetected = 51;
    seAccountConfirmed = 52;
    seClubChange = 53;
    seClubDeleted = 54;
	seGameChange = 55;
	seGameCreate = 56;
	seGameDelete = 57;
	seTableStatus = 58;
	seTransferChips = 59;
	seUserChange = 60;

	scHello = 70;
    scLogin = 71;
    scStatus = 72;
    scRegister = 73;
    scForgotPassword = 74;
    scLogout = 75;
    scCreateClub = 76;
    scJoinClub = 77;
    scKickPlayer = 78;
    scLeaveClub = 79;
    scGiveClubOwnership = 80;
    scChangeClubDetails = 81;
    scDeleteClub = 82;
    scTransferChips = 83;
    scChangeEmail = 84;
    scChangePassword = 85;
    scSetAvatar = 86;
    scCreateGame = 87;
    scCloseGame = 88;
    scTableJoin = 89;
    scTableLeave = 90;
    scTableSit = 91;
    scTableStandUp = 92;
	scPing = 93;
    scSuspendPlayer = 94;
    scGetPlayers = 95;
	scFold = 96;
	scPutChips = 97;
	scTableAddOn = 98;
	scTablePlayNow = 99;
	scTableSitOutNextHand = 100;
	scTableSitOutNextBB = 101;
	scResendVerificationMail = 102;
	scShowCards = 103;
	scQueryTableStats = 104;
	scContactUs = 105;
	scSetPlayerLimit = 106;
	scResetPlayerBalance = 107;
}

message StringSizes {
	required int32 email = 1;
	required int32 password = 2;
	required int32 clubname = 3;
	required int32 invcode = 4;
	required int32 username = 5;
	required int32 gamename = 6;
	required int32 ContactMessage = 7;
}

message ValidCharsRegex {
    required string email = 1;
    required string username = 2;
    required string password = 3;
    required string clubname = 4;
    required string clubpassword = 5;
    required string gamename = 6;
}

message HelloReply {
	required StringSizes stringSizes = 1;
	required int32 ChangeExpireTime = 2;
	required int32 ForgotExpireTime = 3;
	required int32 max_play_time = 4;
	required int32 max_timebank = 5 [ default = 60000 ];
	required StringSizes minSizes = 6;
	repeated UpdateFileInfo update_files = 7;
	required ValidCharsRegex valid_chars_regex = 8;
}

message HelloParams {
	required bool debug = 1;
	repeated UpdateFileInfo files = 2;
}

message UpdateFileInfo {
	enum UpdateFileType {
		ufFull = 0;
		ufDiff = 1;
		ufRemove = 2;
	}
	required string path = 1;
	optional bytes hash = 2;
	optional string url = 3;
	optional UpdateFileType file_type = 4;
	optional uint32 file_size = 5;
}

message LoginParams {
	required string username = 1;
	required string password = 2;
}

message RegisterParams {
	required string email = 1;
	required string password = 2;
	required string displayName = 3;
}

message ForgotPasswordParams {
	required string email = 1;
}

message LoginReply {
	enum LoginStatus {
		lrSuccess = 0;
		lrInvalid = 1;
	}
	required LoginStatus login_status = 1;
	optional StatusReply status = 2;
	repeated TableStatus reconnect_tables = 3;
}

message ClubMember {
	required bytes _id = 1;
	optional bool suspended = 2;
	optional uint32 balance_limit = 3;
	optional int32 club_balance = 4;
	optional bool unlimited_limit = 5;
}

message Club {
	optional bytes _id = 1;
	repeated ClubMember members = 2;
	optional string name = 3;
	optional bytes owner = 4;
	optional string password = 5;
	optional bool is_private = 6;
	optional int32 seq = 7;
	optional bool has_password = 8;
	optional uint32 rake = 9;
	optional uint32 default_balance_limit = 10;
	optional bool unlimited_default_balance = 11;
}

message User {
	required bytes _id = 1;
	optional bytes avatar = 2;
	required string displayname = 3;
	
	optional string email = 5;
	optional bool authed = 6;
	optional uint32 chips = 7;
}

message Game {
	enum GameLimit {
		glNoLimit = 0;
		glPotLimit = 1;
		glFixedLimit = 2;
	}
	enum GameType {
		gtHoldem = 0;
		gtOmaha = 1;
		gtRotationNLHPLO = 2;
	}
	enum GameState {
		gsActive = 0;
		gsClosing = 1;
		gsClosed = 2;
		gsEmpty = 3;
	}
	
	enum GameBlinds {
		gb1x2 = 0;
		gb5x5 = 1;
		gb5x10 = 2;
		gb10x25 = 3;
		gb25x50 = 4;
		gb50x100 = 6;
	}
	
	optional bytes _id = 1;
	optional bytes creator_mongo_id = 2;
	optional string gamename = 3;
	optional int32 clubseq = 4;
	optional GameType game_type = 5;
	optional GameLimit game_limit = 6;
	optional GameBlinds blinds = 7;
	optional int32 seats = 9;
	optional int32 sitting = 10;
	optional int32 buyin_min = 11;
	optional int32 buyin_max = 12;
	optional GameState state = 13;
	optional uint64 closetime = 14;
	optional uint32 lasthandid = 15;
}

message StatusReply {
	repeated Club clubs = 1;
	repeated User users = 2;
	required User self = 3;
	repeated Game games = 4;
}

message ListClubsReply {
	repeated Club clubs = 1;
}

message KickPlayerParams {
	required int32 club_seq = 1;
	required bytes player_mongo_id = 2;
}

message GiveClubOwnershipParams {
	required int32 club_seq = 1;
	required bytes player_mongo_id = 2;
}

message TransferChipsParams {
	required bytes player_mongo_id = 2;
	required uint32 chip_amount = 3;
}

message ChangeEMailParams {
	required string new_mail = 1;
}

message ChangePasswordParams {
	required string new_password = 1;
}

message SetAvatarParams {
	required bytes avatar_id = 1;
}
message SetAvatarReply {
	enum SetAvatarStatus {
		saSuccess = 0;
		saNotFound = 1;
	}
	required SetAvatarStatus status = 1;
}

message ChatEvent {
	enum EventType {
		ceUserMessage = 0;
		ceServerMessage = 1;
	}
	required EventType event = 1;
	required ChatMessage msg = 2;
	optional bytes table_id = 3;
}

message ChatMessage {
	optional bytes _id = 1;
	optional string username = 2;
	required string msg = 3;
	optional int64 timestamp = 4;
}

service Server {
	rpc Login (LoginParams) returns (LoginReply);
}

message PingParams {
	required uint32 uptime = 1;
}

message PingReply {
	required uint32 uptime = 1;
	required uint64 servertime = 2;
}

message TableSit {
	required bytes game_id = 1;
	optional int32 seat_index = 2;
	required uint32 chips = 3;
}

message Pot {
	required uint32 value = 1;
	repeated uint32 members = 2;
}

message TableStatus {
	enum TableState {
		tsIdle = 0;
		tsPreFlop = 1;
		tsFlop = 2;
		tsTurn = 3;
		tsRiver = 4;
		tsWinning = 5;
		tsWinning2 = 6;
	}
	
	required bytes table_mongo_id = 1;
	repeated SeatInfo seats = 2;
	required TableState state = 3;
	required int32 dealer = 4;
	required int32 current_seat = 5;
	repeated uint32 bets = 6;
	required bool locked = 11;
	optional int32 seq = 12;
	optional uint32 minimum_bet = 13;
	optional uint32 maximum_raise = 14;
	optional uint32 small_blind = 15;
	optional uint32 big_blind = 16;
	optional uint32 handid = 17;
	optional uint64 time = 18;
	repeated TableEvent events = 19;
	repeated Pot pots = 20;
	optional uint32 rake_percent = 21;
	optional Game.GameType current_game = 22;
	optional uint32 rotation = 23;
	required uint32 total_balance = 24;
	optional Game.GameLimit game_limit = 25;
	optional uint32 minimum_raise = 26;
}

message SeatInfo {
	enum PlayerStatus {
		psOutOfPlay = 0;
		psOutOfHand = 1;
		psInHand = 2;
		psFolded = 3;
		psAllIn = 4;
	}
	required int32 seat = 1;
	required bytes player_mongo_id = 2;
	required uint32 chips = 3;
	optional int32 card_count = 4;
	optional bytes cards = 5;
	required PlayerStatus status = 6;
	required uint32 timebank = 7;
	required bool cards_visible = 8;
	required bool disconnected = 9;
	optional bool can_show = 10;
}

message ChangeSuspendState {
	required bytes club_mongo_id = 1;
	required bytes player_mongo_id = 3;
	required bool suspended = 2;
}

message RegisterReply {
	enum RegisterStatus {
		regSuccess = 0;
		regDuplicateEmail = 1;
		regDupUsername = 2;
		regInvalidEmail = 3;
		regInvalidName = 4;
	}
	required RegisterStatus status = 1;
}

message ClubCommandReply {
	enum ClubStatus {
		csSuccess = 0;
		csInvalidName = 1;
		csInvalidPassword = 2;
		csNameExists = 3;
		csInvalidClubId = 4;
		csAlreadyMember = 5;
		csInvalidPlayerId = 6;
	}
	required ClubStatus status = 1;
	optional Club club = 2;
	repeated Game games = 3;
}

message ChangeMailReply {
	enum ChangeMailStatus {
		cmSuccess = 0;
		cmDuplicateMail = 1;
		cmInvalidEmail = 2;
	}
	required ChangeMailStatus status = 1;
}

message GetUserParams {
	repeated bytes user_mongo_ids = 1;
	repeated User users = 2;
}

message TableEvent {
	enum TableEventType {
		teFold = 0;
		teSit = 1;
		teStandUp = 2;
		teWinning = 3;
		teDealing = 4;
		teCheck = 5;
		teCall = 6;
		teRaise = 7;
		teAllIn = 8;
		teFlop = 9;
		teTurn = 10;
		teRiver = 11;
		tePostRiver = 12;
		tePreWin = 13;
		teExistingCards = 14;
		teDisconnect = 15;
	}
	message WinnerData {
		enum CardRankings {
			crRoyalFlush = 0;
			crStraightFlush = 1;
			cr4OfKind = 2;
			crFullHouse = 3;
			crFlush = 4;
			crStraight = 5;
			crThreeOfKind = 6;
			crTwoPair = 7;
			crOnePair = 8;
			crHighCard = 9;
		}
		required int32 seat = 3;
		required string msg = 4;
	}
	message WinnerPotInfo {
		required uint32 sum = 1;
		repeated uint32 seats = 2;
		repeated WinnerData WinnerData = 3;
		optional uint32 rake = 4;
	}
	required TableEventType event = 1;
	optional int32 seat = 2;
	repeated WinnerPotInfo pots = 4;
	repeated uint32 bets = 5;
	optional bytes cards = 6;
}

message PutChips {
	required bytes table_mongo_id = 1;
	required uint32 chip_amount = 2;
	required TableStatus.TableState current_state = 3;
}

message TableBoolFlag {
	required bytes table_mongo_id = 1;
	required bool flag = 2;
}

message UserChangeParams {
	repeated User users = 1;
}

message CloseGameData {
	enum CloseGameTime {
		cgtCurrentHand = 0;
		cgtFiveMinutes = 1;
		cgtFifteenMinutes = 2;
	}
	required bytes gameid = 1;
	required CloseGameTime timestamp = 2;
}

message FetchHandHistory {
	message GameQuery {
		required bytes gameid = 1;
		required uint32 lasthandid = 2;
	}
	repeated GameQuery games = 1;
}

message FetchHandReply {
	required string uuid = 1;
}

message QueryTableStats {
	repeated bytes gameid = 1;
}

message TableStatsReplies {
	repeated TableStatsReply reply = 1;
	repeated User players = 2;
}

message TableStatsReply {
	required bytes clubid = 1;
	required bytes gameid = 2;
	repeated TablePlayerStats playerstats = 3;
	optional uint32 hands = 4;
}

message TablePlayerStats {
	required bytes userid = 1;
	optional int32 balance = 3;
	repeated uint32 buyins = 4;
	repeated uint32 cashouts = 5;
	optional uint32 rakecontrib = 6;
	optional uint32 secondsplayed = 7;
	optional uint32 chipsinplay = 8;
	optional uint32 hands = 9;
	optional int32 club_balance = 10;
}

message ContactMessage {
	enum ContactReason {
		cmQuestions = 0;
		cmSuggestions = 1;
		cmBugReport = 2;
		cmOther = 3;
	}
	required ContactReason reason = 1;
	required string message = 2;
}
message BuyinError {
	required bytes game_id = 1;
	required uint32 last_cashout = 2;
}
message PlayerLimitParams {
	required bytes clubid = 1;
	required bytes userid = 2;
	required uint32 limit = 3;
	required bool unlimited = 4;
}
