package Poker;

option optimize_for = LITE_RUNTIME;

message RpcMessage {
	required int32 MethodId = 1;
	optional int32 DataSize = 2 [ default = 0];
	optional int32 Token = 3 [ default = 0];
}

message TokenPrices {
	required int32 club_change_details = 1;
	required int32 club_creation = 2;
}

message StringSizes {
	required int32 email = 1;
	required int32 password = 2;
	required int32 clubname = 3;
	required int32 invcode = 4;
	required int32 username = 5;
	required int32 gamename = 6;
}

message HelloReply {
	required TokenPrices tokenPrices = 1;
	required StringSizes stringSizes = 2;
	required int32 ChangeExpireTime = 3;
	required int32 ForgotExpireTime = 4;
}

message LoginParams {
	required string username = 1;
	required string password = 2;
}

message RegisterParams {
	required string email = 1;
	required string password = 2;
	required string displayName = 3;
}

message ForgotPasswordParams {
	required string email = 1;
}

message LoginReply {
}

message Club {
	optional bytes _id = 1;
	optional int32 chips = 2;
	optional string name = 4;
	optional bytes owner = 5;
	optional string password = 6;
	optional bool is_private = 7;
	optional int32 seq = 8;
	repeated bytes members = 9;
	optional bool has_password = 10;
	optional int32 member_count = 11;
}

message User {
	required bytes _id = 1;
	required bytes avatar = 2;
	required string displayname = 3;
	optional int32 tokens = 4;
	optional string email = 5;
	optional bool authed = 6;
	optional int32 chips = 7;
}

message Game {
	optional bytes _id = 1;
	optional bytes creator_mongo_id = 2;
	optional string gamename = 3;
	optional int32 clubseq = 4;
	optional int32 game_type = 5;
	optional int32 game_limit = 6;
	optional int32 small_blind = 7;
	optional int32 big_blind = 8;
	optional int32 seats = 9;
}

message StatusReply {
	repeated Club clubs = 1;
	repeated User users = 2;
	required User self = 3;
	repeated Game games = 4;
}

message GetDeckReply {
	required string deck = 1;
}

message ListClubsReply {
	repeated Club clubs = 1;
}

message KickPlayerParams {
	required int32 club_seq = 1;
	required bytes player_mongo_id = 2;
}

message GiveClubOwnershipParams {
	required int32 club_seq = 1;
	required bytes player_mongo_id = 2;
}

message TransferChipsParams {
	required int32 club_seq = 1;
	required bytes player_mongo_id = 2;
	required int32 chip_amount = 3;
}

message ChangeEMailParams {
	required string new_mail = 1;
}

message ChangePasswordParams {
	required string new_password = 1;
}

message SetAvatarParams {
	required bytes avatar_id = 1;
}

message ChatEvent {
	enum EventType {
		UserMessage = 0;
		ServerMessage = 1;
	}
	required EventType event = 1;
	required ChatMessage msg = 2;
	optional bytes table_id = 3;
}

message ChatMessage {
	optional bytes _id = 1;
	optional string username = 2;
	required string msg = 3;
	optional int64 timestamp = 4;
}

enum ServerCodes {
	SR_NOT_IMPLEMENTED = 0;
	SR_HELLO = 1;
	SR_LOGIN_OK = 2;
	SR_INVALID_LOGIN = 3;
	SR_LOGOUT = 4;
	SR_REGISTER_OK = 5;
	SR_REGISTER_DUPLICATE_MAIL = 6;
	SR_REGISTER_DUPLICATE_USERNAME = 7;
	SR_REGISTER_INVALID_MAIL = 8;
	SR_LIST_CLUBS = 9;
	SR_STATUS = 10;
	SR_CREATECLUB_OK = 11;
	SR_CREATECLUB_NAME_EXISTS = 12;
	SR_CREATECLUB_INVALID_NAME = 13;
	SR_CREATECLUB_INVALID_CODE = 14;
	SR_JOINCLUB_OK = 15;
	SR_JOINCLUB_INVALID_ID = 16;
	SR_JOINCLUB_INVALID_CODE = 17;
	SR_JOINCLUB_ALREADY_MEMBER = 18;
	SR_LEAVECLUB_OK = 19;
	SR_LEAVECLUB_INVALID_ID = 20;
	SR_KICKPLAYER_OK = 21;
	SR_KICKPLAYER_INVALID_CLUB_ID = 22;
	SR_KICKPLAYER_INVALID_PLAYER_ID = 23;
	SR_OWNERSHIP_GIVEAWAY_NOT_OWNER = 24;
	SR_OWNERSHIP_GIVEAWAY_INVALID_PLAYER_ID = 25;
	SR_OWNERSHIP_GIVEAWAY_INVALID_CLUB_ID = 26;
	SR_OWNERSHIP_GIVEAWAY_OK = 27;
	SR_CLUB_DETAILS_CHANGE_OK = 28;
	SR_CLUB_DETAILS_CLUBNAME_EXISTS = 29;
	SR_CLUB_DISBAND_OK = 30;
	SR_CLUB_TRANFER_CHIPS_OK = 31;
	SR_CLUB_TRANFER_CHIPS_INVALID_AMOUNT = 32;
	SR_CREATECLUB_NO_TOKENS = 33;
	SR_CLUB_DETAILS_CHANGE_NO_TOKENS = 34;
	SR_CHANGE_MAIL_OK = 35;
	SR_CHANGE_MAIL_INVALID_MAIL = 36;
	SR_CHANGE_MAIL_DUPLICATE_MAIL = 37;
	SR_CHANGE_PASSWORD_OK = 38;
	SR_CHANGE_PASSWORD_INVALID_PASSWORD = 39;
	SR_CHANGE_AVATAR_OK = 40;
	SR_CHANGE_AVATAR_INVALID_ID = 41;
	SR_CREATE_GAME_OK = 42;
	SR_DELETE_GAME_OK = 43;
	SR_EDIT_GAME_OK = 44;
	SR_SECONDARY_LOGIN_DETECTED = 45;
	SR_ACCOUNT_CONFIRMED = 46;
	EVENT_CHAT = 47;
	SR_TABLE_STATUS = 48;
    SR_TABLE_SIT_OK = 49;
    SR_TABLE_SIT_SEAT_TAKEN = 50;
    SR_TABLE_STAND_UP_OK = 51;
	SR_PONG = 52;
	SR_SUSPEND_PLAYER_OK = 53;
	SR_SUSPEND_PLAYER_INVALID_ID = 54;
	SR_REINSTATE_PLAYER_OK = 55;
	SR_REINSTATE_PLAYER_INVALID_ID = 56;
	CMD_LOGIN = 501;
	CMD_STATUS = 502;
	CMD_REGISTER = 503;
	CMD_FORGOT_PASSWORD = 504;
	CMD_LOGOUT = 505;
	CMD_LIST_PUBLIC_CLUBS = 506;
	CMD_CREATE_CLUB = 507;
	CMD_JOIN_CLUB = 508;
	CMD_KICK_PLAYER = 509;
	CMD_LEAVE_CLUB = 510;
	CMD_GIVE_CLUB_OWNERSHIP = 511;
	CMD_CHANGE_CLUB_DETAILS = 512;
	CMD_DELETE_CLUB = 513;
	CMD_TRANSFER_CHIPS = 514;
	CMD_CHANGE_EMAIL = 515;
	CMD_CHANGE_PASSWORD = 516;
	CMD_SET_AVATAR = 517;
	CMD_CREATE_GAME = 518;
	CMD_DELETE_GAME = 519;
	CMD_EDIT_GAME = 520;
	CMD_TABLE_JOIN = 521;
	CMD_TABLE_LEAVE = 522;
	CMD_TABLE_SIT = 523;
	CMD_TABLE_STAND_UP = 524;
	CMD_PING = 525;
	CMD_SUSPEND_PLAYER = 526;
	CMD_REINSTATE_PLAYER = 527;
}

service Server {
	rpc Login (LoginParams) returns (LoginReply);
}

message TableSit {
	required bytes game_id = 1;
	required int32 seat_index = 2;
	required int32 chips = 3;
}

message TableStatus {
	required bytes table_mongo_id = 1;
	repeated SeatInfo seats = 2;
	required string state = 3;
}

message SeatInfo {
	required int32 seat = 1;
	required bytes player_mongo_id = 2;
	required int32 chips = 3;
	optional int32 card_count = 4;
	optional string cards = 5;
	optional bool inhand = 6;
}
