unit utCards;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, Poker.Cards, System.Generics.Collections, System.SysUtils;

type
  // Test methods for class TCard

  TestTCard = class(TTestCase)
  strict private
    FCard: TCard;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAssign;
    procedure TestAssign1;
    procedure TestClear;
    procedure TestAsString;
    procedure TestIsKnown;
    procedure TestGetAsString;
    procedure TestSuitAsString;
    procedure TestValueAsString;
    procedure TestByteToString;
  end;
  // Test methods for class TCards

  TestTCards = class(TTestCase)
  strict private
    FCards: TCards;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestAssign;
    procedure TestBytesToString;
  end;

implementation

procedure TestTCard.SetUp;
begin
  FCard := TCard.Create;
end;

procedure TestTCard.TearDown;
begin
  FCard.Free;
  FCard := nil;
end;

procedure TestTCard.TestAssign;
var
  C1: Integer;
begin
  for C1 := Low(Byte) to High(Byte) do
  begin
    FCard.Assign(C1);
    if C1 <= 51 then
      Check(Length(FCard.AsString) = 2)
    else
      Check(Length(FCard.AsString) = 0);
  end;
end;

procedure TestTCard.TestAssign1;
var
  ABytes: TArray<System.Byte>;
  C1, C2: Integer;
begin
  for C1 := 1 to 1000 do
  begin
    SetLength(ABytes, Random(20) + 1);
    for C2 := 0 to High(ABytes) do
      ABytes[C2] := Random(High(Byte) + 1);

    FCard.Assign(ABytes);
    Check(Length(FCard.AsString) in [0, 2])
  end;
end;

procedure TestTCard.TestClear;
begin
  FCard.Clear;
  Check(FCard.AsString = '');
end;

procedure TestTCard.TestAsString;
var
  ReturnValue: string;
begin
  ReturnValue := FCard.AsString;
end;

procedure TestTCard.TestIsKnown;
var
  ReturnValue: Boolean;
begin
  ReturnValue := FCard.IsKnown;
  Check(((not ReturnValue) and (FCard.AsString = '')) or
        (ReturnValue) and (FCard.AsString <> ''));
end;

procedure TestTCard.TestGetAsString;
var
  ReturnValue: string;
  C1: TCardSuit;
  C2: TCardValue;
  expected_len: Integer;
begin
  for C1 := Low(TCardSuit) to High(TCardSuit) do
  begin
    for C2 := Low(TCardValue) to High(TCardValue) do
    begin
      expected_len := 2;
      if C1 = csUnknown then
        Dec(expected_len);
      if C2 = cvUnknown then
        Dec(expected_len);

      ReturnValue := FCard.GetAsString(C2, C1);
      Check(Length(ReturnValue) = expected_len);
    end;
  end;
end;

procedure TestTCard.TestSuitAsString;
var
  ReturnValue: string;
  C1: TCardSuit;
  expected_len: Integer;
begin
  for C1 := Low(TCardSuit) to High(TCardSuit) do
  begin
    expected_len := 1;
    if C1 = csUnknown then
      Dec(expected_len);

    ReturnValue := FCard.SuitAsString(C1);
    Check(Length(ReturnValue) = expected_len);
  end;
end;

procedure TestTCard.TestValueAsString;
var
  ReturnValue: string;
  C1: TCardValue;
  expected_len: Integer;
begin
  for C1 := Low(TCardValue) to High(TCardValue) do
  begin
    expected_len := 1;
    if C1 = cvUnknown then
      Dec(expected_len);

    ReturnValue := FCard.ValueAsString(C1);
    Check(Length(ReturnValue) = expected_len);
  end;
end;

procedure TestTCard.TestByteToString;
var
  ReturnValue: string;
  C1: Integer;
  expected_len: Integer;
begin
  for C1 := Low(Byte) to High(Byte) do
  begin
    expected_len := 2;
    if C1 > 51 then
      expected_len := 0;

    ReturnValue := FCard.ByteToString(C1);
    Check(Length(ReturnValue) = expected_len);
  end;
end;

procedure TestTCards.SetUp;
begin
  FCards := TCards.Create;
end;

procedure TestTCards.TearDown;
begin
  FCards.Free;
  FCards := nil;
end;

procedure TestTCards.TestAssign;
var
  ABytes: TArray<System.Byte>;
  C1, C2, C3: Integer;
  expected_len: Integer;
  rnd_byte: Byte;
begin
  for C1 := 1 to 32 do
  begin
    SetLength(ABytes, C1);
    for C2 := 1 to 1000 do
    begin
      expected_len := 0;
      for C3 := 0 to C1 - 1 do
      begin
        rnd_byte := Random(High(Byte) + 1);
        ABytes[C3] := rnd_byte;
        if rnd_byte <= 51 then
          Inc(expected_len, 2);
      end;
      FCards.Assign(ABytes);
      Check(Length(FCards.AsString) = expected_len);
    end;
  end;
end;

procedure TestTCards.TestBytesToString;
var
  ABytes: TArray<System.Byte>;
  C1, C2, C3, C4: Integer;
  expected_len: Integer;
  delimiter: String;
  rnd_byte: Byte;
  ReturnValue: String;
begin
  for C1 := 1 to 32 do
  begin
    for C4 := 1 to 4 do
    begin
      SetLength(delimiter, C4);
      for C3 := 1 to C4 do
        delimiter[C3] := Chr(Random(26) + 65);
      SetLength(ABytes, C1);
      for C2 := 1 to 1000 do
      begin
        expected_len := 0;
        for C3 := 0 to C1 - 1 do
        begin
          rnd_byte := Random(High(Byte) + 1);
          ABytes[C3] := rnd_byte;
          if rnd_byte <= 51 then
            Inc(expected_len, 2 + C4);
        end;
        if expected_len > 0 then
          Dec(expected_len, C4);
        ReturnValue := FCards.BytesToString(ABytes, delimiter);
        Check(Length(ReturnValue) = expected_len);
      end;
    end;
  end;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTCard.Suite);
  RegisterTest(TestTCards.Suite);
end.

