unit utHandStrengthCalculator;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit
  being tested.

}

interface

uses
  TestFramework, Poker.Protobufs.Objects.Game, Poker.HandStrengthCalculator;

type
  // Test methods for class THandStrengthCalculator

  TestTHandStrengthCalculator = class(TTestCase)
  strict private
    FHandStrengthCalculator: THandStrengthCalculator;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestGetHandStrength;
  end;

implementation

uses
  System.SysUtils, System.Classes;


procedure TestTHandStrengthCalculator.SetUp;
begin
  FHandStrengthCalculator := THandStrengthCalculator.Create;
end;

procedure TestTHandStrengthCalculator.TearDown;
begin
  FHandStrengthCalculator.Free;
  FHandStrengthCalculator := nil;
end;

procedure TestTHandStrengthCalculator.TestGetHandStrength;
var
  ReturnValue: string;
  AShort: Boolean;
  AGameType: TGameType;
  ATableCards: string;
  APlayerCards: string;
  fstream: TFileStream;
  freader: TStreamReader;
  ch: Char;
  line: String;
  valnum: Integer;
begin
  AGameType := gtHoldem;

  valnum := 0;
  fstream := TFileStream.Create('..\..\..\data\hands.txt', fmOpenRead or fmShareDenyNone);
  try
    freader := TStreamReader.Create(fstream);
    try
      while not freader.EndOfStream do
      begin
        line := freader.ReadLine;
        if line = '' then
          Continue;

        ch := line[1];
        case ch of
          'h': AGameType := gtHoldem;
          'o': AGameType := gtOmaha;
        else
          Continue;
        end;
        Delete(line, 1, 2);

        ATableCards := Copy(line, 1, 10);
        Delete(line, 1, 11);
        APlayerCards := line;
        AShort := FALSE;
        ReturnValue := FHandStrengthCalculator.GetHandStrength(APlayerCards, ATableCards, AGameType, AShort);
        Check(ReturnValue <> '');
        Inc(valnum);
        if valnum mod 10000 = 0 then
          Status(Format('%d hands validated', [valnum]));
      end;
    finally
      freader.Free;
    end;
  finally
    fstream.Free;
  end;

  Status(Format('%d hands validated', [valnum]));
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTHandStrengthCalculator.Suite);
end.

