######################################################################
# Automatically generated by qmake (2.01a) Wed Nov 19 10:26:53 2014
######################################################################

CONFIG += qtestlib debug
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
QT += script network
INCLUDEPATH += ../
LIBS += -lprotobuf

# Input
HEADERS += test.h   ../tableprivate.h   ../tablestatus.h   ../data/pot.h   ../data/tableevent.h   ../data/tablemessage.h   ../data/seatinfo.h ../table/card.h ../table/visible_seat.h ../club.h ../pokermain.h ../game.h ../data/user.h ../table/game_wrap.h
SOURCES += test.cpp ../tableprivate.cpp ../tablestatus.cpp ../data/pot.cpp ../data/tableevent.cpp ../data/tablemessage.cpp ../data/seatinfo.cpp ../data/hand.cpp root.cpp ../table/game_object.cpp ../table/table_ui.cpp ../table/visible_seat.cpp fake_pokermain.cpp ../club.cpp ../cpp/message.pb.cc ../table/card.cpp ../cpp/common.pb.cc ../game.cpp ../data/user.cpp
