// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.HandHistory;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.PlayerHandHistory, Poker.Protobufs.Objects.HandHistoryMove, Poker.Protobufs.Objects.Game;

type
  {$RTTI INHERIT}
  TPB_HandHistory = class(TProtobufBaseObject)
  private
    const
      kIdFieldNumber = 1;
      kSeqFieldNumber = 2;
      kTotalrakeFieldNumber = 3;
      kPlayersFieldNumber = 4;
      kCardsFieldNumber = 5;
      kEndtimeFieldNumber = 6;
      kBalanceChangesFieldNumber = 7;
      kMovesFieldNumber = 8;
      kDealerFieldNumber = 9;
      kGameFieldNumber = 10;
      kCurrentGameFieldNumber = 11;
      kRakeFieldNumber = 12;

    var
      FId: TMongoId;
      FSeq: UInt32;
      FTotalrake: UInt32;
      FPlayers: TList<TPB_PlayerHandHistory>;
      FCards: TList<TBytes>;
      FEndtime: UInt32;
      FBalanceChanges: TList<Integer>;
      FMoves: TList<TPB_HandHistoryMove>;
      FDealer: UInt32;
      FGame: TPB_Game;
      FCurrentGame: TGameType;
      FRake: Integer;
      FHasBits: UINT32;

    procedure set_has_MongoId;
    procedure clear_has_MongoId;
    procedure SetMongoId(const AValue: TMongoId);
    procedure set_has_Seq;
    procedure clear_has_Seq;
    procedure SetSeq(const AValue: UInt32);
    procedure set_has_Totalrake;
    procedure clear_has_Totalrake;
    procedure SetTotalrake(const AValue: UInt32);
    procedure set_has_Players;
    procedure clear_has_Players;
    procedure set_has_Cards;
    procedure clear_has_Cards;
    procedure set_has_Endtime;
    procedure clear_has_Endtime;
    procedure SetEndtime(const AValue: UInt32);
    procedure set_has_BalanceChanges;
    procedure clear_has_BalanceChanges;
    procedure set_has_Moves;
    procedure clear_has_Moves;
    procedure set_has_Dealer;
    procedure clear_has_Dealer;
    procedure SetDealer(const AValue: UInt32);
    procedure set_has_Game;
    procedure clear_has_Game;
    procedure SetGame(const AValue: TPB_Game);
    procedure set_has_CurrentGame;
    procedure clear_has_CurrentGame;
    procedure SetCurrentGame(const AValue: TGameType);
    procedure set_has_Rake;
    procedure clear_has_Rake;
    procedure SetRake(const AValue: Integer);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
    procedure CardsNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);
    procedure BalanceChangesNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
    procedure MovesNotifyEvent(Sender: TObject; const Item: TPB_HandHistoryMove; Action: TCollectionNotification);
  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;
  public
    constructor Create(const AFrom: TPB_HandHistory; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_HandHistory);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes MongoId = 1;
    function has_MongoId: Boolean;
    procedure clear_MongoId;

    // required uint32 Seq = 2;
    function has_Seq: Boolean;
    procedure clear_Seq;

    // required uint32 Totalrake = 3;
    function has_Totalrake: Boolean;
    procedure clear_Totalrake;

    // repeated PlayerHandHistory Players = 4;
    function has_Players: Boolean;
    procedure clear_Players;

    // repeated bytes Cards = 5;
    function has_Cards: Boolean;
    procedure clear_Cards;

    // required uint32 Endtime = 6;
    function has_Endtime: Boolean;
    procedure clear_Endtime;

    // repeated int32 BalanceChanges = 7;
    function has_BalanceChanges: Boolean;
    procedure clear_BalanceChanges;

    // repeated HandHistoryMove Moves = 8;
    function has_Moves: Boolean;
    procedure clear_Moves;

    // required uint32 Dealer = 9;
    function has_Dealer: Boolean;
    procedure clear_Dealer;

    // optional Game Game = 10;
    function has_Game: Boolean;
    procedure clear_Game;

    // optional GameType CurrentGame = 11;
    function has_CurrentGame: Boolean;
    procedure clear_CurrentGame;

    // required int32 Rake = 12;
    function has_Rake: Boolean;
    procedure clear_Rake;
  published
    property MongoId: TMongoId read FId write SetMongoId;
    property Seq: UInt32 read FSeq write SetSeq;
    property Totalrake: UInt32 read FTotalrake write SetTotalrake;
    property Players: TList<TPB_PlayerHandHistory> read FPlayers;
    property Cards: TList<TBytes> read FCards;
    property Endtime: UInt32 read FEndtime write SetEndtime;
    property BalanceChanges: TList<Integer> read FBalanceChanges;
    property Moves: TList<TPB_HandHistoryMove> read FMoves;
    property Dealer: UInt32 read FDealer write SetDealer;
    property Game: TPB_Game read FGame write SetGame;
    property CurrentGame: TGameType read FCurrentGame write SetCurrentGame;
    property Rake: Integer read FRake write SetRake;
  end;

  TPB_HandHistoryList = class(TObjectList<TPB_HandHistory>)
    procedure Assign(const APB_HandHistoryList: TList<TPB_HandHistory>);
  end;

implementation

uses
  pbPublic;


constructor TPB_HandHistory.Create(const AFrom: TPB_HandHistory; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_HandHistory.Destroy;
begin
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  if Assigned(FCards) then
  begin
    FCards.OnNotify := nil;
    FreeAndNil(FCards);
  end;
  if Assigned(FBalanceChanges) then
  begin
    FBalanceChanges.OnNotify := nil;
    FreeAndNil(FBalanceChanges);
  end;
  if Assigned(FMoves) then
  begin
    FMoves.OnNotify := nil;
    FreeAndNil(FMoves);
  end;
  if Assigned(FGame) then FreeAndNil(FGame);
  inherited;
end;

procedure TPB_HandHistory.InitObjects;
begin
  inherited;
  FPlayers := TObjectList<TPB_PlayerHandHistory>.Create;
  FCards := TList<TBytes>.Create;
  FBalanceChanges := TList<Integer>.Create;
  FMoves := TObjectList<TPB_HandHistoryMove>.Create;
end;

procedure TPB_HandHistory.HookNotifiers;
begin
  inherited;
  FPlayers.OnNotify := PlayersNotifyEvent;
  FCards.OnNotify := CardsNotifyEvent;
  FBalanceChanges.OnNotify := BalanceChangesNotifyEvent;
  FMoves.OnNotify := MovesNotifyEvent;
end;

procedure TPB_HandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FId := AProtobufReader.readMongoId;
        set_has_MongoId;
      end;
      kSeqFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeq := AProtobufReader.readUInt32;
        set_has_Seq;
      end;
      kTotalrakeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FTotalrake := AProtobufReader.readUInt32;
        set_has_Totalrake;
      end;
      kPlayersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_PlayerHandHistory.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Players;
      end;
      kCardsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FCards.Add(AProtobufReader.readBytes);
        set_has_Cards;
      end;
      kEndtimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEndtime := AProtobufReader.readUInt32;
        set_has_Endtime;
      end;
      kBalanceChangesFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBalanceChanges.Add(AProtobufReader.readInt32);
        set_has_BalanceChanges;
      end;
      kMovesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FMoves.Add(TPB_HandHistoryMove.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Moves;
      end;
      kDealerFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDealer := AProtobufReader.readUInt32;
        set_has_Dealer;
      end;
      kGameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FGame) then
          FGame := TPB_Game.Create;
        FGame.LoadFromProtobufReader(AProtobufReader, AProtobufReader.readInt32);
        set_has_Game;
      end;
      kCurrentGameFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentGame := TGameType(AProtobufReader.readEnum);
        set_has_CurrentGame;
      end;
      kRakeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FRake := AProtobufReader.readInt32;
        set_has_Rake;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_HandHistory.MergeFrom(const AFrom: TPB_HandHistory);
var
  pbobj3: TPB_PlayerHandHistory;
  pbobj7: TPB_HandHistoryMove;
begin
  if AFrom.has_MongoId then
    SetMongoId(AFrom.MongoId);
  if AFrom.has_Seq then
    SetSeq(AFrom.Seq);
  if AFrom.has_Totalrake then
    SetTotalrake(AFrom.Totalrake);
  for pbobj3 in AFrom.Players do
    FPlayers.Add(TPB_PlayerHandHistory.Create(pbobj3, Lightweight));
  FCards.AddRange(AFrom.Cards);
  if AFrom.has_Endtime then
    SetEndtime(AFrom.Endtime);
  FBalanceChanges.AddRange(AFrom.BalanceChanges);
  for pbobj7 in AFrom.Moves do
    FMoves.Add(TPB_HandHistoryMove.Create(pbobj7, Lightweight));
  if AFrom.has_Dealer then
    SetDealer(AFrom.Dealer);
  if (AFrom.has_Game) then
    FGame.MergeFrom(AFrom.Game);
  if AFrom.has_CurrentGame then
    SetCurrentGame(AFrom.CurrentGame);
  if AFrom.has_Rake then
    SetRake(AFrom.Rake);
end;

function TPB_HandHistory.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (FHasBits and $927) <> $927 then
    Exit(FALSE);
  for pbobj in Players do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in Moves do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  if (has_Game) then
    if not FGame.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_HandHistory.clear_MongoId;
begin
  FId.Clear;
  clear_has_MongoId;
end;

function TPB_HandHistory.has_MongoId: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_HandHistory.set_has_MongoId;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_HandHistory.clear_has_MongoId;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_HandHistory.SetMongoId(const AValue: TMongoId);
begin
  if not Lightweight then
    Assert(not has_MongoId);
  FId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_MongoId;
end;

procedure TPB_HandHistory.clear_Seq;
begin
  FSeq := 0;
  clear_has_Seq;
end;

function TPB_HandHistory.has_Seq: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_HandHistory.set_has_Seq;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_HandHistory.clear_has_Seq;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_HandHistory.SetSeq(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Seq);
  FSeq := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kSeqFieldNumber, AValue);
  set_has_Seq;
end;

procedure TPB_HandHistory.clear_Totalrake;
begin
  FTotalrake := 0;
  clear_has_Totalrake;
end;

function TPB_HandHistory.has_Totalrake: Boolean;
begin
  result := (FHasBits and 4) > 0;
end;

procedure TPB_HandHistory.set_has_Totalrake;
begin
  FHasBits := FHasBits or 4;
end;

procedure TPB_HandHistory.clear_has_Totalrake;
begin
  FHasBits := FHasBits and not 4;
end;

procedure TPB_HandHistory.SetTotalrake(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Totalrake);
  FTotalrake := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kTotalrakeFieldNumber, AValue);
  set_has_Totalrake;
end;

procedure TPB_HandHistory.clear_Players;
var
  on_notify: TCollectionNotifyEvent<TPB_PlayerHandHistory>;
begin
  on_notify := FPlayers.OnNotify;
  FPlayers.OnNotify := nil;
  FPlayers.Clear;
  FPlayers.OnNotify := on_notify;
  clear_has_Players;
end;

function TPB_HandHistory.has_Players: Boolean;
begin
  result := (FHasBits and 8) > 0;
end;

procedure TPB_HandHistory.set_has_Players;
begin
  FHasBits := FHasBits or 8;
end;

procedure TPB_HandHistory.clear_has_Players;
begin
  FHasBits := FHasBits and not 8;
end;

procedure TPB_HandHistory.PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Players;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPlayersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_HandHistory.clear_Cards;
var
  on_notify: TCollectionNotifyEvent<TBytes>;
begin
  on_notify := FCards.OnNotify;
  FCards.OnNotify := nil;
  FCards.Clear;
  FCards.OnNotify := on_notify;
  clear_has_Cards;
end;

function TPB_HandHistory.has_Cards: Boolean;
begin
  result := (FHasBits and 16) > 0;
end;

procedure TPB_HandHistory.set_has_Cards;
begin
  FHasBits := FHasBits or 16;
end;

procedure TPB_HandHistory.clear_has_Cards;
begin
  FHasBits := FHasBits and not 16;
end;

procedure TPB_HandHistory.CardsNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Cards;
  if not Lightweight then
    ProtobufOutput.writeBytes(kCardsFieldNumber, Item);
end;

procedure TPB_HandHistory.clear_Endtime;
begin
  FEndtime := 0;
  clear_has_Endtime;
end;

function TPB_HandHistory.has_Endtime: Boolean;
begin
  result := (FHasBits and 32) > 0;
end;

procedure TPB_HandHistory.set_has_Endtime;
begin
  FHasBits := FHasBits or 32;
end;

procedure TPB_HandHistory.clear_has_Endtime;
begin
  FHasBits := FHasBits and not 32;
end;

procedure TPB_HandHistory.SetEndtime(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Endtime);
  FEndtime := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kEndtimeFieldNumber, AValue);
  set_has_Endtime;
end;

procedure TPB_HandHistory.clear_BalanceChanges;
var
  on_notify: TCollectionNotifyEvent<Integer>;
begin
  on_notify := FBalanceChanges.OnNotify;
  FBalanceChanges.OnNotify := nil;
  FBalanceChanges.Clear;
  FBalanceChanges.OnNotify := on_notify;
  clear_has_BalanceChanges;
end;

function TPB_HandHistory.has_BalanceChanges: Boolean;
begin
  result := (FHasBits and 64) > 0;
end;

procedure TPB_HandHistory.set_has_BalanceChanges;
begin
  FHasBits := FHasBits or 64;
end;

procedure TPB_HandHistory.clear_has_BalanceChanges;
begin
  FHasBits := FHasBits and not 64;
end;

procedure TPB_HandHistory.BalanceChangesNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_BalanceChanges;
  if not Lightweight then
    ProtobufOutput.writeInt32(kBalanceChangesFieldNumber, Item);
end;

procedure TPB_HandHistory.clear_Moves;
var
  on_notify: TCollectionNotifyEvent<TPB_HandHistoryMove>;
begin
  on_notify := FMoves.OnNotify;
  FMoves.OnNotify := nil;
  FMoves.Clear;
  FMoves.OnNotify := on_notify;
  clear_has_Moves;
end;

function TPB_HandHistory.has_Moves: Boolean;
begin
  result := (FHasBits and 128) > 0;
end;

procedure TPB_HandHistory.set_has_Moves;
begin
  FHasBits := FHasBits or 128;
end;

procedure TPB_HandHistory.clear_has_Moves;
begin
  FHasBits := FHasBits and not 128;
end;

procedure TPB_HandHistory.MovesNotifyEvent(Sender: TObject; const Item: TPB_HandHistoryMove; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Moves;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kMovesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_HandHistory.clear_Dealer;
begin
  FDealer := 0;
  clear_has_Dealer;
end;

function TPB_HandHistory.has_Dealer: Boolean;
begin
  result := (FHasBits and 256) > 0;
end;

procedure TPB_HandHistory.set_has_Dealer;
begin
  FHasBits := FHasBits or 256;
end;

procedure TPB_HandHistory.clear_has_Dealer;
begin
  FHasBits := FHasBits and not 256;
end;

procedure TPB_HandHistory.SetDealer(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Dealer);
  FDealer := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kDealerFieldNumber, AValue);
  set_has_Dealer;
end;

procedure TPB_HandHistory.clear_Game;
begin
  FreeAndNil(FGame);
  clear_has_Game;
end;

function TPB_HandHistory.has_Game: Boolean;
begin
  result := (FHasBits and 512) > 0;
end;

procedure TPB_HandHistory.set_has_Game;
begin
  FHasBits := FHasBits or 512;
end;

procedure TPB_HandHistory.clear_has_Game;
begin
  FHasBits := FHasBits and not 512;
end;

procedure TPB_HandHistory.SetGame(const AValue: TPB_Game);
begin
  if not Lightweight then
    Assert(not has_Game);
  FGame := AValue;
  if not Lightweight then
    ProtobufOutput.writeMessage(kGameFieldNumber, AValue.ProtobufOutput);
  set_has_Game;
end;

procedure TPB_HandHistory.clear_CurrentGame;
begin
  FCurrentGame := TGameType(0);
  clear_has_CurrentGame;
end;

function TPB_HandHistory.has_CurrentGame: Boolean;
begin
  result := (FHasBits and 1024) > 0;
end;

procedure TPB_HandHistory.set_has_CurrentGame;
begin
  FHasBits := FHasBits or 1024;
end;

procedure TPB_HandHistory.clear_has_CurrentGame;
begin
  FHasBits := FHasBits and not 1024;
end;

procedure TPB_HandHistory.SetCurrentGame(const AValue: TGameType);
begin
  if not Lightweight then
    Assert(not has_CurrentGame);
  FCurrentGame := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kCurrentGameFieldNumber, Integer(AValue));
  set_has_CurrentGame;
end;

procedure TPB_HandHistory.clear_Rake;
begin
  FRake := 0;
  clear_has_Rake;
end;

function TPB_HandHistory.has_Rake: Boolean;
begin
  result := (FHasBits and 2048) > 0;
end;

procedure TPB_HandHistory.set_has_Rake;
begin
  FHasBits := FHasBits or 2048;
end;

procedure TPB_HandHistory.clear_has_Rake;
begin
  FHasBits := FHasBits and not 2048;
end;

procedure TPB_HandHistory.SetRake(const AValue: Integer);
begin
  if not Lightweight then
    Assert(not has_Rake);
  FRake := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kRakeFieldNumber, AValue);
  set_has_Rake;
end;

procedure TPB_HandHistory.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_MongoId;
  clear_Seq;
  clear_Totalrake;
  clear_Players;
  clear_Cards;
  clear_Endtime;
  clear_BalanceChanges;
  clear_Moves;
  clear_Dealer;
  clear_Game;
  clear_CurrentGame;
  clear_Rake;
end;

procedure TPB_HandHistoryList.Assign(const APB_HandHistoryList: TList<TPB_HandHistory>);
var
  pbobj: TPB_HandHistory;
begin
  Clear;
  for pbobj in APB_HandHistoryList do
    Add(TPB_HandHistory.Create(pbobj, TRUE));
end;

end.
