// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.WinnerData;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TCardRankings = (crRoyalFlush = 0, crStraightFlush, cr4OfKind, crFullHouse, crFlush, crStraight, crThreeOfKind, crTwoPair, crOnePair, crHighCard);

  TPB_WinnerData = class(TProtobufBaseObject)
  private
    const
      kSeatFieldNumber = 3;
      kMsgFieldNumber = 4;

    var
      FSeat: Integer;
      FMsg: String;
      _has_bits_: UINT32;

    procedure set_has_Seat;
    procedure clear_has_Seat;
    procedure SetSeat(const AValue: Integer);
    procedure set_has_Msg;
    procedure clear_has_Msg;
    procedure SetMsg(const AValue: String);
  public
    constructor Create(const AFrom: TPB_WinnerData; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_WinnerData);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required int32 Seat = 3;
    function has_Seat: Boolean;
    procedure clear_Seat;
    property Seat: Integer read FSeat write SetSeat;

    // required string Msg = 4;
    function has_Msg: Boolean;
    procedure clear_Msg;
    property Msg: String read FMsg write SetMsg;

  end;

  TPB_WinnerDataList = class(TObjectList<TPB_WinnerData>)
    procedure Assign(const APB_WinnerDataList: TList<TPB_WinnerData>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_WinnerData.Create(const AFrom: TPB_WinnerData; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_WinnerData.Destroy;
begin
  inherited;
end;

procedure TPB_WinnerData.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kSeatFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readInt32;
        set_has_Seat;
      end;
      kMsgFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FMsg := AProtobufReader.readUtf8String;
        set_has_Msg;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_WinnerData.MergeFrom(const AFrom: TPB_WinnerData);
begin
  if AFrom.has_Seat then
    SetSeat(AFrom.Seat);
  if AFrom.has_Msg then
    SetMsg(AFrom.Msg);
end;

function TPB_WinnerData.IsInitialized: Boolean;
begin
  if (_has_bits_ and $c) <> $c then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_WinnerData.clear_Seat;
begin
  FSeat := 0;
  clear_has_Seat;
end;

function TPB_WinnerData.has_Seat: Boolean;
begin
  result := (_has_bits_ and 4) > 0;
end;

procedure TPB_WinnerData.set_has_Seat;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_WinnerData.clear_has_Seat;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_WinnerData.SetSeat(const AValue: Integer);
begin
  if not Lightweight then
    Assert(not has_Seat);
  FSeat := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kSeatFieldNumber, AValue);
  set_has_Seat;
end;

procedure TPB_WinnerData.clear_Msg;
begin
  FMsg := '';
  clear_has_Msg;
end;

function TPB_WinnerData.has_Msg: Boolean;
begin
  result := (_has_bits_ and 8) > 0;
end;

procedure TPB_WinnerData.set_has_Msg;
begin
  _has_bits_ := _has_bits_ or 8;
end;

procedure TPB_WinnerData.clear_has_Msg;
begin
  _has_bits_ := _has_bits_ and not 8;
end;

procedure TPB_WinnerData.SetMsg(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Msg);
  FMsg := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kMsgFieldNumber, AValue);
  set_has_Msg;
end;

procedure TPB_WinnerData.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Seat;
  clear_Msg;
end;

procedure TPB_WinnerDataList.Assign(const APB_WinnerDataList: TList<TPB_WinnerData>);
var
  pbobj: TPB_WinnerData;
begin
  Clear;
  for pbobj in APB_WinnerDataList do
    Add(TPB_WinnerData.Create(pbobj, TRUE));
end;

end.
