// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.Game;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TGameLimit = (glNoLimit = 0, glPotLimit, glFixedLimit);
  TGameType = (gtHoldem = 0, gtOmaha, gtRotationNLHPLO);
  TGameState = (gsActive = 0, gsClosing, gsClosed, gsEmpty);
  TGameBlinds = (gb1x2 = 0, gb2x4, gb2x5, gb5x5, gb3x6, gb4x8, gb5x10, gb10x25, gb25x25, gb15x30, gb20x40, gb25x50, gb30x60, gb40x80, gb50x100, gbOther);

  TPB_Game = class(TProtobufBaseObject)
  private
    const
      kIdFieldNumber = 1;
      kCreatorMongoIdFieldNumber = 2;
      kGamenameFieldNumber = 3;
      kClubMongoidFieldNumber = 4;
      kGameTypeFieldNumber = 5;
      kGameLimitFieldNumber = 6;
      kBlindsFieldNumber = 7;
      kSeatsFieldNumber = 9;
      kSittingFieldNumber = 10;
      kBuyinMinFieldNumber = 11;
      kBuyinMaxFieldNumber = 12;
      kStateFieldNumber = 13;
      kClosetimeFieldNumber = 14;
      kLasthandidFieldNumber = 15;
      kTournamentFieldNumber = 16;
      kSmallBlindFieldNumber = 17;
      kBigBlindFieldNumber = 18;
      kFinalTableFieldNumber = 19;
      kMaxRakePerHandFieldNumber = 20;

    var
      FId: TMongoId;
      FCreatorMongoId: TMongoId;
      FGamename: String;
      FClubMongoid: TMongoId;
      FGameType: TGameType;
      FGameLimit: TGameLimit;
      FBlinds: TGameBlinds;
      FSeats: Integer;
      FSitting: Integer;
      FBuyinMin: UInt32;
      FBuyinMax: UInt32;
      FState: TGameState;
      FClosetime: UInt32;
      FLasthandid: UInt32;
      FTournament: TMongoId;
      FSmallBlind: UInt32;
      FBigBlind: UInt32;
      FFinalTable: Boolean;
      FMaxRakePerHand: UInt32;
      FHasBits: UINT32;

    procedure set_has_MongoId;
    procedure clear_has_MongoId;
    procedure SetMongoId(const AValue: TMongoId);
    procedure set_has_CreatorMongoId;
    procedure clear_has_CreatorMongoId;
    procedure SetCreatorMongoId(const AValue: TMongoId);
    procedure set_has_Gamename;
    procedure clear_has_Gamename;
    procedure SetGamename(const AValue: String);
    procedure set_has_ClubMongoid;
    procedure clear_has_ClubMongoid;
    procedure SetClubMongoid(const AValue: TMongoId);
    procedure set_has_GameType;
    procedure clear_has_GameType;
    procedure SetGameType(const AValue: TGameType);
    procedure set_has_GameLimit;
    procedure clear_has_GameLimit;
    procedure SetGameLimit(const AValue: TGameLimit);
    procedure set_has_Blinds;
    procedure clear_has_Blinds;
    procedure SetBlinds(const AValue: TGameBlinds);
    procedure set_has_Seats;
    procedure clear_has_Seats;
    procedure SetSeats(const AValue: Integer);
    procedure set_has_Sitting;
    procedure clear_has_Sitting;
    procedure SetSitting(const AValue: Integer);
    procedure set_has_BuyinMin;
    procedure clear_has_BuyinMin;
    procedure SetBuyinMin(const AValue: UInt32);
    procedure set_has_BuyinMax;
    procedure clear_has_BuyinMax;
    procedure SetBuyinMax(const AValue: UInt32);
    procedure set_has_State;
    procedure clear_has_State;
    procedure SetState(const AValue: TGameState);
    procedure set_has_Closetime;
    procedure clear_has_Closetime;
    procedure SetClosetime(const AValue: UInt32);
    procedure set_has_Lasthandid;
    procedure clear_has_Lasthandid;
    procedure SetLasthandid(const AValue: UInt32);
    procedure set_has_Tournament;
    procedure clear_has_Tournament;
    procedure SetTournament(const AValue: TMongoId);
    procedure set_has_SmallBlind;
    procedure clear_has_SmallBlind;
    procedure SetSmallBlind(const AValue: UInt32);
    procedure set_has_BigBlind;
    procedure clear_has_BigBlind;
    procedure SetBigBlind(const AValue: UInt32);
    procedure set_has_FinalTable;
    procedure clear_has_FinalTable;
    procedure SetFinalTable(const AValue: Boolean);
    procedure set_has_MaxRakePerHand;
    procedure clear_has_MaxRakePerHand;
    procedure SetMaxRakePerHand(const AValue: UInt32);
  public
    constructor Create(const AFrom: TPB_Game; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_Game);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // optional bytes MongoId = 1;
    function has_MongoId: Boolean;
    procedure clear_MongoId;
    property MongoId: TMongoId read FId write SetMongoId;

    // optional bytes CreatorMongoId = 2;
    function has_CreatorMongoId: Boolean;
    procedure clear_CreatorMongoId;
    property CreatorMongoId: TMongoId read FCreatorMongoId write SetCreatorMongoId;

    // optional string Gamename = 3;
    function has_Gamename: Boolean;
    procedure clear_Gamename;
    property Gamename: String read FGamename write SetGamename;

    // optional bytes ClubMongoid = 4;
    function has_ClubMongoid: Boolean;
    procedure clear_ClubMongoid;
    property ClubMongoid: TMongoId read FClubMongoid write SetClubMongoid;

    // optional GameType GameType = 5;
    function has_GameType: Boolean;
    procedure clear_GameType;
    property GameType: TGameType read FGameType write SetGameType;

    // optional GameLimit GameLimit = 6;
    function has_GameLimit: Boolean;
    procedure clear_GameLimit;
    property GameLimit: TGameLimit read FGameLimit write SetGameLimit;

    // optional GameBlinds Blinds = 7;
    function has_Blinds: Boolean;
    procedure clear_Blinds;
    property Blinds: TGameBlinds read FBlinds write SetBlinds;

    // optional int32 Seats = 9;
    function has_Seats: Boolean;
    procedure clear_Seats;
    property Seats: Integer read FSeats write SetSeats;

    // optional int32 Sitting = 10;
    function has_Sitting: Boolean;
    procedure clear_Sitting;
    property Sitting: Integer read FSitting write SetSitting;

    // optional uint32 BuyinMin = 11;
    function has_BuyinMin: Boolean;
    procedure clear_BuyinMin;
    property BuyinMin: UInt32 read FBuyinMin write SetBuyinMin;

    // optional uint32 BuyinMax = 12;
    function has_BuyinMax: Boolean;
    procedure clear_BuyinMax;
    property BuyinMax: UInt32 read FBuyinMax write SetBuyinMax;

    // optional GameState State = 13;
    function has_State: Boolean;
    procedure clear_State;
    property State: TGameState read FState write SetState;

    // optional uint32 Closetime = 14;
    function has_Closetime: Boolean;
    procedure clear_Closetime;
    property Closetime: UInt32 read FClosetime write SetClosetime;

    // optional uint32 Lasthandid = 15;
    function has_Lasthandid: Boolean;
    procedure clear_Lasthandid;
    property Lasthandid: UInt32 read FLasthandid write SetLasthandid;

    // optional bytes Tournament = 16;
    function has_Tournament: Boolean;
    procedure clear_Tournament;
    property Tournament: TMongoId read FTournament write SetTournament;

    // optional uint32 SmallBlind = 17;
    function has_SmallBlind: Boolean;
    procedure clear_SmallBlind;
    property SmallBlind: UInt32 read FSmallBlind write SetSmallBlind;

    // optional uint32 BigBlind = 18;
    function has_BigBlind: Boolean;
    procedure clear_BigBlind;
    property BigBlind: UInt32 read FBigBlind write SetBigBlind;

    // optional bool FinalTable = 19;
    function has_FinalTable: Boolean;
    procedure clear_FinalTable;
    property FinalTable: Boolean read FFinalTable write SetFinalTable;

    // optional uint32 MaxRakePerHand = 20;
    function has_MaxRakePerHand: Boolean;
    procedure clear_MaxRakePerHand;
    property MaxRakePerHand: UInt32 read FMaxRakePerHand write SetMaxRakePerHand;
  end;

  TPB_GameList = class(TObjectList<TPB_Game>)
    procedure Assign(const APB_GameList: TList<TPB_Game>);
  end;

implementation

uses
  pbPublic;


constructor TPB_Game.Create(const AFrom: TPB_Game; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_Game.Destroy;
begin
  inherited;
end;

procedure TPB_Game.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FId := AProtobufReader.readMongoId;
        set_has_MongoId;
      end;
      kCreatorMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FCreatorMongoId := AProtobufReader.readMongoId;
        set_has_CreatorMongoId;
      end;
      kGamenameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGamename := AProtobufReader.readUtf8String;
        set_has_Gamename;
      end;
      kClubMongoidFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubMongoid := AProtobufReader.readMongoId;
        set_has_ClubMongoid;
      end;
      kGameTypeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FGameType := TGameType(AProtobufReader.readEnum);
        set_has_GameType;
      end;
      kGameLimitFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FGameLimit := TGameLimit(AProtobufReader.readEnum);
        set_has_GameLimit;
      end;
      kBlindsFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBlinds := TGameBlinds(AProtobufReader.readEnum);
        set_has_Blinds;
      end;
      kSeatsFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeats := AProtobufReader.readInt32;
        set_has_Seats;
      end;
      kSittingFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSitting := AProtobufReader.readInt32;
        set_has_Sitting;
      end;
      kBuyinMinFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBuyinMin := AProtobufReader.readUInt32;
        set_has_BuyinMin;
      end;
      kBuyinMaxFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBuyinMax := AProtobufReader.readUInt32;
        set_has_BuyinMax;
      end;
      kStateFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FState := TGameState(AProtobufReader.readEnum);
        set_has_State;
      end;
      kClosetimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FClosetime := AProtobufReader.readUInt32;
        set_has_Closetime;
      end;
      kLasthandidFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FLasthandid := AProtobufReader.readUInt32;
        set_has_Lasthandid;
      end;
      kTournamentFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FTournament := AProtobufReader.readMongoId;
        set_has_Tournament;
      end;
      kSmallBlindFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSmallBlind := AProtobufReader.readUInt32;
        set_has_SmallBlind;
      end;
      kBigBlindFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBigBlind := AProtobufReader.readUInt32;
        set_has_BigBlind;
      end;
      kFinalTableFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FFinalTable := AProtobufReader.readBoolean;
        set_has_FinalTable;
      end;
      kMaxRakePerHandFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMaxRakePerHand := AProtobufReader.readUInt32;
        set_has_MaxRakePerHand;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_Game.MergeFrom(const AFrom: TPB_Game);
begin
  if AFrom.has_MongoId then
    SetMongoId(AFrom.MongoId);
  if AFrom.has_CreatorMongoId then
    SetCreatorMongoId(AFrom.CreatorMongoId);
  if AFrom.has_Gamename then
    SetGamename(AFrom.Gamename);
  if AFrom.has_ClubMongoid then
    SetClubMongoid(AFrom.ClubMongoid);
  if AFrom.has_GameType then
    SetGameType(AFrom.GameType);
  if AFrom.has_GameLimit then
    SetGameLimit(AFrom.GameLimit);
  if AFrom.has_Blinds then
    SetBlinds(AFrom.Blinds);
  if AFrom.has_Seats then
    SetSeats(AFrom.Seats);
  if AFrom.has_Sitting then
    SetSitting(AFrom.Sitting);
  if AFrom.has_BuyinMin then
    SetBuyinMin(AFrom.BuyinMin);
  if AFrom.has_BuyinMax then
    SetBuyinMax(AFrom.BuyinMax);
  if AFrom.has_State then
    SetState(AFrom.State);
  if AFrom.has_Closetime then
    SetClosetime(AFrom.Closetime);
  if AFrom.has_Lasthandid then
    SetLasthandid(AFrom.Lasthandid);
  if AFrom.has_Tournament then
    SetTournament(AFrom.Tournament);
  if AFrom.has_SmallBlind then
    SetSmallBlind(AFrom.SmallBlind);
  if AFrom.has_BigBlind then
    SetBigBlind(AFrom.BigBlind);
  if AFrom.has_FinalTable then
    SetFinalTable(AFrom.FinalTable);
  if AFrom.has_MaxRakePerHand then
    SetMaxRakePerHand(AFrom.MaxRakePerHand);
end;

function TPB_Game.IsInitialized: Boolean;
begin
  if (FHasBits and $0) <> $0 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_Game.clear_MongoId;
begin
  FId.Clear;
  clear_has_MongoId;
end;

function TPB_Game.has_MongoId: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_Game.set_has_MongoId;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_Game.clear_has_MongoId;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_Game.SetMongoId(const AValue: TMongoId);
begin
  if not Lightweight then
    Assert(not has_MongoId);
  FId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_MongoId;
end;

procedure TPB_Game.clear_CreatorMongoId;
begin
  FCreatorMongoId.Clear;
  clear_has_CreatorMongoId;
end;

function TPB_Game.has_CreatorMongoId: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_Game.set_has_CreatorMongoId;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_Game.clear_has_CreatorMongoId;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_Game.SetCreatorMongoId(const AValue: TMongoId);
begin
  if not Lightweight then
    Assert(not has_CreatorMongoId);
  FCreatorMongoId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kCreatorMongoIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_CreatorMongoId;
end;

procedure TPB_Game.clear_Gamename;
begin
  FGamename := '';
  clear_has_Gamename;
end;

function TPB_Game.has_Gamename: Boolean;
begin
  result := (FHasBits and 4) > 0;
end;

procedure TPB_Game.set_has_Gamename;
begin
  FHasBits := FHasBits or 4;
end;

procedure TPB_Game.clear_has_Gamename;
begin
  FHasBits := FHasBits and not 4;
end;

procedure TPB_Game.SetGamename(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Gamename);
  FGamename := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kGamenameFieldNumber, AValue);
  set_has_Gamename;
end;

procedure TPB_Game.clear_ClubMongoid;
begin
  FClubMongoid.Clear;
  clear_has_ClubMongoid;
end;

function TPB_Game.has_ClubMongoid: Boolean;
begin
  result := (FHasBits and 8) > 0;
end;

procedure TPB_Game.set_has_ClubMongoid;
begin
  FHasBits := FHasBits or 8;
end;

procedure TPB_Game.clear_has_ClubMongoid;
begin
  FHasBits := FHasBits and not 8;
end;

procedure TPB_Game.SetClubMongoid(const AValue: TMongoId);
begin
  if not Lightweight then
    Assert(not has_ClubMongoid);
  FClubMongoid := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kClubMongoidFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_ClubMongoid;
end;

procedure TPB_Game.clear_GameType;
begin
  FGameType := TGameType(0);
  clear_has_GameType;
end;

function TPB_Game.has_GameType: Boolean;
begin
  result := (FHasBits and 16) > 0;
end;

procedure TPB_Game.set_has_GameType;
begin
  FHasBits := FHasBits or 16;
end;

procedure TPB_Game.clear_has_GameType;
begin
  FHasBits := FHasBits and not 16;
end;

procedure TPB_Game.SetGameType(const AValue: TGameType);
begin
  if not Lightweight then
    Assert(not has_GameType);
  FGameType := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kGameTypeFieldNumber, Integer(AValue));
  set_has_GameType;
end;

procedure TPB_Game.clear_GameLimit;
begin
  FGameLimit := TGameLimit(0);
  clear_has_GameLimit;
end;

function TPB_Game.has_GameLimit: Boolean;
begin
  result := (FHasBits and 32) > 0;
end;

procedure TPB_Game.set_has_GameLimit;
begin
  FHasBits := FHasBits or 32;
end;

procedure TPB_Game.clear_has_GameLimit;
begin
  FHasBits := FHasBits and not 32;
end;

procedure TPB_Game.SetGameLimit(const AValue: TGameLimit);
begin
  if not Lightweight then
    Assert(not has_GameLimit);
  FGameLimit := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kGameLimitFieldNumber, Integer(AValue));
  set_has_GameLimit;
end;

procedure TPB_Game.clear_Blinds;
begin
  FBlinds := TGameBlinds(0);
  clear_has_Blinds;
end;

function TPB_Game.has_Blinds: Boolean;
begin
  result := (FHasBits and 64) > 0;
end;

procedure TPB_Game.set_has_Blinds;
begin
  FHasBits := FHasBits or 64;
end;

procedure TPB_Game.clear_has_Blinds;
begin
  FHasBits := FHasBits and not 64;
end;

procedure TPB_Game.SetBlinds(const AValue: TGameBlinds);
begin
  if not Lightweight then
    Assert(not has_Blinds);
  FBlinds := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kBlindsFieldNumber, Integer(AValue));
  set_has_Blinds;
end;

procedure TPB_Game.clear_Seats;
begin
  FSeats := 0;
  clear_has_Seats;
end;

function TPB_Game.has_Seats: Boolean;
begin
  result := (FHasBits and 256) > 0;
end;

procedure TPB_Game.set_has_Seats;
begin
  FHasBits := FHasBits or 256;
end;

procedure TPB_Game.clear_has_Seats;
begin
  FHasBits := FHasBits and not 256;
end;

procedure TPB_Game.SetSeats(const AValue: Integer);
begin
  if not Lightweight then
    Assert(not has_Seats);
  FSeats := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kSeatsFieldNumber, AValue);
  set_has_Seats;
end;

procedure TPB_Game.clear_Sitting;
begin
  FSitting := 0;
  clear_has_Sitting;
end;

function TPB_Game.has_Sitting: Boolean;
begin
  result := (FHasBits and 512) > 0;
end;

procedure TPB_Game.set_has_Sitting;
begin
  FHasBits := FHasBits or 512;
end;

procedure TPB_Game.clear_has_Sitting;
begin
  FHasBits := FHasBits and not 512;
end;

procedure TPB_Game.SetSitting(const AValue: Integer);
begin
  if not Lightweight then
    Assert(not has_Sitting);
  FSitting := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kSittingFieldNumber, AValue);
  set_has_Sitting;
end;

procedure TPB_Game.clear_BuyinMin;
begin
  FBuyinMin := 0;
  clear_has_BuyinMin;
end;

function TPB_Game.has_BuyinMin: Boolean;
begin
  result := (FHasBits and 1024) > 0;
end;

procedure TPB_Game.set_has_BuyinMin;
begin
  FHasBits := FHasBits or 1024;
end;

procedure TPB_Game.clear_has_BuyinMin;
begin
  FHasBits := FHasBits and not 1024;
end;

procedure TPB_Game.SetBuyinMin(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_BuyinMin);
  FBuyinMin := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kBuyinMinFieldNumber, AValue);
  set_has_BuyinMin;
end;

procedure TPB_Game.clear_BuyinMax;
begin
  FBuyinMax := 0;
  clear_has_BuyinMax;
end;

function TPB_Game.has_BuyinMax: Boolean;
begin
  result := (FHasBits and 2048) > 0;
end;

procedure TPB_Game.set_has_BuyinMax;
begin
  FHasBits := FHasBits or 2048;
end;

procedure TPB_Game.clear_has_BuyinMax;
begin
  FHasBits := FHasBits and not 2048;
end;

procedure TPB_Game.SetBuyinMax(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_BuyinMax);
  FBuyinMax := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kBuyinMaxFieldNumber, AValue);
  set_has_BuyinMax;
end;

procedure TPB_Game.clear_State;
begin
  FState := TGameState(0);
  clear_has_State;
end;

function TPB_Game.has_State: Boolean;
begin
  result := (FHasBits and 4096) > 0;
end;

procedure TPB_Game.set_has_State;
begin
  FHasBits := FHasBits or 4096;
end;

procedure TPB_Game.clear_has_State;
begin
  FHasBits := FHasBits and not 4096;
end;

procedure TPB_Game.SetState(const AValue: TGameState);
begin
  if not Lightweight then
    Assert(not has_State);
  FState := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kStateFieldNumber, Integer(AValue));
  set_has_State;
end;

procedure TPB_Game.clear_Closetime;
begin
  FClosetime := 0;
  clear_has_Closetime;
end;

function TPB_Game.has_Closetime: Boolean;
begin
  result := (FHasBits and 8192) > 0;
end;

procedure TPB_Game.set_has_Closetime;
begin
  FHasBits := FHasBits or 8192;
end;

procedure TPB_Game.clear_has_Closetime;
begin
  FHasBits := FHasBits and not 8192;
end;

procedure TPB_Game.SetClosetime(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Closetime);
  FClosetime := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kClosetimeFieldNumber, AValue);
  set_has_Closetime;
end;

procedure TPB_Game.clear_Lasthandid;
begin
  FLasthandid := 0;
  clear_has_Lasthandid;
end;

function TPB_Game.has_Lasthandid: Boolean;
begin
  result := (FHasBits and 16384) > 0;
end;

procedure TPB_Game.set_has_Lasthandid;
begin
  FHasBits := FHasBits or 16384;
end;

procedure TPB_Game.clear_has_Lasthandid;
begin
  FHasBits := FHasBits and not 16384;
end;

procedure TPB_Game.SetLasthandid(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_Lasthandid);
  FLasthandid := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kLasthandidFieldNumber, AValue);
  set_has_Lasthandid;
end;

procedure TPB_Game.clear_Tournament;
begin
  FTournament.Clear;
  clear_has_Tournament;
end;

function TPB_Game.has_Tournament: Boolean;
begin
  result := (FHasBits and 32768) > 0;
end;

procedure TPB_Game.set_has_Tournament;
begin
  FHasBits := FHasBits or 32768;
end;

procedure TPB_Game.clear_has_Tournament;
begin
  FHasBits := FHasBits and not 32768;
end;

procedure TPB_Game.SetTournament(const AValue: TMongoId);
begin
  if not Lightweight then
    Assert(not has_Tournament);
  FTournament := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kTournamentFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_Tournament;
end;

procedure TPB_Game.clear_SmallBlind;
begin
  FSmallBlind := 0;
  clear_has_SmallBlind;
end;

function TPB_Game.has_SmallBlind: Boolean;
begin
  result := (FHasBits and 65536) > 0;
end;

procedure TPB_Game.set_has_SmallBlind;
begin
  FHasBits := FHasBits or 65536;
end;

procedure TPB_Game.clear_has_SmallBlind;
begin
  FHasBits := FHasBits and not 65536;
end;

procedure TPB_Game.SetSmallBlind(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_SmallBlind);
  FSmallBlind := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kSmallBlindFieldNumber, AValue);
  set_has_SmallBlind;
end;

procedure TPB_Game.clear_BigBlind;
begin
  FBigBlind := 0;
  clear_has_BigBlind;
end;

function TPB_Game.has_BigBlind: Boolean;
begin
  result := (FHasBits and 131072) > 0;
end;

procedure TPB_Game.set_has_BigBlind;
begin
  FHasBits := FHasBits or 131072;
end;

procedure TPB_Game.clear_has_BigBlind;
begin
  FHasBits := FHasBits and not 131072;
end;

procedure TPB_Game.SetBigBlind(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_BigBlind);
  FBigBlind := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kBigBlindFieldNumber, AValue);
  set_has_BigBlind;
end;

procedure TPB_Game.clear_FinalTable;
begin
  FFinalTable := false;
  clear_has_FinalTable;
end;

function TPB_Game.has_FinalTable: Boolean;
begin
  result := (FHasBits and 262144) > 0;
end;

procedure TPB_Game.set_has_FinalTable;
begin
  FHasBits := FHasBits or 262144;
end;

procedure TPB_Game.clear_has_FinalTable;
begin
  FHasBits := FHasBits and not 262144;
end;

procedure TPB_Game.SetFinalTable(const AValue: Boolean);
begin
  if not Lightweight then
    Assert(not has_FinalTable);
  FFinalTable := AValue;
  if not Lightweight then
    ProtobufOutput.writeBoolean(kFinalTableFieldNumber, AValue);
  set_has_FinalTable;
end;

procedure TPB_Game.clear_MaxRakePerHand;
begin
  FMaxRakePerHand := 0;
  clear_has_MaxRakePerHand;
end;

function TPB_Game.has_MaxRakePerHand: Boolean;
begin
  result := (FHasBits and 524288) > 0;
end;

procedure TPB_Game.set_has_MaxRakePerHand;
begin
  FHasBits := FHasBits or 524288;
end;

procedure TPB_Game.clear_has_MaxRakePerHand;
begin
  FHasBits := FHasBits and not 524288;
end;

procedure TPB_Game.SetMaxRakePerHand(const AValue: UInt32);
begin
  if not Lightweight then
    Assert(not has_MaxRakePerHand);
  FMaxRakePerHand := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kMaxRakePerHandFieldNumber, AValue);
  set_has_MaxRakePerHand;
end;

procedure TPB_Game.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_MongoId;
  clear_CreatorMongoId;
  clear_Gamename;
  clear_ClubMongoid;
  clear_GameType;
  clear_GameLimit;
  clear_Blinds;
  clear_Seats;
  clear_Sitting;
  clear_BuyinMin;
  clear_BuyinMax;
  clear_State;
  clear_Closetime;
  clear_Lasthandid;
  clear_Tournament;
  clear_SmallBlind;
  clear_BigBlind;
  clear_FinalTable;
  clear_MaxRakePerHand;
end;

procedure TPB_GameList.Assign(const APB_GameList: TList<TPB_Game>);
var
  pbobj: TPB_Game;
begin
  Clear;
  for pbobj in APB_GameList do
    Add(TPB_Game.Create(pbobj, TRUE));
end;

end.
