// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.SoftException;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TPB_SoftException = class(TProtobufBaseObject)
  private
    const
      kExceptionFieldNumber = 1;
      kDataFieldNumber = 2;

    var
      FException: String;
      FData: String;
      FHasBits: UINT32;

    procedure set_has_Exception;
    procedure clear_has_Exception;
    procedure SetException(const AValue: String);
    procedure set_has_Data;
    procedure clear_has_Data;
    procedure SetData(const AValue: String);
  public
    constructor Create(const AFrom: TPB_SoftException; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_SoftException);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required string Exception = 1;
    function has_Exception: Boolean;
    procedure clear_Exception;
    property Exception: String read FException write SetException;

    // optional string Data = 2;
    function has_Data: Boolean;
    procedure clear_Data;
    property Data: String read FData write SetData;
  end;

  TPB_SoftExceptionList = class(TObjectList<TPB_SoftException>)
    procedure Assign(const APB_SoftExceptionList: TList<TPB_SoftException>);
  end;

implementation

uses
  pbPublic;


constructor TPB_SoftException.Create(const AFrom: TPB_SoftException; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_SoftException.Destroy;
begin
  inherited;
end;

procedure TPB_SoftException.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kExceptionFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FException := AProtobufReader.readUtf8String;
        set_has_Exception;
      end;
      kDataFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FData := AProtobufReader.readUtf8String;
        set_has_Data;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_SoftException.MergeFrom(const AFrom: TPB_SoftException);
begin
  if AFrom.has_Exception then
    SetException(AFrom.Exception);
  if AFrom.has_Data then
    SetData(AFrom.Data);
end;

function TPB_SoftException.IsInitialized: Boolean;
begin
  if (FHasBits and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_SoftException.clear_Exception;
begin
  FException := '';
  clear_has_Exception;
end;

function TPB_SoftException.has_Exception: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_SoftException.set_has_Exception;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_SoftException.clear_has_Exception;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_SoftException.SetException(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Exception);
  FException := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kExceptionFieldNumber, AValue);
  set_has_Exception;
end;

procedure TPB_SoftException.clear_Data;
begin
  FData := '';
  clear_has_Data;
end;

function TPB_SoftException.has_Data: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_SoftException.set_has_Data;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_SoftException.clear_has_Data;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_SoftException.SetData(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Data);
  FData := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kDataFieldNumber, AValue);
  set_has_Data;
end;

procedure TPB_SoftException.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_Exception;
  clear_Data;
end;

procedure TPB_SoftExceptionList.Assign(const APB_SoftExceptionList: TList<TPB_SoftException>);
var
  pbobj: TPB_SoftException;
begin
  Clear;
  for pbobj in APB_SoftExceptionList do
    Add(TPB_SoftException.Create(pbobj, TRUE));
end;

end.
