// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TableMessage;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  {$RTTI INHERIT}
  TTableMessageType = (tmtClosing = 0, tmtTournamentBreak, tmtTournamentStart);

  TPB_TableMessage = class(TProtobufBaseObject)
  private
    const
      kMessageFieldNumber = 1;
      kEndTimeFieldNumber = 2;

    var
      FMessage: TTableMessageType;
      FEndTime: UInt64;
      FHasBits: UINT32;

    procedure set_has_Message;
    procedure clear_has_Message;
    procedure SetMessage(const AValue: TTableMessageType);
    procedure set_has_EndTime;
    procedure clear_has_EndTime;
    procedure SetEndTime(const AValue: UInt64);
  public
    constructor Create(const AFrom: TPB_TableMessage; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TableMessage);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required TableMessageType Message = 1;
    function has_Message: Boolean;
    procedure clear_Message;

    // optional uint64 EndTime = 2;
    function has_EndTime: Boolean;
    procedure clear_EndTime;
  published
    property Message: TTableMessageType read FMessage write SetMessage;
    property EndTime: UInt64 read FEndTime write SetEndTime;
  end;

  TPB_TableMessageList = class(TObjectList<TPB_TableMessage>)
    procedure Assign(const APB_TableMessageList: TList<TPB_TableMessage>);
  end;

implementation

uses
  pbPublic;


constructor TPB_TableMessage.Create(const AFrom: TPB_TableMessage; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TableMessage.Destroy;
begin
  inherited;
end;

procedure TPB_TableMessage.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kMessageFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMessage := TTableMessageType(AProtobufReader.readEnum);
        set_has_Message;
      end;
      kEndTimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEndTime := AProtobufReader.readInt64;
        set_has_EndTime;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TableMessage.MergeFrom(const AFrom: TPB_TableMessage);
begin
  if AFrom.has_Message then
    SetMessage(AFrom.Message);
  if AFrom.has_EndTime then
    SetEndTime(AFrom.EndTime);
end;

function TPB_TableMessage.IsInitialized: Boolean;
begin
  if (FHasBits and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TableMessage.clear_Message;
begin
  FMessage := TTableMessageType(0);
  clear_has_Message;
end;

function TPB_TableMessage.has_Message: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_TableMessage.set_has_Message;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_TableMessage.clear_has_Message;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_TableMessage.SetMessage(const AValue: TTableMessageType);
begin
  if not Lightweight then
    Assert(not has_Message);
  FMessage := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kMessageFieldNumber, Integer(AValue));
  set_has_Message;
end;

procedure TPB_TableMessage.clear_EndTime;
begin
  FEndTime := 0;
  clear_has_EndTime;
end;

function TPB_TableMessage.has_EndTime: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_TableMessage.set_has_EndTime;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_TableMessage.clear_has_EndTime;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_TableMessage.SetEndTime(const AValue: UInt64);
begin
  if not Lightweight then
    Assert(not has_EndTime);
  FEndTime := AValue;
  if not Lightweight then
    ProtobufOutput.WriteInt64(kEndTimeFieldNumber, AValue);
  set_has_EndTime;
end;

procedure TPB_TableMessage.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_Message;
  clear_EndTime;
end;

procedure TPB_TableMessageList.Assign(const APB_TableMessageList: TList<TPB_TableMessage>);
var
  pbobj: TPB_TableMessage;
begin
  Clear;
  for pbobj in APB_TableMessageList do
    Add(TPB_TableMessage.Create(pbobj, TRUE));
end;

end.
