// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TournamentPlayerFinished;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TPB_TournamentPlayerFinished = class(TProtobufBaseObject)
  private
    const
      kTournamentIdFieldNumber = 1;
      kPlayerIdFieldNumber = 2;
      kPlaceFieldNumber = 3;

    var
      FTournamentId: TMongoId;
      FPlayerId: TMongoId;
      FPlace: Integer;
      _has_bits_: UINT32;

    procedure set_has_TournamentId;
    procedure clear_has_TournamentId;
    procedure SetTournamentId(const AValue: TMongoId);
    procedure set_has_PlayerId;
    procedure clear_has_PlayerId;
    procedure SetPlayerId(const AValue: TMongoId);
    procedure set_has_Place;
    procedure clear_has_Place;
    procedure SetPlace(const AValue: Integer);

  public
    constructor Create(const AFrom: TPB_TournamentPlayerFinished; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TournamentPlayerFinished);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes TournamentId = 1;
    function has_TournamentId: Boolean;
    procedure clear_TournamentId;
    property TournamentId: TMongoId read FTournamentId write SetTournamentId;

    // required bytes PlayerId = 2;
    function has_PlayerId: Boolean;
    procedure clear_PlayerId;
    property PlayerId: TMongoId read FPlayerId write SetPlayerId;

    // required int32 Place = 3;
    function has_Place: Boolean;
    procedure clear_Place;
    property Place: Integer read FPlace write SetPlace;

  end;

  TPB_TournamentPlayerFinishedList = class(TObjectList<TPB_TournamentPlayerFinished>)
    procedure Assign(const APB_TournamentPlayerFinishedList: TList<TPB_TournamentPlayerFinished>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TournamentPlayerFinished.Create(const AFrom: TPB_TournamentPlayerFinished; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TournamentPlayerFinished.Destroy;
begin
  inherited;
end;

procedure TPB_TournamentPlayerFinished.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kTournamentIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FTournamentId := AProtobufReader.readMongoId;
        set_has_TournamentId;
      end;
      kPlayerIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerId := AProtobufReader.readMongoId;
        set_has_PlayerId;
      end;
      kPlaceFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FPlace := AProtobufReader.readInt32;
        set_has_Place;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TournamentPlayerFinished.MergeFrom(const AFrom: TPB_TournamentPlayerFinished);
begin
  if AFrom.has_TournamentId then
    SetTournamentId(AFrom.TournamentId);
  if AFrom.has_PlayerId then
    SetPlayerId(AFrom.PlayerId);
  if AFrom.has_Place then
    SetPlace(AFrom.Place);
end;

function TPB_TournamentPlayerFinished.IsInitialized: Boolean;
begin
  if (_has_bits_ and $7) <> $7 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TournamentPlayerFinished.clear_TournamentId;
begin
  FTournamentId.Clear;
  clear_has_TournamentId;
end;

function TPB_TournamentPlayerFinished.has_TournamentId: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TournamentPlayerFinished.set_has_TournamentId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TournamentPlayerFinished.clear_has_TournamentId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_TournamentPlayerFinished.SetTournamentId(const AValue: TMongoId);
begin
  if not Lightweight then    Assert(not has_TournamentId);
  FTournamentId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kTournamentIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_TournamentId;
end;

procedure TPB_TournamentPlayerFinished.clear_PlayerId;
begin
  FPlayerId.Clear;
  clear_has_PlayerId;
end;

function TPB_TournamentPlayerFinished.has_PlayerId: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_TournamentPlayerFinished.set_has_PlayerId;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_TournamentPlayerFinished.clear_has_PlayerId;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_TournamentPlayerFinished.SetPlayerId(const AValue: TMongoId);
begin
  if not Lightweight then    Assert(not has_PlayerId);
  FPlayerId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPlayerIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_PlayerId;
end;

procedure TPB_TournamentPlayerFinished.clear_Place;
begin
  FPlace := 0;
  clear_has_Place;
end;

function TPB_TournamentPlayerFinished.has_Place: Boolean;
begin
  result := (_has_bits_ and 4) > 0;
end;

procedure TPB_TournamentPlayerFinished.set_has_Place;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_TournamentPlayerFinished.clear_has_Place;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_TournamentPlayerFinished.SetPlace(const AValue: Integer);
begin
  if not Lightweight then    Assert(not has_Place);
  FPlace := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kPlaceFieldNumber, AValue);
  set_has_Place;
end;

procedure TPB_TournamentPlayerFinished.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_TournamentId;
  clear_PlayerId;
  clear_Place;
end;

procedure TPB_TournamentPlayerFinishedList.Assign(const APB_TournamentPlayerFinishedList: TList<TPB_TournamentPlayerFinished>);
var
  pbobj: TPB_TournamentPlayerFinished;
begin
  Clear;
  for pbobj in APB_TournamentPlayerFinishedList do
    Add(TPB_TournamentPlayerFinished.Create(pbobj, TRUE));
end;

end.
