// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TableMessage;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TTableMessageType = (tmtClosing = 0,tmtTournamentBreak = 1,tmtTournamentStart = 2);

  TPB_TableMessage = class(TProtobufBaseObject)
  private
    const
      kMessageFieldNumber = 1;
      kDurationFieldNumber = 2;

    var
      FMessage: TTableMessageType;
      FDuration: UInt32;
      _has_bits_: UINT32;

    procedure set_has_Message;
    procedure clear_has_Message;
    procedure SetMessage(const AValue: TTableMessageType);
    procedure set_has_Duration;
    procedure clear_has_Duration;
    procedure SetDuration(const AValue: UInt32);

  public
    constructor Create(const AFrom: TPB_TableMessage; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TableMessage);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required TableMessageType Message = 1;
    function has_Message: Boolean;
    procedure clear_Message;
    property Message: TTableMessageType read FMessage write SetMessage;

    // optional uint32 Duration = 2;
    function has_Duration: Boolean;
    procedure clear_Duration;
    property Duration: UInt32 read FDuration write SetDuration;

  end;

  TPB_TableMessageList = class(TObjectList<TPB_TableMessage>)
    procedure Assign(const APB_TableMessageList: TList<TPB_TableMessage>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TableMessage.Create(const AFrom: TPB_TableMessage; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TableMessage.Destroy;
begin
  inherited;
end;

procedure TPB_TableMessage.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kMessageFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMessage := TTableMessageType(AProtobufReader.readEnum);
        set_has_Message;
      end;
      kDurationFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDuration := AProtobufReader.readUInt32;
        set_has_Duration;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TableMessage.MergeFrom(const AFrom: TPB_TableMessage);
begin
  if AFrom.has_Message then
    SetMessage(AFrom.Message);
  if AFrom.has_Duration then
    SetDuration(AFrom.Duration);
end;

function TPB_TableMessage.IsInitialized: Boolean;
begin
  if (_has_bits_ and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TableMessage.clear_Message;
begin
  FMessage := TTableMessageType(0);
  clear_has_Message;
end;

function TPB_TableMessage.has_Message: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TableMessage.set_has_Message;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TableMessage.clear_has_Message;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_TableMessage.SetMessage(const AValue: TTableMessageType);
begin
  if not Lightweight then    Assert(not has_Message);
  FMessage := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kMessageFieldNumber, Integer(AValue));
  set_has_Message;
end;

procedure TPB_TableMessage.clear_Duration;
begin
  FDuration := 0;
  clear_has_Duration;
end;

function TPB_TableMessage.has_Duration: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_TableMessage.set_has_Duration;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_TableMessage.clear_has_Duration;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_TableMessage.SetDuration(const AValue: UInt32);
begin
  if not Lightweight then    Assert(not has_Duration);
  FDuration := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kDurationFieldNumber, AValue);
  set_has_Duration;
end;

procedure TPB_TableMessage.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Message;
  clear_Duration;
end;

procedure TPB_TableMessageList.Assign(const APB_TableMessageList: TList<TPB_TableMessage>);
var
  pbobj: TPB_TableMessage;
begin
  Clear;
  for pbobj in APB_TableMessageList do
    Add(TPB_TableMessage.Create(pbobj, TRUE));
end;

end.
