// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.UpdateGameObjects;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.Game;

type
  TPB_UpdateGameObjects = class(TProtobufBaseObject)
  private
    const
      kGamesFieldNumber = 1;

    var
      FGames: TList<TPB_Game>;
      _has_bits_: UINT32;

    procedure set_has_Games;
    procedure clear_has_Games;
    procedure GamesNotifyEvent(Sender: TObject; const Item: TPB_Game; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_UpdateGameObjects; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_UpdateGameObjects);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated Game Games = 1;
    function has_Games: Boolean;
    procedure clear_Games;
    property Games: TList<TPB_Game> read FGames;

  end;

  TPB_UpdateGameObjectsList = class(TObjectList<TPB_UpdateGameObjects>)
    procedure Assign(const APB_UpdateGameObjectsList: TList<TPB_UpdateGameObjects>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_UpdateGameObjects.Create(const AFrom: TPB_UpdateGameObjects; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_UpdateGameObjects.Destroy;
begin
  if Assigned(FGames) then
  begin
    FGames.OnNotify := nil;
    FreeAndNil(FGames);
  end;
  inherited;
end;

procedure TPB_UpdateGameObjects.InitObjects;
begin
  inherited;
  FGames := TObjectList<TPB_Game>.Create;
end;

procedure TPB_UpdateGameObjects.HookNotifiers;
begin
  inherited;
  FGames.OnNotify := GamesNotifyEvent;
end;

procedure TPB_UpdateGameObjects.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kGamesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGames.Add(TPB_Game.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Games;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_UpdateGameObjects.MergeFrom(const AFrom: TPB_UpdateGameObjects);
var
  pbobj0: TPB_Game;
begin
  for pbobj0 in AFrom.Games do
    FGames.Add(TPB_Game.Create(pbobj0));
end;

function TPB_UpdateGameObjects.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $0) <> $0 then
    Exit(FALSE);
  for pbobj in Games do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_UpdateGameObjects.clear_Games;
var
  on_notify: TCollectionNotifyEvent<TPB_Game>;
begin
  on_notify := FGames.OnNotify;
  FGames.OnNotify := nil;
  FGames.Clear;
  FGames.OnNotify := on_notify;
  clear_has_Games;
end;

function TPB_UpdateGameObjects.has_Games: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_UpdateGameObjects.set_has_Games;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_UpdateGameObjects.clear_has_Games;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_UpdateGameObjects.GamesNotifyEvent(Sender: TObject; const Item: TPB_Game; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Games;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kGamesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_UpdateGameObjects.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Games;
end;

procedure TPB_UpdateGameObjectsList.Assign(const APB_UpdateGameObjectsList: TList<TPB_UpdateGameObjects>);
var
  pbobj: TPB_UpdateGameObjects;
begin
  Clear;
  for pbobj in APB_UpdateGameObjectsList do
    Add(TPB_UpdateGameObjects.Create(pbobj, TRUE));
end;

end.
