// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TournamentPrize;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TPB_TournamentPrize = class(TProtobufBaseObject)
  private
    const
      kPlaceFieldNumber = 1;
      kNameFieldNumber = 2;

    var
      FPlace: Integer;
      FName: String;
      _has_bits_: UINT32;

    procedure set_has_Place;
    procedure clear_has_Place;
    procedure SetPlace(const AValue: Integer);
    procedure set_has_Name;
    procedure clear_has_Name;
    procedure SetName(const AValue: String);

  public
    constructor Create(const AFrom: TPB_TournamentPrize; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TournamentPrize);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required int32 Place = 1;
    function has_Place: Boolean;
    procedure clear_Place;
    property Place: Integer read FPlace write SetPlace;

    // required string Name = 2;
    function has_Name: Boolean;
    procedure clear_Name;
    property Name: String read FName write SetName;

  end;

  TPB_TournamentPrizeList = class(TObjectList<TPB_TournamentPrize>)
    procedure Assign(const APB_TournamentPrizeList: TList<TPB_TournamentPrize>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TournamentPrize.Create(const AFrom: TPB_TournamentPrize; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TournamentPrize.Destroy;
begin
  inherited;
end;

procedure TPB_TournamentPrize.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kPlaceFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FPlace := AProtobufReader.readInt32;
        set_has_Place;
      end;
      kNameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FName := AProtobufReader.readUtf8String;
        set_has_Name;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TournamentPrize.MergeFrom(const AFrom: TPB_TournamentPrize);
begin
  if AFrom.has_Place then
    SetPlace(AFrom.Place);
  if AFrom.has_Name then
    SetName(AFrom.Name);
end;

function TPB_TournamentPrize.IsInitialized: Boolean;
begin
  if (_has_bits_ and $3) <> $3 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TournamentPrize.clear_Place;
begin
  FPlace := 0;
  clear_has_Place;
end;

function TPB_TournamentPrize.has_Place: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TournamentPrize.set_has_Place;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TournamentPrize.clear_has_Place;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_TournamentPrize.SetPlace(const AValue: Integer);
begin
  if not Lightweight then
    Assert(not has_Place);
  FPlace := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kPlaceFieldNumber, AValue);
  set_has_Place;
end;

procedure TPB_TournamentPrize.clear_Name;
begin
  FName := '';
  clear_has_Name;
end;

function TPB_TournamentPrize.has_Name: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_TournamentPrize.set_has_Name;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_TournamentPrize.clear_has_Name;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_TournamentPrize.SetName(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Name);
  FName := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kNameFieldNumber, AValue);
  set_has_Name;
end;

procedure TPB_TournamentPrize.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Place;
  clear_Name;
end;

procedure TPB_TournamentPrizeList.Assign(const APB_TournamentPrizeList: TList<TPB_TournamentPrize>);
var
  pbobj: TPB_TournamentPrize;
begin
  Clear;
  for pbobj in APB_TournamentPrizeList do
    Add(TPB_TournamentPrize.Create(pbobj, TRUE));
end;

end.
