// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.SubscriptionPlanChange;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.User;

type
  TPB_SubscriptionPlanChange = class(TProtobufBaseObject)
  private
    const
      kSubscriptionPlanFieldNumber = 1;
      kUrlFieldNumber = 2;
      kStripeTokenFieldNumber = 3;

    var
      FSubscriptionPlan: TPlayerSubscriptionPlan;
      FUrl: String;
      FStripeToken: String;
      _has_bits_: UINT32;

    procedure set_has_SubscriptionPlan;
    procedure clear_has_SubscriptionPlan;
    procedure SetSubscriptionPlan(const AValue: TPlayerSubscriptionPlan);
    procedure set_has_Url;
    procedure clear_has_Url;
    procedure SetUrl(const AValue: String);
    procedure set_has_StripeToken;
    procedure clear_has_StripeToken;
    procedure SetStripeToken(const AValue: String);

  public
    constructor Create(const AFrom: TPB_SubscriptionPlanChange; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_SubscriptionPlanChange);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required PlayerSubscriptionPlan SubscriptionPlan = 1;
    function has_SubscriptionPlan: Boolean;
    procedure clear_SubscriptionPlan;
    property SubscriptionPlan: TPlayerSubscriptionPlan read FSubscriptionPlan write SetSubscriptionPlan;

    // optional string Url = 2;
    function has_Url: Boolean;
    procedure clear_Url;
    property Url: String read FUrl write SetUrl;

    // optional string StripeToken = 3;
    function has_StripeToken: Boolean;
    procedure clear_StripeToken;
    property StripeToken: String read FStripeToken write SetStripeToken;

  end;

  TPB_SubscriptionPlanChangeList = class(TObjectList<TPB_SubscriptionPlanChange>)
    procedure Assign(const APB_SubscriptionPlanChangeList: TList<TPB_SubscriptionPlanChange>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_SubscriptionPlanChange.Create(const AFrom: TPB_SubscriptionPlanChange; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_SubscriptionPlanChange.Destroy;
begin
  inherited;
end;

procedure TPB_SubscriptionPlanChange.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kSubscriptionPlanFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSubscriptionPlan := TPlayerSubscriptionPlan(AProtobufReader.readEnum);
        set_has_SubscriptionPlan;
      end;
      kUrlFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUrl := AProtobufReader.readUtf8String;
        set_has_Url;
      end;
      kStripeTokenFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FStripeToken := AProtobufReader.readUtf8String;
        set_has_StripeToken;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_SubscriptionPlanChange.MergeFrom(const AFrom: TPB_SubscriptionPlanChange);
begin
  if AFrom.has_SubscriptionPlan then
    SetSubscriptionPlan(AFrom.SubscriptionPlan);
  if AFrom.has_Url then
    SetUrl(AFrom.Url);
  if AFrom.has_StripeToken then
    SetStripeToken(AFrom.StripeToken);
end;

function TPB_SubscriptionPlanChange.IsInitialized: Boolean;
begin
  if (_has_bits_ and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_SubscriptionPlanChange.clear_SubscriptionPlan;
begin
  FSubscriptionPlan := TPlayerSubscriptionPlan(0);
  clear_has_SubscriptionPlan;
end;

function TPB_SubscriptionPlanChange.has_SubscriptionPlan: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_SubscriptionPlanChange.set_has_SubscriptionPlan;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_SubscriptionPlanChange.clear_has_SubscriptionPlan;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_SubscriptionPlanChange.SetSubscriptionPlan(const AValue: TPlayerSubscriptionPlan);
begin
  Assert(not has_SubscriptionPlan);
  FSubscriptionPlan := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kSubscriptionPlanFieldNumber, Integer(AValue));
  set_has_SubscriptionPlan;
end;

procedure TPB_SubscriptionPlanChange.clear_Url;
begin
  FUrl := '';
  clear_has_Url;
end;

function TPB_SubscriptionPlanChange.has_Url: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_SubscriptionPlanChange.set_has_Url;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_SubscriptionPlanChange.clear_has_Url;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_SubscriptionPlanChange.SetUrl(const AValue: String);
begin
  Assert(not has_Url);
  FUrl := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kUrlFieldNumber, AValue);
  set_has_Url;
end;

procedure TPB_SubscriptionPlanChange.clear_StripeToken;
begin
  FStripeToken := '';
  clear_has_StripeToken;
end;

function TPB_SubscriptionPlanChange.has_StripeToken: Boolean;
begin
  result := (_has_bits_ and 4) > 0;
end;

procedure TPB_SubscriptionPlanChange.set_has_StripeToken;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_SubscriptionPlanChange.clear_has_StripeToken;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_SubscriptionPlanChange.SetStripeToken(const AValue: String);
begin
  Assert(not has_StripeToken);
  FStripeToken := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kStripeTokenFieldNumber, AValue);
  set_has_StripeToken;
end;

procedure TPB_SubscriptionPlanChange.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_SubscriptionPlan;
  clear_Url;
  clear_StripeToken;
end;

procedure TPB_SubscriptionPlanChangeList.Assign(const APB_SubscriptionPlanChangeList: TList<TPB_SubscriptionPlanChange>);
var
  pbobj: TPB_SubscriptionPlanChange;
begin
  Clear;
  for pbobj in APB_SubscriptionPlanChangeList do
    Add(TPB_SubscriptionPlanChange.Create(pbobj, TRUE));
end;

end.
