// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.ValidCharsRegex;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  {$RTTI INHERIT}
  TPB_ValidCharsRegex = class(TProtobufBaseObject)
  private
    const
      kEmailFieldNumber = 1;
      kUsernameFieldNumber = 2;
      kPasswordFieldNumber = 3;
      kClubnameFieldNumber = 4;
      kClubpasswordFieldNumber = 5;
      kGamenameFieldNumber = 6;

    var
      FEmail: String;
      FUsername: String;
      FPassword: String;
      FClubname: String;
      FClubpassword: String;
      FGamename: String;
      FHasBits: UINT32;

    procedure set_has_Email;
    procedure clear_has_Email;
    procedure SetEmail(const AValue: String);
    procedure set_has_Username;
    procedure clear_has_Username;
    procedure SetUsername(const AValue: String);
    procedure set_has_Password;
    procedure clear_has_Password;
    procedure SetPassword(const AValue: String);
    procedure set_has_Clubname;
    procedure clear_has_Clubname;
    procedure SetClubname(const AValue: String);
    procedure set_has_Clubpassword;
    procedure clear_has_Clubpassword;
    procedure SetClubpassword(const AValue: String);
    procedure set_has_Gamename;
    procedure clear_has_Gamename;
    procedure SetGamename(const AValue: String);
  public
    constructor Create(const AFrom: TPB_ValidCharsRegex; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_ValidCharsRegex);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required string Email = 1;
    function has_Email: Boolean;
    procedure clear_Email;

    // required string Username = 2;
    function has_Username: Boolean;
    procedure clear_Username;

    // required string Password = 3;
    function has_Password: Boolean;
    procedure clear_Password;

    // required string Clubname = 4;
    function has_Clubname: Boolean;
    procedure clear_Clubname;

    // required string Clubpassword = 5;
    function has_Clubpassword: Boolean;
    procedure clear_Clubpassword;

    // required string Gamename = 6;
    function has_Gamename: Boolean;
    procedure clear_Gamename;
  published
    property Email: String read FEmail write SetEmail;
    property Username: String read FUsername write SetUsername;
    property Password: String read FPassword write SetPassword;
    property Clubname: String read FClubname write SetClubname;
    property Clubpassword: String read FClubpassword write SetClubpassword;
    property Gamename: String read FGamename write SetGamename;
  end;

  TPB_ValidCharsRegexList = class(TObjectList<TPB_ValidCharsRegex>)
    procedure Assign(const APB_ValidCharsRegexList: TList<TPB_ValidCharsRegex>);
  end;

implementation

uses
  pbPublic;


constructor TPB_ValidCharsRegex.Create(const AFrom: TPB_ValidCharsRegex; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_ValidCharsRegex.Destroy;
begin
  inherited;
end;

procedure TPB_ValidCharsRegex.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kEmailFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FEmail := AProtobufReader.readUtf8String;
        set_has_Email;
      end;
      kUsernameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsername := AProtobufReader.readUtf8String;
        set_has_Username;
      end;
      kPasswordFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPassword := AProtobufReader.readUtf8String;
        set_has_Password;
      end;
      kClubnameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubname := AProtobufReader.readUtf8String;
        set_has_Clubname;
      end;
      kClubpasswordFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubpassword := AProtobufReader.readUtf8String;
        set_has_Clubpassword;
      end;
      kGamenameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGamename := AProtobufReader.readUtf8String;
        set_has_Gamename;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_ValidCharsRegex.MergeFrom(const AFrom: TPB_ValidCharsRegex);
begin
  if AFrom.has_Email then
    SetEmail(AFrom.Email);
  if AFrom.has_Username then
    SetUsername(AFrom.Username);
  if AFrom.has_Password then
    SetPassword(AFrom.Password);
  if AFrom.has_Clubname then
    SetClubname(AFrom.Clubname);
  if AFrom.has_Clubpassword then
    SetClubpassword(AFrom.Clubpassword);
  if AFrom.has_Gamename then
    SetGamename(AFrom.Gamename);
end;

function TPB_ValidCharsRegex.IsInitialized: Boolean;
begin
  if (FHasBits and $3f) <> $3f then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_ValidCharsRegex.clear_Email;
begin
  FEmail := '';
  clear_has_Email;
end;

function TPB_ValidCharsRegex.has_Email: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Email;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_ValidCharsRegex.clear_has_Email;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_ValidCharsRegex.SetEmail(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Email);
  FEmail := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kEmailFieldNumber, AValue);
  set_has_Email;
end;

procedure TPB_ValidCharsRegex.clear_Username;
begin
  FUsername := '';
  clear_has_Username;
end;

function TPB_ValidCharsRegex.has_Username: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Username;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_ValidCharsRegex.clear_has_Username;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_ValidCharsRegex.SetUsername(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Username);
  FUsername := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kUsernameFieldNumber, AValue);
  set_has_Username;
end;

procedure TPB_ValidCharsRegex.clear_Password;
begin
  FPassword := '';
  clear_has_Password;
end;

function TPB_ValidCharsRegex.has_Password: Boolean;
begin
  result := (FHasBits and 4) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Password;
begin
  FHasBits := FHasBits or 4;
end;

procedure TPB_ValidCharsRegex.clear_has_Password;
begin
  FHasBits := FHasBits and not 4;
end;

procedure TPB_ValidCharsRegex.SetPassword(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Password);
  FPassword := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kPasswordFieldNumber, AValue);
  set_has_Password;
end;

procedure TPB_ValidCharsRegex.clear_Clubname;
begin
  FClubname := '';
  clear_has_Clubname;
end;

function TPB_ValidCharsRegex.has_Clubname: Boolean;
begin
  result := (FHasBits and 8) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Clubname;
begin
  FHasBits := FHasBits or 8;
end;

procedure TPB_ValidCharsRegex.clear_has_Clubname;
begin
  FHasBits := FHasBits and not 8;
end;

procedure TPB_ValidCharsRegex.SetClubname(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Clubname);
  FClubname := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kClubnameFieldNumber, AValue);
  set_has_Clubname;
end;

procedure TPB_ValidCharsRegex.clear_Clubpassword;
begin
  FClubpassword := '';
  clear_has_Clubpassword;
end;

function TPB_ValidCharsRegex.has_Clubpassword: Boolean;
begin
  result := (FHasBits and 16) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Clubpassword;
begin
  FHasBits := FHasBits or 16;
end;

procedure TPB_ValidCharsRegex.clear_has_Clubpassword;
begin
  FHasBits := FHasBits and not 16;
end;

procedure TPB_ValidCharsRegex.SetClubpassword(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Clubpassword);
  FClubpassword := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kClubpasswordFieldNumber, AValue);
  set_has_Clubpassword;
end;

procedure TPB_ValidCharsRegex.clear_Gamename;
begin
  FGamename := '';
  clear_has_Gamename;
end;

function TPB_ValidCharsRegex.has_Gamename: Boolean;
begin
  result := (FHasBits and 32) > 0;
end;

procedure TPB_ValidCharsRegex.set_has_Gamename;
begin
  FHasBits := FHasBits or 32;
end;

procedure TPB_ValidCharsRegex.clear_has_Gamename;
begin
  FHasBits := FHasBits and not 32;
end;

procedure TPB_ValidCharsRegex.SetGamename(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_Gamename);
  FGamename := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kGamenameFieldNumber, AValue);
  set_has_Gamename;
end;

procedure TPB_ValidCharsRegex.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_Email;
  clear_Username;
  clear_Password;
  clear_Clubname;
  clear_Clubpassword;
  clear_Gamename;
end;

procedure TPB_ValidCharsRegexList.Assign(const APB_ValidCharsRegexList: TList<TPB_ValidCharsRegex>);
var
  pbobj: TPB_ValidCharsRegex;
begin
  Clear;
  for pbobj in APB_ValidCharsRegexList do
    Add(TPB_ValidCharsRegex.Create(pbobj, TRUE));
end;

end.
