// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.ChangeEMailParams;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TPB_ChangeEMailParams = class(TProtobufBaseObject)
  private
    const
      kNewMailFieldNumber = 1;

    var
      FNewMail: String;
      _has_bits_: UINT32;

    procedure set_has_NewMail;
    procedure clear_has_NewMail;
    procedure SetNewMail(const AValue: String);
  public
    constructor Create(const AFrom: TPB_ChangeEMailParams; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_ChangeEMailParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required string NewMail = 1;
    function has_NewMail: Boolean;
    procedure clear_NewMail;
    property NewMail: String read FNewMail write SetNewMail;

  end;

  TPB_ChangeEMailParamsList = class(TObjectList<TPB_ChangeEMailParams>)
    procedure Assign(const APB_ChangeEMailParamsList: TList<TPB_ChangeEMailParams>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_ChangeEMailParams.Create(const AFrom: TPB_ChangeEMailParams; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_ChangeEMailParams.Destroy;
begin
  inherited;
end;

procedure TPB_ChangeEMailParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kNewMailFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FNewMail := AProtobufReader.readUtf8String;
        set_has_NewMail;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_ChangeEMailParams.MergeFrom(const AFrom: TPB_ChangeEMailParams);
begin
  if AFrom.has_NewMail then
    SetNewMail(AFrom.NewMail);
end;

function TPB_ChangeEMailParams.IsInitialized: Boolean;
begin
  if (_has_bits_ and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_ChangeEMailParams.clear_NewMail;
begin
  FNewMail := '';
  clear_has_NewMail;
end;

function TPB_ChangeEMailParams.has_NewMail: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_ChangeEMailParams.set_has_NewMail;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_ChangeEMailParams.clear_has_NewMail;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_ChangeEMailParams.SetNewMail(const AValue: String);
begin
  if not Lightweight then
    Assert(not has_NewMail);
  FNewMail := AValue;
  if not Lightweight then
    ProtobufOutput.writeString(kNewMailFieldNumber, AValue);
  set_has_NewMail;
end;

procedure TPB_ChangeEMailParams.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_NewMail;
end;

procedure TPB_ChangeEMailParamsList.Assign(const APB_ChangeEMailParamsList: TList<TPB_ChangeEMailParams>);
var
  pbobj: TPB_ChangeEMailParams;
begin
  Clear;
  for pbobj in APB_ChangeEMailParamsList do
    Add(TPB_ChangeEMailParams.Create(pbobj, TRUE));
end;

end.
