// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.AssetList;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.UpdateFileInfo;

type
  TPB_AssetList = class(TProtobufBaseObject)
  private
    const
      kAssetsFieldNumber = 1;

    var
      FAssets: TList<TPB_UpdateFileInfo>;
      _has_bits_: UINT32;

    procedure set_has_Assets;
    procedure clear_has_Assets;
    procedure AssetsNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_AssetList; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_AssetList);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated UpdateFileInfo Assets = 1;
    function has_Assets: Boolean;
    procedure clear_Assets;
    property Assets: TList<TPB_UpdateFileInfo> read FAssets;

  end;

  TPB_AssetListList = class(TObjectList<TPB_AssetList>)
    procedure Assign(const APB_AssetListList: TList<TPB_AssetList>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_AssetList.Create(const AFrom: TPB_AssetList; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_AssetList.Destroy;
begin
  if Assigned(FAssets) then
  begin
    FAssets.OnNotify := nil;
    FreeAndNil(FAssets);
  end;
  inherited;
end;

procedure TPB_AssetList.InitObjects;
begin
  inherited;
  FAssets := TObjectList<TPB_UpdateFileInfo>.Create;
end;

procedure TPB_AssetList.HookNotifiers;
begin
  inherited;
  FAssets.OnNotify := AssetsNotifyEvent;
end;

procedure TPB_AssetList.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kAssetsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FAssets.Add(TPB_UpdateFileInfo.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Assets;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_AssetList.MergeFrom(const AFrom: TPB_AssetList);
var
  pbobj0: TPB_UpdateFileInfo;
begin
  for pbobj0 in AFrom.Assets do
    FAssets.Add(TPB_UpdateFileInfo.Create(pbobj0, Lightweight));
end;

function TPB_AssetList.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $0) <> $0 then
    Exit(FALSE);
  for pbobj in Assets do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_AssetList.clear_Assets;
var
  on_notify: TCollectionNotifyEvent<TPB_UpdateFileInfo>;
begin
  on_notify := FAssets.OnNotify;
  FAssets.OnNotify := nil;
  FAssets.Clear;
  FAssets.OnNotify := on_notify;
  clear_has_Assets;
end;

function TPB_AssetList.has_Assets: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_AssetList.set_has_Assets;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_AssetList.clear_has_Assets;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_AssetList.AssetsNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Assets;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kAssetsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_AssetList.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Assets;
end;

procedure TPB_AssetListList.Assign(const APB_AssetListList: TList<TPB_AssetList>);
var
  pbobj: TPB_AssetList;
begin
  Clear;
  for pbobj in APB_AssetListList do
    Add(TPB_AssetList.Create(pbobj, TRUE));
end;

end.
