// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.SetAvatarParams;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  {$RTTI INHERIT}
  TPB_SetAvatarParams = class(TProtobufBaseObject)
  private
    const
      kAvatarIdFieldNumber = 1;

    var
      FAvatarId: TBytes;
      FHasBits: UINT32;

    procedure set_has_AvatarId;
    procedure clear_has_AvatarId;
    procedure SetAvatarId(const AValue: TBytes);
  public
    constructor Create(const AFrom: TPB_SetAvatarParams; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_SetAvatarParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes AvatarId = 1;
    function has_AvatarId: Boolean;
    procedure clear_AvatarId;
  published
    property AvatarId: TBytes read FAvatarId write SetAvatarId;
  end;

  TPB_SetAvatarParamsList = class(TObjectList<TPB_SetAvatarParams>)
    procedure Assign(const APB_SetAvatarParamsList: TList<TPB_SetAvatarParams>);
  end;

implementation

uses
  pbPublic;


constructor TPB_SetAvatarParams.Create(const AFrom: TPB_SetAvatarParams; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_SetAvatarParams.Destroy;
begin
  inherited;
end;

procedure TPB_SetAvatarParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kAvatarIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FAvatarId := AProtobufReader.readBytes;
        set_has_AvatarId;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_SetAvatarParams.MergeFrom(const AFrom: TPB_SetAvatarParams);
begin
  if AFrom.has_AvatarId then
    SetAvatarId(AFrom.AvatarId);
end;

function TPB_SetAvatarParams.IsInitialized: Boolean;
begin
  if (FHasBits and $1) <> $1 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_SetAvatarParams.clear_AvatarId;
begin
  SetLength(FAvatarId, 0);
  clear_has_AvatarId;
end;

function TPB_SetAvatarParams.has_AvatarId: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_SetAvatarParams.set_has_AvatarId;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_SetAvatarParams.clear_has_AvatarId;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_SetAvatarParams.SetAvatarId(const AValue: TBytes);
begin
  if not Lightweight then
    Assert(not has_AvatarId);
  FAvatarId := Copy(AValue, 0, Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kAvatarIdFieldNumber, AValue);
  set_has_AvatarId;
end;

procedure TPB_SetAvatarParams.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_AvatarId;
end;

procedure TPB_SetAvatarParamsList.Assign(const APB_SetAvatarParamsList: TList<TPB_SetAvatarParams>);
var
  pbobj: TPB_SetAvatarParams;
begin
  Clear;
  for pbobj in APB_SetAvatarParamsList do
    Add(TPB_SetAvatarParams.Create(pbobj, TRUE));
end;

end.
