// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TableStatsReplies;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.TableStatsReply, Poker.Protobufs.Objects.User, Poker.Protobufs.Objects.ClubStatsReply;

type
  TPB_TableStatsReplies = class(TProtobufBaseObject)
  private
    const
      kReplyFieldNumber = 1;
      kPlayersFieldNumber = 2;
      kClubStatsFieldNumber = 3;

    var
      FReply: TList<TPB_TableStatsReply>;
      FPlayers: TList<TPB_User>;
      FClubStats: TList<TPB_ClubStatsReply>;
      FHasBits: UINT32;

    procedure set_has_Reply;
    procedure clear_has_Reply;
    procedure set_has_Players;
    procedure clear_has_Players;
    procedure set_has_ClubStats;
    procedure clear_has_ClubStats;
    procedure ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
    procedure ClubStatsNotifyEvent(Sender: TObject; const Item: TPB_ClubStatsReply; Action: TCollectionNotification);
  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;
  public
    constructor Create(const AFrom: TPB_TableStatsReplies; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TableStatsReplies);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated TableStatsReply Reply = 1;
    function has_Reply: Boolean;
    procedure clear_Reply;
    property Reply: TList<TPB_TableStatsReply> read FReply;

    // repeated User Players = 2;
    function has_Players: Boolean;
    procedure clear_Players;
    property Players: TList<TPB_User> read FPlayers;

    // repeated ClubStatsReply ClubStats = 3;
    function has_ClubStats: Boolean;
    procedure clear_ClubStats;
    property ClubStats: TList<TPB_ClubStatsReply> read FClubStats;

  end;

  TPB_TableStatsRepliesList = class(TObjectList<TPB_TableStatsReplies>)
    procedure Assign(const APB_TableStatsRepliesList: TList<TPB_TableStatsReplies>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TableStatsReplies.Create(const AFrom: TPB_TableStatsReplies; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TableStatsReplies.Destroy;
begin
  if Assigned(FReply) then
  begin
    FReply.OnNotify := nil;
    FreeAndNil(FReply);
  end;
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  if Assigned(FClubStats) then
  begin
    FClubStats.OnNotify := nil;
    FreeAndNil(FClubStats);
  end;
  inherited;
end;

procedure TPB_TableStatsReplies.InitObjects;
begin
  inherited;
  FReply := TObjectList<TPB_TableStatsReply>.Create;
  FPlayers := TObjectList<TPB_User>.Create;
  FClubStats := TObjectList<TPB_ClubStatsReply>.Create;
end;

procedure TPB_TableStatsReplies.HookNotifiers;
begin
  inherited;
  FReply.OnNotify := ReplyNotifyEvent;
  FPlayers.OnNotify := PlayersNotifyEvent;
  FClubStats.OnNotify := ClubStatsNotifyEvent;
end;

procedure TPB_TableStatsReplies.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kReplyFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FReply.Add(TPB_TableStatsReply.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Reply;
      end;
      kPlayersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_User.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Players;
      end;
      kClubStatsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubStats.Add(TPB_ClubStatsReply.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_ClubStats;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TableStatsReplies.MergeFrom(const AFrom: TPB_TableStatsReplies);
var
  pbobj0: TPB_TableStatsReply;
  pbobj1: TPB_User;
  pbobj2: TPB_ClubStatsReply;
begin
  for pbobj0 in AFrom.Reply do
    FReply.Add(TPB_TableStatsReply.Create(pbobj0, Lightweight));
  for pbobj1 in AFrom.Players do
    FPlayers.Add(TPB_User.Create(pbobj1, Lightweight));
  for pbobj2 in AFrom.ClubStats do
    FClubStats.Add(TPB_ClubStatsReply.Create(pbobj2, Lightweight));
end;

function TPB_TableStatsReplies.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (FHasBits and $0) <> $0 then
    Exit(FALSE);
  for pbobj in Reply do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in Players do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in ClubStats do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TableStatsReplies.clear_Reply;
var
  on_notify: TCollectionNotifyEvent<TPB_TableStatsReply>;
begin
  on_notify := FReply.OnNotify;
  FReply.OnNotify := nil;
  FReply.Clear;
  FReply.OnNotify := on_notify;
  clear_has_Reply;
end;

function TPB_TableStatsReplies.has_Reply: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_TableStatsReplies.set_has_Reply;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_TableStatsReplies.clear_has_Reply;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_TableStatsReplies.ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Reply;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kReplyFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_TableStatsReplies.clear_Players;
var
  on_notify: TCollectionNotifyEvent<TPB_User>;
begin
  on_notify := FPlayers.OnNotify;
  FPlayers.OnNotify := nil;
  FPlayers.Clear;
  FPlayers.OnNotify := on_notify;
  clear_has_Players;
end;

function TPB_TableStatsReplies.has_Players: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_TableStatsReplies.set_has_Players;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_TableStatsReplies.clear_has_Players;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_TableStatsReplies.PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Players;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPlayersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_TableStatsReplies.clear_ClubStats;
var
  on_notify: TCollectionNotifyEvent<TPB_ClubStatsReply>;
begin
  on_notify := FClubStats.OnNotify;
  FClubStats.OnNotify := nil;
  FClubStats.Clear;
  FClubStats.OnNotify := on_notify;
  clear_has_ClubStats;
end;

function TPB_TableStatsReplies.has_ClubStats: Boolean;
begin
  result := (FHasBits and 4) > 0;
end;

procedure TPB_TableStatsReplies.set_has_ClubStats;
begin
  FHasBits := FHasBits or 4;
end;

procedure TPB_TableStatsReplies.clear_has_ClubStats;
begin
  FHasBits := FHasBits and not 4;
end;

procedure TPB_TableStatsReplies.ClubStatsNotifyEvent(Sender: TObject; const Item: TPB_ClubStatsReply; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_ClubStats;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kClubStatsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_TableStatsReplies.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_Reply;
  clear_Players;
  clear_ClubStats;
end;

procedure TPB_TableStatsRepliesList.Assign(const APB_TableStatsRepliesList: TList<TPB_TableStatsReplies>);
var
  pbobj: TPB_TableStatsReplies;
begin
  Clear;
  for pbobj in APB_TableStatsRepliesList do
    Add(TPB_TableStatsReplies.Create(pbobj, TRUE));
end;

end.
