// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.LoginReply;

interface

uses
  System.SysUtils,
  {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF},
  pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.TableStatus, Poker.Protobufs.Objects.TournamentInfo, Poker.Protobufs.Objects.Club, Poker.Protobufs.Objects.User, Poker.Protobufs.Objects.Game, Poker.Protobufs.Objects.PlayerClubStatus;

type
  TLoginStatus = (lrSuccess = 0, lrInvalid);

  TPB_LoginReply = class(TProtobufBaseObject)
  private
    const
      kLoginStatusFieldNumber = 1;
      kReconnectTablesFieldNumber = 2;
      kTournamentInfosFieldNumber = 3;
      kRegisteredTournamentsFieldNumber = 4;
      kClubsFieldNumber = 5;
      kUsersFieldNumber = 6;
      kSelfFieldNumber = 7;
      kGamesFieldNumber = 8;
      kPlayerClubStatusesFieldNumber = 9;

    var
      FLoginStatus: TLoginStatus;
      FReconnectTables: TList<TPB_TableStatus>;
      FTournamentInfos: TList<TPB_TournamentInfo>;
      FRegisteredTournaments: TList<TMongoId>;
      FClubs: TList<TPB_Club>;
      FUsers: TList<TPB_User>;
      FSelf: TPB_User;
      FGames: TList<TPB_Game>;
      FPlayerClubStatuses: TList<TPB_PlayerClubStatus>;
      FHasBits: UINT32;

    procedure set_has_LoginStatus;
    procedure clear_has_LoginStatus;
    procedure SetLoginStatus(const AValue: TLoginStatus);
    procedure set_has_ReconnectTables;
    procedure clear_has_ReconnectTables;
    procedure set_has_TournamentInfos;
    procedure clear_has_TournamentInfos;
    procedure set_has_RegisteredTournaments;
    procedure clear_has_RegisteredTournaments;
    procedure set_has_Clubs;
    procedure clear_has_Clubs;
    procedure set_has_Users;
    procedure clear_has_Users;
    procedure set_has_Self;
    procedure clear_has_Self;
    procedure SetSelf(const AValue: TPB_User);
    procedure set_has_Games;
    procedure clear_has_Games;
    procedure set_has_PlayerClubStatuses;
    procedure clear_has_PlayerClubStatuses;
    procedure ReconnectTablesNotifyEvent(Sender: TObject; const Item: TPB_TableStatus; Action: TCollectionNotification);
    procedure TournamentInfosNotifyEvent(Sender: TObject; const Item: TPB_TournamentInfo; Action: TCollectionNotification);
    procedure RegisteredTournamentsNotifyEvent(Sender: TObject; const Item: TMongoId; Action: TCollectionNotification);
    procedure ClubsNotifyEvent(Sender: TObject; const Item: TPB_Club; Action: TCollectionNotification);
    procedure UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
    procedure GamesNotifyEvent(Sender: TObject; const Item: TPB_Game; Action: TCollectionNotification);
    procedure PlayerClubStatusesNotifyEvent(Sender: TObject; const Item: TPB_PlayerClubStatus; Action: TCollectionNotification);
  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;
  public
    constructor Create(const AFrom: TPB_LoginReply; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_LoginReply);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required LoginStatus LoginStatus = 1;
    function has_LoginStatus: Boolean;
    procedure clear_LoginStatus;
    property LoginStatus: TLoginStatus read FLoginStatus write SetLoginStatus;

    // repeated TableStatus ReconnectTables = 2;
    function has_ReconnectTables: Boolean;
    procedure clear_ReconnectTables;
    property ReconnectTables: TList<TPB_TableStatus> read FReconnectTables;

    // repeated TournamentInfo TournamentInfos = 3;
    function has_TournamentInfos: Boolean;
    procedure clear_TournamentInfos;
    property TournamentInfos: TList<TPB_TournamentInfo> read FTournamentInfos;

    // repeated bytes RegisteredTournaments = 4;
    function has_RegisteredTournaments: Boolean;
    procedure clear_RegisteredTournaments;
    property RegisteredTournaments: TList<TMongoId> read FRegisteredTournaments;

    // repeated Club Clubs = 5;
    function has_Clubs: Boolean;
    procedure clear_Clubs;
    property Clubs: TList<TPB_Club> read FClubs;

    // repeated User Users = 6;
    function has_Users: Boolean;
    procedure clear_Users;
    property Users: TList<TPB_User> read FUsers;

    // optional User Self = 7;
    function has_Self: Boolean;
    procedure clear_Self;
    property Self: TPB_User read FSelf write SetSelf;

    // repeated Game Games = 8;
    function has_Games: Boolean;
    procedure clear_Games;
    property Games: TList<TPB_Game> read FGames;

    // repeated PlayerClubStatus PlayerClubStatuses = 9;
    function has_PlayerClubStatuses: Boolean;
    procedure clear_PlayerClubStatuses;
    property PlayerClubStatuses: TList<TPB_PlayerClubStatus> read FPlayerClubStatuses;
  end;

  TPB_LoginReplyList = class(TObjectList<TPB_LoginReply>)
    procedure Assign(const APB_LoginReplyList: TList<TPB_LoginReply>);
  end;

implementation

uses
  pbPublic;


constructor TPB_LoginReply.Create(const AFrom: TPB_LoginReply; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_LoginReply.Destroy;
begin
  if Assigned(FReconnectTables) then
  begin
    FReconnectTables.OnNotify := nil;
    FreeAndNil(FReconnectTables);
  end;
  if Assigned(FTournamentInfos) then
  begin
    FTournamentInfos.OnNotify := nil;
    FreeAndNil(FTournamentInfos);
  end;
  if Assigned(FRegisteredTournaments) then
  begin
    FRegisteredTournaments.OnNotify := nil;
    FreeAndNil(FRegisteredTournaments);
  end;
  if Assigned(FClubs) then
  begin
    FClubs.OnNotify := nil;
    FreeAndNil(FClubs);
  end;
  if Assigned(FUsers) then
  begin
    FUsers.OnNotify := nil;
    FreeAndNil(FUsers);
  end;
  if Assigned(FSelf) then FreeAndNil(FSelf);
  if Assigned(FGames) then
  begin
    FGames.OnNotify := nil;
    FreeAndNil(FGames);
  end;
  if Assigned(FPlayerClubStatuses) then
  begin
    FPlayerClubStatuses.OnNotify := nil;
    FreeAndNil(FPlayerClubStatuses);
  end;
  inherited;
end;

procedure TPB_LoginReply.InitObjects;
begin
  inherited;
  FReconnectTables := TObjectList<TPB_TableStatus>.Create;
  FTournamentInfos := TObjectList<TPB_TournamentInfo>.Create;
  FRegisteredTournaments := TList<TMongoId>.Create;
  FClubs := TObjectList<TPB_Club>.Create;
  FUsers := TObjectList<TPB_User>.Create;
  FGames := TObjectList<TPB_Game>.Create;
  FPlayerClubStatuses := TObjectList<TPB_PlayerClubStatus>.Create;
end;

procedure TPB_LoginReply.HookNotifiers;
begin
  inherited;
  FReconnectTables.OnNotify := ReconnectTablesNotifyEvent;
  FTournamentInfos.OnNotify := TournamentInfosNotifyEvent;
  FRegisteredTournaments.OnNotify := RegisteredTournamentsNotifyEvent;
  FClubs.OnNotify := ClubsNotifyEvent;
  FUsers.OnNotify := UsersNotifyEvent;
  FGames.OnNotify := GamesNotifyEvent;
  FPlayerClubStatuses.OnNotify := PlayerClubStatusesNotifyEvent;
end;

procedure TPB_LoginReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kLoginStatusFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FLoginStatus := TLoginStatus(AProtobufReader.readEnum);
        set_has_LoginStatus;
      end;
      kReconnectTablesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FReconnectTables.Add(TPB_TableStatus.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_ReconnectTables;
      end;
      kTournamentInfosFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FTournamentInfos.Add(TPB_TournamentInfo.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_TournamentInfos;
      end;
      kRegisteredTournamentsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FRegisteredTournaments.Add(AProtobufReader.readMongoId);
        set_has_RegisteredTournaments;
      end;
      kClubsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubs.Add(TPB_Club.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Clubs;
      end;
      kUsersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsers.Add(TPB_User.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Users;
      end;
      kSelfFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FSelf) then
          FSelf := TPB_User.Create;
        FSelf.LoadFromProtobufReader(AProtobufReader, AProtobufReader.readInt32);
        set_has_Self;
      end;
      kGamesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGames.Add(TPB_Game.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Games;
      end;
      kPlayerClubStatusesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerClubStatuses.Add(TPB_PlayerClubStatus.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_PlayerClubStatuses;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_LoginReply.MergeFrom(const AFrom: TPB_LoginReply);
var
  pbobj1: TPB_TableStatus;
  pbobj2: TPB_TournamentInfo;
  pbobj4: TPB_Club;
  pbobj5: TPB_User;
  pbobj7: TPB_Game;
  pbobj8: TPB_PlayerClubStatus;
begin
  if AFrom.has_LoginStatus then
    SetLoginStatus(AFrom.LoginStatus);
  for pbobj1 in AFrom.ReconnectTables do
    FReconnectTables.Add(TPB_TableStatus.Create(pbobj1, Lightweight));
  for pbobj2 in AFrom.TournamentInfos do
    FTournamentInfos.Add(TPB_TournamentInfo.Create(pbobj2, Lightweight));
  FRegisteredTournaments.AddRange(AFrom.RegisteredTournaments);
  for pbobj4 in AFrom.Clubs do
    FClubs.Add(TPB_Club.Create(pbobj4, Lightweight));
  for pbobj5 in AFrom.Users do
    FUsers.Add(TPB_User.Create(pbobj5, Lightweight));
  if (AFrom.has_Self) then
    FSelf.MergeFrom(AFrom.Self);
  for pbobj7 in AFrom.Games do
    FGames.Add(TPB_Game.Create(pbobj7, Lightweight));
  for pbobj8 in AFrom.PlayerClubStatuses do
    FPlayerClubStatuses.Add(TPB_PlayerClubStatus.Create(pbobj8, Lightweight));
end;

function TPB_LoginReply.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (FHasBits and $1) <> $1 then
    Exit(FALSE);
  for pbobj in ReconnectTables do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in TournamentInfos do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in Clubs do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in Users do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  if (has_Self) then
    if not FSelf.IsInitialized then
      Exit(FALSE);
  for pbobj in Games do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  for pbobj in PlayerClubStatuses do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_LoginReply.clear_LoginStatus;
begin
  FLoginStatus := TLoginStatus(0);
  clear_has_LoginStatus;
end;

function TPB_LoginReply.has_LoginStatus: Boolean;
begin
  result := (FHasBits and 1) > 0;
end;

procedure TPB_LoginReply.set_has_LoginStatus;
begin
  FHasBits := FHasBits or 1;
end;

procedure TPB_LoginReply.clear_has_LoginStatus;
begin
  FHasBits := FHasBits and not 1;
end;

procedure TPB_LoginReply.SetLoginStatus(const AValue: TLoginStatus);
begin
  if not Lightweight then
    Assert(not has_LoginStatus);
  FLoginStatus := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kLoginStatusFieldNumber, Integer(AValue));
  set_has_LoginStatus;
end;

procedure TPB_LoginReply.clear_ReconnectTables;
var
  on_notify: TCollectionNotifyEvent<TPB_TableStatus>;
begin
  on_notify := FReconnectTables.OnNotify;
  FReconnectTables.OnNotify := nil;
  FReconnectTables.Clear;
  FReconnectTables.OnNotify := on_notify;
  clear_has_ReconnectTables;
end;

function TPB_LoginReply.has_ReconnectTables: Boolean;
begin
  result := (FHasBits and 2) > 0;
end;

procedure TPB_LoginReply.set_has_ReconnectTables;
begin
  FHasBits := FHasBits or 2;
end;

procedure TPB_LoginReply.clear_has_ReconnectTables;
begin
  FHasBits := FHasBits and not 2;
end;

procedure TPB_LoginReply.ReconnectTablesNotifyEvent(Sender: TObject; const Item: TPB_TableStatus; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_ReconnectTables;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kReconnectTablesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.clear_TournamentInfos;
var
  on_notify: TCollectionNotifyEvent<TPB_TournamentInfo>;
begin
  on_notify := FTournamentInfos.OnNotify;
  FTournamentInfos.OnNotify := nil;
  FTournamentInfos.Clear;
  FTournamentInfos.OnNotify := on_notify;
  clear_has_TournamentInfos;
end;

function TPB_LoginReply.has_TournamentInfos: Boolean;
begin
  result := (FHasBits and 4) > 0;
end;

procedure TPB_LoginReply.set_has_TournamentInfos;
begin
  FHasBits := FHasBits or 4;
end;

procedure TPB_LoginReply.clear_has_TournamentInfos;
begin
  FHasBits := FHasBits and not 4;
end;

procedure TPB_LoginReply.TournamentInfosNotifyEvent(Sender: TObject; const Item: TPB_TournamentInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_TournamentInfos;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kTournamentInfosFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.clear_RegisteredTournaments;
var
  on_notify: TCollectionNotifyEvent<TMongoId>;
begin
  on_notify := FRegisteredTournaments.OnNotify;
  FRegisteredTournaments.OnNotify := nil;
  FRegisteredTournaments.Clear;
  FRegisteredTournaments.OnNotify := on_notify;
  clear_has_RegisteredTournaments;
end;

function TPB_LoginReply.has_RegisteredTournaments: Boolean;
begin
  result := (FHasBits and 8) > 0;
end;

procedure TPB_LoginReply.set_has_RegisteredTournaments;
begin
  FHasBits := FHasBits or 8;
end;

procedure TPB_LoginReply.clear_has_RegisteredTournaments;
begin
  FHasBits := FHasBits and not 8;
end;

procedure TPB_LoginReply.RegisteredTournamentsNotifyEvent(Sender: TObject; const Item: TMongoId; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_RegisteredTournaments;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kRegisteredTournamentsFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(Item.Memory, 12);
  end;
end;

procedure TPB_LoginReply.clear_Clubs;
var
  on_notify: TCollectionNotifyEvent<TPB_Club>;
begin
  on_notify := FClubs.OnNotify;
  FClubs.OnNotify := nil;
  FClubs.Clear;
  FClubs.OnNotify := on_notify;
  clear_has_Clubs;
end;

function TPB_LoginReply.has_Clubs: Boolean;
begin
  result := (FHasBits and 16) > 0;
end;

procedure TPB_LoginReply.set_has_Clubs;
begin
  FHasBits := FHasBits or 16;
end;

procedure TPB_LoginReply.clear_has_Clubs;
begin
  FHasBits := FHasBits and not 16;
end;

procedure TPB_LoginReply.ClubsNotifyEvent(Sender: TObject; const Item: TPB_Club; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Clubs;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kClubsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.clear_Users;
var
  on_notify: TCollectionNotifyEvent<TPB_User>;
begin
  on_notify := FUsers.OnNotify;
  FUsers.OnNotify := nil;
  FUsers.Clear;
  FUsers.OnNotify := on_notify;
  clear_has_Users;
end;

function TPB_LoginReply.has_Users: Boolean;
begin
  result := (FHasBits and 32) > 0;
end;

procedure TPB_LoginReply.set_has_Users;
begin
  FHasBits := FHasBits or 32;
end;

procedure TPB_LoginReply.clear_has_Users;
begin
  FHasBits := FHasBits and not 32;
end;

procedure TPB_LoginReply.UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Users;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kUsersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.clear_Self;
begin
  FreeAndNil(FSelf);
  clear_has_Self;
end;

function TPB_LoginReply.has_Self: Boolean;
begin
  result := (FHasBits and 64) > 0;
end;

procedure TPB_LoginReply.set_has_Self;
begin
  FHasBits := FHasBits or 64;
end;

procedure TPB_LoginReply.clear_has_Self;
begin
  FHasBits := FHasBits and not 64;
end;

procedure TPB_LoginReply.SetSelf(const AValue: TPB_User);
begin
  if not Lightweight then
    Assert(not has_Self);
  FSelf := AValue;
  if not Lightweight then
    ProtobufOutput.writeMessage(kSelfFieldNumber, AValue.ProtobufOutput);
  set_has_Self;
end;

procedure TPB_LoginReply.clear_Games;
var
  on_notify: TCollectionNotifyEvent<TPB_Game>;
begin
  on_notify := FGames.OnNotify;
  FGames.OnNotify := nil;
  FGames.Clear;
  FGames.OnNotify := on_notify;
  clear_has_Games;
end;

function TPB_LoginReply.has_Games: Boolean;
begin
  result := (FHasBits and 128) > 0;
end;

procedure TPB_LoginReply.set_has_Games;
begin
  FHasBits := FHasBits or 128;
end;

procedure TPB_LoginReply.clear_has_Games;
begin
  FHasBits := FHasBits and not 128;
end;

procedure TPB_LoginReply.GamesNotifyEvent(Sender: TObject; const Item: TPB_Game; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Games;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kGamesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.clear_PlayerClubStatuses;
var
  on_notify: TCollectionNotifyEvent<TPB_PlayerClubStatus>;
begin
  on_notify := FPlayerClubStatuses.OnNotify;
  FPlayerClubStatuses.OnNotify := nil;
  FPlayerClubStatuses.Clear;
  FPlayerClubStatuses.OnNotify := on_notify;
  clear_has_PlayerClubStatuses;
end;

function TPB_LoginReply.has_PlayerClubStatuses: Boolean;
begin
  result := (FHasBits and 256) > 0;
end;

procedure TPB_LoginReply.set_has_PlayerClubStatuses;
begin
  FHasBits := FHasBits or 256;
end;

procedure TPB_LoginReply.clear_has_PlayerClubStatuses;
begin
  FHasBits := FHasBits and not 256;
end;

procedure TPB_LoginReply.PlayerClubStatusesNotifyEvent(Sender: TObject; const Item: TPB_PlayerClubStatus; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_PlayerClubStatuses;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPlayerClubStatusesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_LoginReply.Clear;
begin
  if FHasBits = 0 then
    Exit;

  clear_LoginStatus;
  clear_ReconnectTables;
  clear_TournamentInfos;
  clear_RegisteredTournaments;
  clear_Clubs;
  clear_Users;
  clear_Self;
  clear_Games;
  clear_PlayerClubStatuses;
end;

procedure TPB_LoginReplyList.Assign(const APB_LoginReplyList: TList<TPB_LoginReply>);
var
  pbobj: TPB_LoginReply;
begin
  Clear;
  for pbobj in APB_LoginReplyList do
    Add(TPB_LoginReply.Create(pbobj, TRUE));
end;

end.
