object frmReconnect: TfrmReconnect
  Left = 0
  Top = 0
  BorderIcons = [biSystemMenu]
  BorderStyle = bsSingle
  Caption = 'Reconnecting'
  ClientHeight = 61
  ClientWidth = 304
  Color = clWindow
  Ctl3D = False
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  Position = poMainFormCenter
  OnClose = FormClose
  OnCloseQuery = FormCloseQuery
  OnCreate = FormCreate
  OnDestroy = FormDestroy
  DesignSize = (
    304
    61)
  PixelsPerInch = 96
  TextHeight = 13
  object lbsStatus: TcxLabel
    Left = 0
    Top = 0
    Align = alTop
    AutoSize = False
    ParentFont = False
    Style.Font.Charset = DEFAULT_CHARSET
    Style.Font.Color = clWindowText
    Style.Font.Height = -13
    Style.Font.Name = 'Tahoma'
    Style.Font.Style = []
    Style.LookAndFeel.SkinName = 'ChipUpPokerDarkStyle'
    Style.TextColor = clWhite
    Style.TextStyle = [fsBold]
    Style.IsFontAssigned = True
    StyleDisabled.LookAndFeel.SkinName = 'ChipUpPokerDarkStyle'
    StyleFocused.LookAndFeel.SkinName = 'ChipUpPokerDarkStyle'
    StyleHot.LookAndFeel.SkinName = 'ChipUpPokerDarkStyle'
    Properties.Alignment.Horz = taCenter
    Properties.Alignment.Vert = taVCenter
    Transparent = True
    Height = 40
    Width = 304
    AnchorX = 152
    AnchorY = 20
  end
  object pbReconnecting: TcxProgressBar
    Left = 8
    Top = 43
    Anchors = [akLeft, akRight, akBottom]
    AutoSize = False
    Position = 100.000000000000000000
    Properties.AnimationPath = cxapPingPong
    Properties.AnimationSpeed = 4
    Properties.BarStyle = cxbsAnimation
    Properties.BeginColor = 591228
    Properties.PeakValue = 100.000000000000000000
    Properties.ShowText = False
    Properties.ShowTextStyle = cxtsText
    Style.Edges = []
    Style.LookAndFeel.SkinName = ''
    StyleDisabled.LookAndFeel.SkinName = ''
    StyleFocused.LookAndFeel.SkinName = ''
    StyleHot.LookAndFeel.SkinName = ''
    TabOrder = 1
    Height = 12
    Width = 288
  end
  object tiReconnectTimer: TTimer
    OnTimer = tiReconnectTimerTimer
    Left = 212
    Top = 8
  end
end
