#!/bin/bash -e
make
cd ..
export PATH=cpp-generator/:$PATH
protoc message.proto -o message.desc --java_out=android/src/ --delphi_out=cpp-generator/output
node server/rebuild.js
#cp -v message.proto ~/Dropbox/poker/protobuf/
#cp -vr delphi/ ~/Dropbox/poker/protobuf/
#pushd cpp-generator
#cp -vr main.cpp Makefile strutil.h ~/Dropbox/poker/protobuf/generator/
#popd
