// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.QueryTableStats;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_QueryTableStats = class(TProtobufBaseObject)
  private
    const
      kGameidFieldNumber = 1;

    var
      FGameid: TList<TBytes>;
      _has_bits_: UINT32;

    procedure set_has_Gameid;
    procedure clear_has_Gameid;
    procedure GameidNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_QueryTableStats; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_QueryTableStats);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated bytes Gameid = 1;
    function has_Gameid: Boolean;
    procedure clear_Gameid;
    property Gameid: TList<TBytes> read FGameid;

  end;
  TPB_QueryTableStatsList = class (TObjectList<TPB_QueryTableStats>)
    procedure Assign(const APB_QueryTableStatsList: TList<TPB_QueryTableStats>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_QueryTableStats.InitObjects;
begin
  inherited;
  FGameid := TList<TBytes>.Create;
end;

procedure TPB_QueryTableStats.HookNotifiers;
begin
  inherited;
  FGameid.OnNotify := GameidNotifyEvent;
end;

constructor TPB_QueryTableStats.Create(const AFrom: TPB_QueryTableStats; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_QueryTableStats.Destroy;
begin
  if Assigned(FGameid) then
  begin
    FGameid.OnNotify := nil;
    FreeAndNil(FGameid);
  end;
  inherited;
end;

procedure TPB_QueryTableStats.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kGameidFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGameid.Add(AProtobufReader.readBytes);
        set_has_Gameid;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_QueryTableStats.MergeFrom(const AFrom: TPB_QueryTableStats);
begin
  FGameid.AddRange(AFrom.Gameid);
end;

function TPB_QueryTableStats.IsInitialized: Boolean;
begin
  if (_has_bits_ and $0) <> $0 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_QueryTableStats.clear_Gameid;
begin
  FGameid.Clear;
  clear_has_Gameid;
end;

function TPB_QueryTableStats.has_Gameid: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_QueryTableStats.set_has_Gameid;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_QueryTableStats.clear_has_Gameid;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_QueryTableStats.GameidNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Gameid;
  if not Lightweight then
    ProtobufOutput.writeBytes(kGameidFieldNumber,Item);
end;

procedure TPB_QueryTableStats.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Gameid;
end;

procedure TPB_QueryTableStatsList.Assign(const APB_QueryTableStatsList: TList<TPB_QueryTableStats>);
var
  pbobj: TPB_QueryTableStats;
begin
  Clear;
  for pbobj in APB_QueryTableStatsList do
    Add(TPB_QueryTableStats.Create(pbobj, TRUE));
end;

end.
