// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.UserChangeParams;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,
  Poker.Protobufs.Objects.User;

type
  TPB_UserChangeParams = class(TProtobufBaseObject)
  private
    const
      kUsersFieldNumber = 1;

    var
      FUsers: TList<TPB_User>;
      _has_bits_: UINT32;

    procedure set_has_Users;
    procedure clear_has_Users;
    procedure UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_UserChangeParams; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_UserChangeParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated User Users = 1;
    function has_Users: Boolean;
    procedure clear_Users;
    property Users: TList<TPB_User> read FUsers;

  end;
  TPB_UserChangeParamsList = class (TObjectList<TPB_UserChangeParams>)
    procedure Assign(const APB_UserChangeParamsList: TList<TPB_UserChangeParams>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_UserChangeParams.InitObjects;
begin
  inherited;
  FUsers := TObjectList<TPB_User>.Create;
end;

procedure TPB_UserChangeParams.HookNotifiers;
begin
  inherited;
  FUsers.OnNotify := UsersNotifyEvent;
end;

constructor TPB_UserChangeParams.Create(const AFrom: TPB_UserChangeParams; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_UserChangeParams.Destroy;
begin
  if Assigned(FUsers) then
  begin
    FUsers.OnNotify := nil;
    FreeAndNil(FUsers);
  end;
  inherited;
end;

procedure TPB_UserChangeParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kUsersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32, Lightweight));
        set_has_Users;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_UserChangeParams.MergeFrom(const AFrom: TPB_UserChangeParams);
var
  pbobj0: TPB_User;
begin
  for pbobj0 in AFrom.Users do
    FUsers.Add(TPB_User.Create(pbobj0));
end;

function TPB_UserChangeParams.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $0) <> $0 then
    Exit(FALSE);
  for pbobj in Users do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_UserChangeParams.clear_Users;
begin
  FUsers.Clear;
  clear_has_Users;
end;

function TPB_UserChangeParams.has_Users: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_UserChangeParams.set_has_Users;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_UserChangeParams.clear_has_Users;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_UserChangeParams.UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Users;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kUsersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_UserChangeParams.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Users;
end;

procedure TPB_UserChangeParamsList.Assign(const APB_UserChangeParamsList: TList<TPB_UserChangeParams>);
var
  pbobj: TPB_UserChangeParams;
begin
  Clear;
  for pbobj in APB_UserChangeParamsList do
    Add(TPB_UserChangeParams.Create(pbobj, TRUE));
end;

end.
