// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.PingParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_PingParams = class(TProtobufBaseObject)
  private
    const
      FN_UPTIME = 1;

    var
      FUptime: UINT32;

    procedure SetUptime(const AValue: UINT32);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Uptime: UINT32 read FUptime write SetUptime;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_PingParams.Destroy;
begin
  inherited;
end;

procedure TPB_PingParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_UPTIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FUptime := AProtobufReader.readUInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_PingParams.SetUptime(const AValue: UINT32);
begin
  FUptime := AValue;
  ProtobufOutput.writeUInt32(FN_UPTIME, AValue);
end;

end.
