// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.WinnerPotInfo;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.WinnerData;

type
  TPB_WinnerPotInfo = class(TProtobufBaseObject)
  private
    const
      FN_SUM = 1;
      FN_SEATS = 2;
      FN_WINNERDATA = 3;
      FN_RAKE = 4;

    var
      FSum: UINT32;
      FSeats: TArray<UINT32>;
      FWinnerData: TObjectList<TPB_WinnerData>;
      FRake: UINT32;

    procedure SetSum(const AValue: UINT32);
    procedure SetSeats(const AValue: TArray<UINT32>);
    procedure SetRake(const AValue: UINT32);
    procedure WinnerDataNotifyEvent(Sender: TObject; const Item: TPB_WinnerData; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Sum: UINT32 read FSum write SetSum;
    property Seats: TArray<UINT32> read FSeats write SetSeats;
    property WinnerData: TObjectList<TPB_WinnerData> read FWinnerData;
    property Rake: UINT32 read FRake write SetRake;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_WinnerPotInfo.InitObjects;
begin
  FWinnerData := TObjectList<TPB_WinnerData>.Create;
  FWinnerData.OnNotify := WinnerDataNotifyEvent;
end;

destructor TPB_WinnerPotInfo.Destroy;
begin
  if Assigned(FWinnerData) then
  begin
    FWinnerData.OnNotify := nil;
    FreeAndNil(FWinnerData);
  end;
  inherited;
end;

procedure TPB_WinnerPotInfo.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_SUM: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSum := AProtobufReader.readUInt32;
      end;
      FN_SEATS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        SetLength(FSeats, Length(FSeats) + 1);
        FSeats[Length(FSeats)-1] := AProtobufReader.readUInt32;
      end;
      FN_WINNERDATA: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FWinnerData.Add(TPB_WinnerData.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_RAKE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FRake := AProtobufReader.readUInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_WinnerPotInfo.SetSum(const AValue: UINT32);
begin
  FSum := AValue;
  ProtobufOutput.writeUInt32(FN_SUM, AValue);
end;

procedure TPB_WinnerPotInfo.SetSeats(const AValue: TArray<UINT32>);
var
  C1: Integer;
begin
  FSeats := AValue;
  for C1 := 0 to Length(FSeats) - 1 do
    ProtobufOutput.writeUInt32(FN_SEATS, AValue[C1]);
end;

procedure TPB_WinnerPotInfo.WinnerDataNotifyEvent(Sender: TObject; const Item: TPB_WinnerData; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_WINNERDATA,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_WinnerPotInfo.SetRake(const AValue: UINT32);
begin
  FRake := AValue;
  ProtobufOutput.writeUInt32(FN_RAKE, AValue);
end;

end.
