// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.QueryTableStats;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_QueryTableStats = class(TProtobufBaseObject)
  private
    const
      FN_GAMEID = 1;

    var
      FGameid: TArray<TBytes>;

    procedure SetGameid(const AValue: TArray<TBytes>);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Gameid: TArray<TBytes> read FGameid write SetGameid;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_QueryTableStats.Destroy;
begin
  inherited;
end;

procedure TPB_QueryTableStats.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_GAMEID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        SetLength(FGameid, Length(FGameid) + 1);
        AProtobufReader.readBytes(FGameid[Length(FGameid)-1]);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_QueryTableStats.SetGameid(const AValue: TArray<TBytes>);
var
  C1: Integer;
begin
  FGameid := AValue;
  for C1 := 0 to Length(FGameid) - 1 do
    ProtobufOutput.writeBytes(FN_GAMEID, AValue[C1]);
end;

end.
