// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.TableStatsReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.TablePlayerStats;

type
  TPB_TableStatsReply = class(TProtobufBaseObject)
  private
    const
      FN_CLUBID = 1;
      FN_GAMEID = 2;
      FN_PLAYERSTATS = 3;

    var
      FClubid: TBytes;
      FGameid: TBytes;
      FPlayerstats: TObjectList<TPB_TablePlayerStats>;

    procedure SetClubid(const AValue: TBytes);
    procedure SetGameid(const AValue: TBytes);
    procedure PlayerstatsNotifyEvent(Sender: TObject; const Item: TPB_TablePlayerStats; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Clubid: TBytes read FClubid write SetClubid;
    property Gameid: TBytes read FGameid write SetGameid;
    property Playerstats: TObjectList<TPB_TablePlayerStats> read FPlayerstats;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_TableStatsReply.InitObjects;
begin
  FPlayerstats := TObjectList<TPB_TablePlayerStats>.Create;
  FPlayerstats.OnNotify := PlayerstatsNotifyEvent;
end;

destructor TPB_TableStatsReply.Destroy;
begin
  if Assigned(FPlayerstats) then
  begin
    FPlayerstats.OnNotify := nil;
    FreeAndNil(FPlayerstats);
  end;
  inherited;
end;

procedure TPB_TableStatsReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_CLUBID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FClubid);
      end;
      FN_GAMEID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FGameid);
      end;
      FN_PLAYERSTATS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerstats.Add(TPB_TablePlayerStats.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_TableStatsReply.SetClubid(const AValue: TBytes);
begin
  FClubid := AValue;
  ProtobufOutput.writeBytes(FN_CLUBID, AValue);
end;

procedure TPB_TableStatsReply.SetGameid(const AValue: TBytes);
begin
  FGameid := AValue;
  ProtobufOutput.writeBytes(FN_GAMEID, AValue);
end;

procedure TPB_TableStatsReply.PlayerstatsNotifyEvent(Sender: TObject; const Item: TPB_TablePlayerStats; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_PLAYERSTATS,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
