// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.PlayerHandHistory;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.SeatInfo;

type
  TPB_PlayerHandHistory = class(TProtobufBaseObject)
  private
    const
      FN__ID = 1;
      FN_SEAT = 2;
      FN_CARDS = 3;
      FN_CHIPS = 4;
      FN_NICK = 5;
      FN_MUCK = 6;
      FN_STATUS = 7;

    var
      FId: TBytes;
      FSeat: Integer;
      FCards: TBytes;
      FChips: UINT32;
      FNick: String;
      FMuck: Boolean;
      FStatus: TPlayerStatus;

    procedure SetMongoId(const AValue: TBytes);
    procedure SetSeat(const AValue: Integer);
    procedure SetCards(const AValue: TBytes);
    procedure SetChips(const AValue: UINT32);
    procedure SetNick(const AValue: String);
    procedure SetMuck(const AValue: Boolean);
    procedure SetStatus(const AValue: TPlayerStatus);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property MongoId: TBytes read FId write SetMongoId;
    property Seat: Integer read FSeat write SetSeat;
    property Cards: TBytes read FCards write SetCards;
    property Chips: UINT32 read FChips write SetChips;
    property Nick: String read FNick write SetNick;
    property Muck: Boolean read FMuck write SetMuck;
    property Status: TPlayerStatus read FStatus write SetStatus;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_PlayerHandHistory.Destroy;
begin
  inherited;
end;

procedure TPB_PlayerHandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN__ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FId);
      end;
      FN_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readInt32;
      end;
      FN_CARDS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FCards);
      end;
      FN_CHIPS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChips := AProtobufReader.readUInt32;
      end;
      FN_NICK: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FNick := AProtobufReader.readUtf8String;
      end;
      FN_MUCK: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMuck := AProtobufReader.readBoolean;
      end;
      FN_STATUS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FStatus := TPlayerStatus(AProtobufReader.readEnum);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_PlayerHandHistory.SetMongoId(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FId,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FId[C1] := AValue[C1];
  ProtobufOutput.writeBytes(FN__ID, AValue);
end;

procedure TPB_PlayerHandHistory.SetSeat(const AValue: Integer);
begin
  FSeat := AValue;
  ProtobufOutput.writeInt32(FN_SEAT, AValue);
end;

procedure TPB_PlayerHandHistory.SetCards(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FCards,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FCards[C1] := AValue[C1];
  ProtobufOutput.writeBytes(FN_CARDS, AValue);
end;

procedure TPB_PlayerHandHistory.SetChips(const AValue: UINT32);
begin
  FChips := AValue;
  ProtobufOutput.writeUInt32(FN_CHIPS, AValue);
end;

procedure TPB_PlayerHandHistory.SetNick(const AValue: String);
begin
  FNick := AValue;
  ProtobufOutput.writeString(FN_NICK, AValue);
end;

procedure TPB_PlayerHandHistory.SetMuck(const AValue: Boolean);
begin
  FMuck := AValue;
  ProtobufOutput.writeBoolean(FN_MUCK, AValue);
end;

procedure TPB_PlayerHandHistory.SetStatus(const AValue: TPlayerStatus);
begin
  FStatus := AValue;
  ProtobufOutput.writeInt32(FN_STATUS, Integer(AValue));
end;

end.
