// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.PingParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_PingParams = class(TProtobufBaseObject)
  private
    const
      kUptimeFieldNumber = 1;

    var
      FUptime: UINT32;
      _has_bits_: Integer;

    procedure set_has_Uptime;
    procedure clear_has_Uptime;
    procedure SetUptime(const AValue: UINT32);

  public
    constructor Create(const AFrom: TPB_PingParams); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_PingParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required uint32 Uptime = 1;
    function has_Uptime: Boolean;
    procedure clear_Uptime;
    property Uptime: UINT32 read FUptime write SetUptime;

  end;
  TPB_PingParamsList = class (TObjectList<TPB_PingParams>)
    procedure Assign(const APB_PingParamsList: TList<TPB_PingParams>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



constructor TPB_PingParams.Create(const AFrom: TPB_PingParams);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_PingParams.Destroy;
begin
  inherited;
end;

procedure TPB_PingParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kUptimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FUptime := AProtobufReader.readUInt32;
        set_has_Uptime;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_PingParams.MergeFrom(const from: TPB_PingParams);
begin
  if (from.has_Uptime) then
    SetUptime(from.Uptime);
end;

function TPB_PingParams.IsInitialized: Boolean;
begin
  if ((_has_bits_ and $1) <> $1) Then Exit(false);
  Exit(True);
end;

procedure TPB_PingParams.clear_Uptime;
begin
  FUptime := 0;
  clear_has_Uptime;
end;

function TPB_PingParams.has_Uptime: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_PingParams.set_has_Uptime;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_PingParams.clear_has_Uptime;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_PingParams.SetUptime(const AValue: UINT32);
begin
  Assert(not has_Uptime);
  FUptime := AValue;
  ProtobufOutput.writeUInt32(kUptimeFieldNumber, AValue);
  set_has_Uptime;
end;

procedure TPB_PingParamsList.Assign(const APB_PingParamsList: TList<TPB_PingParams>);
var
  pbobj: TPB_PingParams;
begin
  Clear;
  for pbobj in APB_PingParamsList do
    Add(TPB_PingParams.Create(pbobj));
end;

procedure TPB_PingParams.Clear;
begin
  if (_has_bits_ <> 0) then
  begin
    clear_Uptime;
  end;
end;

end.
