// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.Game;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TGameLimit = (glNoLimit = 0,glPotLimit = 1,glFixedLimit = 2);
  TGameType = (gtHoldem = 0,gtOmaha = 1);
  TGameState = (gsActive = 1,gsClosing = 2,gsClosed = 3,gsEmpty = 4);
  TPB_Game = class(TProtobufBaseObject)
  private
    const
      FN__ID = 1;
      FN_CREATOR_MONGO_ID = 2;
      FN_GAMENAME = 3;
      FN_CLUBSEQ = 4;
      FN_GAME_TYPE = 5;
      FN_GAME_LIMIT = 6;
      FN_SMALL_BLIND = 7;
      FN_BIG_BLIND = 8;
      FN_SEATS = 9;
      FN_SITTING = 10;
      FN_BUYIN_MIN = 11;
      FN_BUYIN_MAX = 12;
      FN_STATE = 13;
      FN_CLOSETIME = 14;

    var
      FId: TBytes;
      FCreatorMongoId: TBytes;
      FGamename: String;
      FClubseq: Integer;
      FGameType: TGameType;
      FGameLimit: TGameLimit;
      FSmallBlind: UINT32;
      FBigBlind: UINT32;
      FSeats: Integer;
      FSitting: Integer;
      FBuyinMin: Integer;
      FBuyinMax: Integer;
      FState: TGameState;
      FClosetime: UInt64;

    procedure SetMongoId(const AValue: TBytes);
    procedure SetCreatorMongoId(const AValue: TBytes);
    procedure SetGamename(const AValue: String);
    procedure SetClubseq(const AValue: Integer);
    procedure SetGameType(const AValue: TGameType);
    procedure SetGameLimit(const AValue: TGameLimit);
    procedure SetSmallBlind(const AValue: UINT32);
    procedure SetBigBlind(const AValue: UINT32);
    procedure SetSeats(const AValue: Integer);
    procedure SetSitting(const AValue: Integer);
    procedure SetBuyinMin(const AValue: Integer);
    procedure SetBuyinMax(const AValue: Integer);
    procedure SetState(const AValue: TGameState);
    procedure SetClosetime(const AValue: UInt64);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property MongoId: TBytes read FId write SetMongoId;
    property CreatorMongoId: TBytes read FCreatorMongoId write SetCreatorMongoId;
    property Gamename: String read FGamename write SetGamename;
    property Clubseq: Integer read FClubseq write SetClubseq;
    property GameType: TGameType read FGameType write SetGameType;
    property GameLimit: TGameLimit read FGameLimit write SetGameLimit;
    property SmallBlind: UINT32 read FSmallBlind write SetSmallBlind;
    property BigBlind: UINT32 read FBigBlind write SetBigBlind;
    property Seats: Integer read FSeats write SetSeats;
    property Sitting: Integer read FSitting write SetSitting;
    property BuyinMin: Integer read FBuyinMin write SetBuyinMin;
    property BuyinMax: Integer read FBuyinMax write SetBuyinMax;
    property State: TGameState read FState write SetState;
    property Closetime: UInt64 read FClosetime write SetClosetime;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_Game.Destroy;
begin
  inherited;
end;
procedure TPB_Game.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN__ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FId);
      end;
      FN_CREATOR_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FCreatorMongoId);
      end;
      FN_GAMENAME: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGamename := AProtobufReader.readUtf8String;
      end;
      FN_CLUBSEQ: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FClubseq := AProtobufReader.readInt32;
      end;
      FN_GAME_TYPE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FGameType := TGameType(AProtobufReader.readEnum);
      end;
      FN_GAME_LIMIT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FGameLimit := TGameLimit(AProtobufReader.readEnum);
      end;
      FN_SMALL_BLIND: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSmallBlind := AProtobufReader.readUInt32;
      end;
      FN_BIG_BLIND: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBigBlind := AProtobufReader.readUInt32;
      end;
      FN_SEATS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeats := AProtobufReader.readInt32;
      end;
      FN_SITTING: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSitting := AProtobufReader.readInt32;
      end;
      FN_BUYIN_MIN: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBuyinMin := AProtobufReader.readInt32;
      end;
      FN_BUYIN_MAX: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBuyinMax := AProtobufReader.readInt32;
      end;
      FN_STATE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FState := TGameState(AProtobufReader.readEnum);
      end;
      FN_CLOSETIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FClosetime := AProtobufReader.readInt64;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_Game.SetMongoId(const AValue: TBytes);
begin
  FId := AValue;
  ProtobufOutput.writeBytes(FN__ID, AValue);
end;

procedure TPB_Game.SetCreatorMongoId(const AValue: TBytes);
begin
  FCreatorMongoId := AValue;
  ProtobufOutput.writeBytes(FN_CREATOR_MONGO_ID, AValue);
end;

procedure TPB_Game.SetGamename(const AValue: String);
begin
  FGamename := AValue;
  ProtobufOutput.writeString(FN_GAMENAME, AValue);
end;

procedure TPB_Game.SetClubseq(const AValue: Integer);
begin
  FClubseq := AValue;
  ProtobufOutput.writeInt32(FN_CLUBSEQ, AValue);
end;

procedure TPB_Game.SetGameType(const AValue: TGameType);
begin
  FGameType := AValue;
  ProtobufOutput.writeInt32(FN_GAME_TYPE, Integer(AValue));
end;

procedure TPB_Game.SetGameLimit(const AValue: TGameLimit);
begin
  FGameLimit := AValue;
  ProtobufOutput.writeInt32(FN_GAME_LIMIT, Integer(AValue));
end;

procedure TPB_Game.SetSmallBlind(const AValue: UINT32);
begin
  FSmallBlind := AValue;
  ProtobufOutput.writeUInt32(FN_SMALL_BLIND, AValue);
end;

procedure TPB_Game.SetBigBlind(const AValue: UINT32);
begin
  FBigBlind := AValue;
  ProtobufOutput.writeUInt32(FN_BIG_BLIND, AValue);
end;

procedure TPB_Game.SetSeats(const AValue: Integer);
begin
  FSeats := AValue;
  ProtobufOutput.writeInt32(FN_SEATS, AValue);
end;

procedure TPB_Game.SetSitting(const AValue: Integer);
begin
  FSitting := AValue;
  ProtobufOutput.writeInt32(FN_SITTING, AValue);
end;

procedure TPB_Game.SetBuyinMin(const AValue: Integer);
begin
  FBuyinMin := AValue;
  ProtobufOutput.writeInt32(FN_BUYIN_MIN, AValue);
end;

procedure TPB_Game.SetBuyinMax(const AValue: Integer);
begin
  FBuyinMax := AValue;
  ProtobufOutput.writeInt32(FN_BUYIN_MAX, AValue);
end;

procedure TPB_Game.SetState(const AValue: TGameState);
begin
  FState := AValue;
  ProtobufOutput.writeInt32(FN_STATE, Integer(AValue));
end;

procedure TPB_Game.SetClosetime(const AValue: UInt64);
begin
  FClosetime := AValue;
  ProtobufOutput.WriteInt64(FN_CLOSETIME, AValue);
end;

end.
