// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.ClubPlayerStats;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_ClubPlayerStats = class(TProtobufBaseObject)
  private
    const
      FN_USERID = 1;
      FN_CLUB_BALANCE = 2;

    var
      FUserid: TBytes;
      FClubBalance: Integer;

    procedure SetUserid(const AValue: TBytes);
    procedure SetClubBalance(const AValue: Integer);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Userid: TBytes read FUserid write SetUserid;
    property ClubBalance: Integer read FClubBalance write SetClubBalance;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_ClubPlayerStats.Destroy;
begin
  inherited;
end;

procedure TPB_ClubPlayerStats.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_USERID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FUserid);
      end;
      FN_CLUB_BALANCE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FClubBalance := AProtobufReader.readInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_ClubPlayerStats.SetUserid(const AValue: TBytes);
begin
  FUserid := AValue;
  ProtobufOutput.writeBytes(FN_USERID, AValue);
end;

procedure TPB_ClubPlayerStats.SetClubBalance(const AValue: Integer);
begin
  FClubBalance := AValue;
  ProtobufOutput.writeInt32(FN_CLUB_BALANCE, AValue);
end;

end.
