// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.GetUserParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.User;

type
  TPB_GetUserParams = class(TProtobufBaseObject)
  private
    const
      kUserMongoIdsFieldNumber = 1;
      kUsersFieldNumber = 2;

    var
      FUserMongoIds: TList<TBytes>;
      FUsers: TList<TPB_User>;
      _has_bits_: Integer;

    procedure set_has_UserMongoIds;
    procedure clear_has_UserMongoIds;
    procedure set_has_Users;
    procedure clear_has_Users;
    procedure UserMongoIdsNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);
    procedure UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_GetUserParams); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_GetUserParams);

    // LABEL TYPE UserMongoIds = 1;
    function has_UserMongoIds: Boolean;
    procedure clear_UserMongoIds;
    property UserMongoIds: TList<TBytes> read FUserMongoIds;

    // LABEL TYPE Users = 2;
    function has_Users: Boolean;
    procedure clear_Users;
    property Users: TList<TPB_User> read FUsers;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_GetUserParams.InitObjects;
begin
  inherited;
  FUserMongoIds := TList<TBytes>.Create;
  FUsers := TObjectList<TPB_User>.Create;
end;
procedure TPB_GetUserParams.HookNotifiers;
begin
  inherited;
  FUserMongoIds.OnNotify := UserMongoIdsNotifyEvent;
  FUsers.OnNotify := UsersNotifyEvent;
end;

constructor TPB_GetUserParams.Create(const AFrom: TPB_GetUserParams);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_GetUserParams.Destroy;
begin
  if Assigned(FUserMongoIds) then
  begin
    FUserMongoIds.OnNotify := nil;
    FreeAndNil(FUserMongoIds);
  end;
  if Assigned(FUsers) then
  begin
    FUsers.OnNotify := nil;
    FreeAndNil(FUsers);
  end;
  inherited;
end;

procedure TPB_GetUserParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
  cheating: TBytes;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kUserMongoIdsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(cheating);
        FUserMongoIds.Add(cheating);
      end;
      kUsersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Users;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_GetUserParams.MergeFrom(const from: TPB_GetUserParams);
var
  temp0: TBytes;
  temp1: TPB_User;
begin
  for temp0 in from.UserMongoIds do
    FUserMongoIds.Add(temp0); // FIXME?
  for temp1 in from.Users do
    FUsers.Add(TPB_User.Create(temp1));
end;

procedure TPB_GetUserParams.clear_UserMongoIds;
begin
  FUserMongoIds.Clear;
  clear_has_UserMongoIds;
end;

function TPB_GetUserParams.has_UserMongoIds: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_GetUserParams.set_has_UserMongoIds;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_GetUserParams.clear_has_UserMongoIds;
begin
  _has_bits_ := _has_bits_ xor 1;
end;

procedure TPB_GetUserParams.UserMongoIdsNotifyEvent(Sender: TObject; const Item: TBytes; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
end;

procedure TPB_GetUserParams.clear_Users;
begin
  FUsers.Clear;
  clear_has_Users;
end;

function TPB_GetUserParams.has_Users: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_GetUserParams.set_has_Users;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_GetUserParams.clear_has_Users;
begin
  _has_bits_ := _has_bits_ xor 2;
end;

procedure TPB_GetUserParams.UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kUsersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
