// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.GiveClubOwnershipParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_GiveClubOwnershipParams = class(TProtobufBaseObject)
  private
    const
      kClubMongoIdFieldNumber = 1;
      kPlayerMongoIdFieldNumber = 2;

    var
      FClubMongoId: TBytes;
      FPlayerMongoId: TBytes;
      _has_bits_: Integer;

    procedure set_has_ClubMongoId;
    procedure clear_has_ClubMongoId;
    procedure SetClubMongoId(const AValue: TBytes);
    procedure set_has_PlayerMongoId;
    procedure clear_has_PlayerMongoId;
    procedure SetPlayerMongoId(const AValue: TBytes);

  public
    constructor Create(const AFrom: TPB_GiveClubOwnershipParams; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_GiveClubOwnershipParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes ClubMongoId = 1;
    function has_ClubMongoId: Boolean;
    procedure clear_ClubMongoId;
    property ClubMongoId: TBytes read FClubMongoId write SetClubMongoId;

    // required bytes PlayerMongoId = 2;
    function has_PlayerMongoId: Boolean;
    procedure clear_PlayerMongoId;
    property PlayerMongoId: TBytes read FPlayerMongoId write SetPlayerMongoId;

  end;
  TPB_GiveClubOwnershipParamsList = class (TObjectList<TPB_GiveClubOwnershipParams>)
    procedure Assign(const APB_GiveClubOwnershipParamsList: TList<TPB_GiveClubOwnershipParams>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



constructor TPB_GiveClubOwnershipParams.Create(const AFrom: TPB_GiveClubOwnershipParams; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_GiveClubOwnershipParams.Destroy;
begin
  inherited;
end;

procedure TPB_GiveClubOwnershipParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kClubMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubMongoId := AProtobufReader.readBytes;
        set_has_ClubMongoId;
      end;
      kPlayerMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerMongoId := AProtobufReader.readBytes;
        set_has_PlayerMongoId;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_GiveClubOwnershipParams.MergeFrom(const from: TPB_GiveClubOwnershipParams);
begin
  if (from.has_ClubMongoId) then
    SetClubMongoId(from.ClubMongoId);
  if (from.has_PlayerMongoId) then
    SetPlayerMongoId(from.PlayerMongoId);
end;

function TPB_GiveClubOwnershipParams.IsInitialized: Boolean;
begin
  if ((_has_bits_ and $3) <> $3) Then Exit(false);
  Exit(True);
end;

procedure TPB_GiveClubOwnershipParams.clear_ClubMongoId;
begin
  SetLength(FClubMongoId,0);
  clear_has_ClubMongoId;
end;

function TPB_GiveClubOwnershipParams.has_ClubMongoId: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_GiveClubOwnershipParams.set_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_GiveClubOwnershipParams.clear_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_GiveClubOwnershipParams.SetClubMongoId(const AValue: TBytes);
begin
  Assert(not has_ClubMongoId);
  FClubMongoId := Copy(AValue,0,Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kClubMongoIdFieldNumber, AValue);
  set_has_ClubMongoId;
end;

procedure TPB_GiveClubOwnershipParams.clear_PlayerMongoId;
begin
  SetLength(FPlayerMongoId,0);
  clear_has_PlayerMongoId;
end;

function TPB_GiveClubOwnershipParams.has_PlayerMongoId: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_GiveClubOwnershipParams.set_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_GiveClubOwnershipParams.clear_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_GiveClubOwnershipParams.SetPlayerMongoId(const AValue: TBytes);
begin
  Assert(not has_PlayerMongoId);
  FPlayerMongoId := Copy(AValue,0,Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kPlayerMongoIdFieldNumber, AValue);
  set_has_PlayerMongoId;
end;

procedure TPB_GiveClubOwnershipParamsList.Assign(const APB_GiveClubOwnershipParamsList: TList<TPB_GiveClubOwnershipParams>);
var
  pbobj: TPB_GiveClubOwnershipParams;
begin
  Clear;
  for pbobj in APB_GiveClubOwnershipParamsList do
    Add(TPB_GiveClubOwnershipParams.Create(pbobj, TRUE));
end;

procedure TPB_GiveClubOwnershipParams.Clear;
begin
  if (_has_bits_ <> 0) then
  begin
    clear_ClubMongoId;
    clear_PlayerMongoId;
  end;
end;

end.
