// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.KickPlayerParams;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types;

type
  TPB_KickPlayerParams = class(TProtobufBaseObject)
  private
    const
      kClubMongoIdFieldNumber = 1;
      kPlayerMongoIdFieldNumber = 2;

    var
      FClubMongoId: TMongoId;
      FPlayerMongoId: TMongoId;
      _has_bits_: UINT32;

    procedure set_has_ClubMongoId;
    procedure clear_has_ClubMongoId;
    procedure SetClubMongoId(const AValue: TMongoId);
    procedure set_has_PlayerMongoId;
    procedure clear_has_PlayerMongoId;
    procedure SetPlayerMongoId(const AValue: TMongoId);

  public
    constructor Create(const AFrom: TPB_KickPlayerParams; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_KickPlayerParams);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes ClubMongoId = 1;
    function has_ClubMongoId: Boolean;
    procedure clear_ClubMongoId;
    property ClubMongoId: TMongoId read FClubMongoId write SetClubMongoId;

    // required bytes PlayerMongoId = 2;
    function has_PlayerMongoId: Boolean;
    procedure clear_PlayerMongoId;
    property PlayerMongoId: TMongoId read FPlayerMongoId write SetPlayerMongoId;

  end;

  TPB_KickPlayerParamsList = class(TObjectList<TPB_KickPlayerParams>)
    procedure Assign(const APB_KickPlayerParamsList: TList<TPB_KickPlayerParams>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_KickPlayerParams.Create(const AFrom: TPB_KickPlayerParams; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_KickPlayerParams.Destroy;
begin
  inherited;
end;

procedure TPB_KickPlayerParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kClubMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubMongoId := AProtobufReader.readMongoId;
        set_has_ClubMongoId;
      end;
      kPlayerMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerMongoId := AProtobufReader.readMongoId;
        set_has_PlayerMongoId;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_KickPlayerParams.MergeFrom(const AFrom: TPB_KickPlayerParams);
begin
  if AFrom.has_ClubMongoId then
    SetClubMongoId(AFrom.ClubMongoId);
  if AFrom.has_PlayerMongoId then
    SetPlayerMongoId(AFrom.PlayerMongoId);
end;

function TPB_KickPlayerParams.IsInitialized: Boolean;
begin
  if (_has_bits_ and $3) <> $3 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_KickPlayerParams.clear_ClubMongoId;
begin
  FClubMongoId.Clear;
  clear_has_ClubMongoId;
end;

function TPB_KickPlayerParams.has_ClubMongoId: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_KickPlayerParams.set_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_KickPlayerParams.clear_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_KickPlayerParams.SetClubMongoId(const AValue: TMongoId);
begin
  Assert(not has_ClubMongoId);
  FClubMongoId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kClubMongoIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_ClubMongoId;
end;

procedure TPB_KickPlayerParams.clear_PlayerMongoId;
begin
  FPlayerMongoId.Clear;
  clear_has_PlayerMongoId;
end;

function TPB_KickPlayerParams.has_PlayerMongoId: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_KickPlayerParams.set_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_KickPlayerParams.clear_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_KickPlayerParams.SetPlayerMongoId(const AValue: TMongoId);
begin
  Assert(not has_PlayerMongoId);
  FPlayerMongoId := AValue;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPlayerMongoIdFieldNumber, WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(12);
    ProtobufOutput.writeRawData(AValue.Memory, 12);
  end;
  set_has_PlayerMongoId;
end;

procedure TPB_KickPlayerParams.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_ClubMongoId;
  clear_PlayerMongoId;
end;

procedure TPB_KickPlayerParamsList.Assign(const APB_KickPlayerParamsList: TList<TPB_KickPlayerParams>);
var
  pbobj: TPB_KickPlayerParams;
begin
  Clear;
  for pbobj in APB_KickPlayerParamsList do
    Add(TPB_KickPlayerParams.Create(pbobj, TRUE));
end;

end.
