// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.ChangeSuspendState;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_ChangeSuspendState = class(TProtobufBaseObject)
  private
    const
      kClubMongoIdFieldNumber = 1;
      kPlayerMongoIdFieldNumber = 3;
      kSuspendedFieldNumber = 2;

    var
      FClubMongoId: TBytes;
      FPlayerMongoId: TBytes;
      FSuspended: Boolean;
      _has_bits_: UINT32;

    procedure set_has_ClubMongoId;
    procedure clear_has_ClubMongoId;
    procedure SetClubMongoId(const AValue: TBytes);
    procedure set_has_PlayerMongoId;
    procedure clear_has_PlayerMongoId;
    procedure SetPlayerMongoId(const AValue: TBytes);
    procedure set_has_Suspended;
    procedure clear_has_Suspended;
    procedure SetSuspended(const AValue: Boolean);

  public
    constructor Create(const AFrom: TPB_ChangeSuspendState; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_ChangeSuspendState);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes ClubMongoId = 1;
    function has_ClubMongoId: Boolean;
    procedure clear_ClubMongoId;
    property ClubMongoId: TBytes read FClubMongoId write SetClubMongoId;

    // required bytes PlayerMongoId = 3;
    function has_PlayerMongoId: Boolean;
    procedure clear_PlayerMongoId;
    property PlayerMongoId: TBytes read FPlayerMongoId write SetPlayerMongoId;

    // required bool Suspended = 2;
    function has_Suspended: Boolean;
    procedure clear_Suspended;
    property Suspended: Boolean read FSuspended write SetSuspended;

  end;

  TPB_ChangeSuspendStateList = class(TObjectList<TPB_ChangeSuspendState>)
    procedure Assign(const APB_ChangeSuspendStateList: TList<TPB_ChangeSuspendState>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_ChangeSuspendState.Create(const AFrom: TPB_ChangeSuspendState; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_ChangeSuspendState.Destroy;
begin
  inherited;
end;

procedure TPB_ChangeSuspendState.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kClubMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubMongoId := AProtobufReader.readBytes;
        set_has_ClubMongoId;
      end;
      kPlayerMongoIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayerMongoId := AProtobufReader.readBytes;
        set_has_PlayerMongoId;
      end;
      kSuspendedFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSuspended := AProtobufReader.readBoolean;
        set_has_Suspended;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_ChangeSuspendState.MergeFrom(const AFrom: TPB_ChangeSuspendState);
begin
  if AFrom.has_ClubMongoId then
    SetClubMongoId(AFrom.ClubMongoId);
  if AFrom.has_PlayerMongoId then
    SetPlayerMongoId(AFrom.PlayerMongoId);
  if AFrom.has_Suspended then
    SetSuspended(AFrom.Suspended);
end;

function TPB_ChangeSuspendState.IsInitialized: Boolean;
begin
  if (_has_bits_ and $7) <> $7 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_ChangeSuspendState.clear_ClubMongoId;
begin
  SetLength(FClubMongoId, 0);
  clear_has_ClubMongoId;
end;

function TPB_ChangeSuspendState.has_ClubMongoId: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_ChangeSuspendState.set_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_ChangeSuspendState.clear_has_ClubMongoId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_ChangeSuspendState.SetClubMongoId(const AValue: TBytes);
begin
  Assert(not has_ClubMongoId);
  FClubMongoId := Copy(AValue, 0, Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kClubMongoIdFieldNumber, AValue);
  set_has_ClubMongoId;
end;

procedure TPB_ChangeSuspendState.clear_PlayerMongoId;
begin
  SetLength(FPlayerMongoId, 0);
  clear_has_PlayerMongoId;
end;

function TPB_ChangeSuspendState.has_PlayerMongoId: Boolean;
begin
  result := (_has_bits_ and 4) > 0;
end;

procedure TPB_ChangeSuspendState.set_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_ChangeSuspendState.clear_has_PlayerMongoId;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_ChangeSuspendState.SetPlayerMongoId(const AValue: TBytes);
begin
  Assert(not has_PlayerMongoId);
  FPlayerMongoId := Copy(AValue, 0, Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kPlayerMongoIdFieldNumber, AValue);
  set_has_PlayerMongoId;
end;

procedure TPB_ChangeSuspendState.clear_Suspended;
begin
  FSuspended := false;
  clear_has_Suspended;
end;

function TPB_ChangeSuspendState.has_Suspended: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_ChangeSuspendState.set_has_Suspended;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_ChangeSuspendState.clear_has_Suspended;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_ChangeSuspendState.SetSuspended(const AValue: Boolean);
begin
  Assert(not has_Suspended);
  FSuspended := AValue;
  if not Lightweight then
    ProtobufOutput.writeBoolean(kSuspendedFieldNumber, AValue);
  set_has_Suspended;
end;

procedure TPB_ChangeSuspendState.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_ClubMongoId;
  clear_PlayerMongoId;
  clear_Suspended;
end;

procedure TPB_ChangeSuspendStateList.Assign(const APB_ChangeSuspendStateList: TList<TPB_ChangeSuspendState>);
var
  pbobj: TPB_ChangeSuspendState;
begin
  Clear;
  for pbobj in APB_ChangeSuspendStateList do
    Add(TPB_ChangeSuspendState.Create(pbobj, TRUE));
end;

end.
