// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.RegisterReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TRegisterStatus = (regSuccess = 0,regDuplicateEmail = 1,regDupUsername = 2,regInvalidEmail = 3,regInvalidName = 4);
  TPB_RegisterReply = class(TProtobufBaseObject)
  private
    const
      FN_STATUS = 1;

    var
      FStatus: TRegisterStatus;

    procedure SetStatus(const AValue: TRegisterStatus);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Status: TRegisterStatus read FStatus write SetStatus;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_RegisterReply.Destroy;
begin
  inherited;
end;
procedure TPB_RegisterReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_STATUS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FStatus := TRegisterStatus(AProtobufReader.readEnum);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_RegisterReply.SetStatus(const AValue: TRegisterStatus);
begin
  FStatus := AValue;
  ProtobufOutput.writeInt32(FN_STATUS, Integer(AValue));
end;

end.
