// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HelloParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.UpdateFileInfo;

type
  TPB_HelloParams = class(TProtobufBaseObject)
  private
    const
      FN_DEBUG = 1;
      FN_FILES = 2;

    var
      FDebug: Boolean;
      FFiles: TObjectList<TPB_UpdateFileInfo>;

    procedure SetDebug(const AValue: Boolean);
    procedure FilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Debug: Boolean read FDebug write SetDebug;
    property Files: TObjectList<TPB_UpdateFileInfo> read FFiles;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HelloParams.InitObjects;
begin
  inherited;
  FFiles := TObjectList<TPB_UpdateFileInfo>.Create;
end;
procedure TPB_HelloParams.HookNotifiers;
begin
  inherited;
  FFiles.OnNotify := FilesNotifyEvent;
end;

destructor TPB_HelloParams.Destroy;
begin
  if Assigned(FFiles) then
  begin
    FFiles.OnNotify := nil;
    FreeAndNil(FFiles);
  end;
  inherited;
end;

procedure TPB_HelloParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_DEBUG: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDebug := AProtobufReader.readBoolean;
      end;
      FN_FILES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FFiles.Add(TPB_UpdateFileInfo.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HelloParams.SetDebug(const AValue: Boolean);
begin
  FDebug := AValue;
  ProtobufOutput.writeBoolean(FN_DEBUG, AValue);
end;

procedure TPB_HelloParams.FilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_FILES,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
