// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.PutChips;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,
  Poker.Protobufs.Objects.TableStatus;

type
  TPB_PutChips = class(TProtobufBaseObject)
  private
    const
      FN_TABLE_MONGO_ID = 1;
      FN_CHIP_AMOUNT = 2;
      FN_CURRENT_STATE = 3;

    var
      FTableMongoId: TBytes;
      FChipAmount: UINT32;
      FCurrentState: TTableState;

    procedure SetTableMongoId(const AValue: TBytes);
    procedure SetChipAmount(const AValue: UINT32);
    procedure SetCurrentState(const AValue: TTableState);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property TableMongoId: TBytes read FTableMongoId write SetTableMongoId;
    property ChipAmount: UINT32 read FChipAmount write SetChipAmount;
    property CurrentState: TTableState read FCurrentState write SetCurrentState;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_PutChips.Destroy;
begin
  inherited;
end;

procedure TPB_PutChips.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_TABLE_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FTableMongoId);
      end;
      FN_CHIP_AMOUNT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChipAmount := AProtobufReader.readUInt32;
      end;
      FN_CURRENT_STATE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentState := TTableState(AProtobufReader.readEnum);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_PutChips.SetTableMongoId(const AValue: TBytes);
begin
  FTableMongoId := AValue;
  ProtobufOutput.writeBytes(FN_TABLE_MONGO_ID, AValue);
end;

procedure TPB_PutChips.SetChipAmount(const AValue: UINT32);
begin
  FChipAmount := AValue;
  ProtobufOutput.writeUInt32(FN_CHIP_AMOUNT, AValue);
end;

procedure TPB_PutChips.SetCurrentState(const AValue: TTableState);
begin
  FCurrentState := AValue;
  ProtobufOutput.writeInt32(FN_CURRENT_STATE, Integer(AValue));
end;

end.
