// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.BuyinError;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_BuyinError = class(TProtobufBaseObject)
  private
    const
      kGameIdFieldNumber = 1;
      kLastCashoutFieldNumber = 2;

    var
      FGameId: TBytes;
      FLastCashout: UINT32;
      _has_bits_: Integer;

    procedure set_has_GameId;
    procedure clear_has_GameId;
    procedure SetGameId(const AValue: TBytes);
    procedure set_has_LastCashout;
    procedure clear_has_LastCashout;
    procedure SetLastCashout(const AValue: UINT32);

  public
    constructor Create(const AFrom: TPB_BuyinError; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_BuyinError);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes GameId = 1;
    function has_GameId: Boolean;
    procedure clear_GameId;
    property GameId: TBytes read FGameId write SetGameId;

    // required uint32 LastCashout = 2;
    function has_LastCashout: Boolean;
    procedure clear_LastCashout;
    property LastCashout: UINT32 read FLastCashout write SetLastCashout;

  end;
  TPB_BuyinErrorList = class (TObjectList<TPB_BuyinError>)
    procedure Assign(const APB_BuyinErrorList: TList<TPB_BuyinError>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



constructor TPB_BuyinError.Create(const AFrom: TPB_BuyinError; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_BuyinError.Destroy;
begin
  inherited;
end;

procedure TPB_BuyinError.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kGameIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGameId := AProtobufReader.readBytes;
        set_has_GameId;
      end;
      kLastCashoutFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FLastCashout := AProtobufReader.readUInt32;
        set_has_LastCashout;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_BuyinError.MergeFrom(const from: TPB_BuyinError);
begin
  if (from.has_GameId) then
    SetGameId(from.GameId);
  if (from.has_LastCashout) then
    SetLastCashout(from.LastCashout);
end;

function TPB_BuyinError.IsInitialized: Boolean;
begin
  if ((_has_bits_ and $3) <> $3) Then Exit(false);
  Exit(True);
end;

procedure TPB_BuyinError.clear_GameId;
begin
  SetLength(FGameId,0);
  clear_has_GameId;
end;

function TPB_BuyinError.has_GameId: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_BuyinError.set_has_GameId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_BuyinError.clear_has_GameId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_BuyinError.SetGameId(const AValue: TBytes);
begin
  Assert(not has_GameId);
  FGameId := Copy(AValue,0,Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kGameIdFieldNumber, AValue);
  set_has_GameId;
end;

procedure TPB_BuyinError.clear_LastCashout;
begin
  FLastCashout := 0;
  clear_has_LastCashout;
end;

function TPB_BuyinError.has_LastCashout: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_BuyinError.set_has_LastCashout;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_BuyinError.clear_has_LastCashout;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_BuyinError.SetLastCashout(const AValue: UINT32);
begin
  Assert(not has_LastCashout);
  FLastCashout := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kLastCashoutFieldNumber, AValue);
  set_has_LastCashout;
end;

procedure TPB_BuyinErrorList.Assign(const APB_BuyinErrorList: TList<TPB_BuyinError>);
var
  pbobj: TPB_BuyinError;
begin
  Clear;
  for pbobj in APB_BuyinErrorList do
    Add(TPB_BuyinError.Create(pbobj, TRUE));
end;

procedure TPB_BuyinError.Clear;
begin
  if (_has_bits_ <> 0) then
  begin
    clear_GameId;
    clear_LastCashout;
  end;
end;

end.
