// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.BuyinError;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_BuyinError = class(TProtobufBaseObject)
  private
    const
      kGameIdFieldNumber = 1;
      kLastCashoutFieldNumber = 2;

    var
      FGameId: TBytes;
      FLastCashout: UInt32;
      _has_bits_: UINT32;

    procedure set_has_GameId;
    procedure clear_has_GameId;
    procedure SetGameId(const AValue: TBytes);
    procedure set_has_LastCashout;
    procedure clear_has_LastCashout;
    procedure SetLastCashout(const AValue: UInt32);

  public
    constructor Create(const AFrom: TPB_BuyinError; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_BuyinError);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes GameId = 1;
    function has_GameId: Boolean;
    procedure clear_GameId;
    property GameId: TBytes read FGameId write SetGameId;

    // required uint32 LastCashout = 2;
    function has_LastCashout: Boolean;
    procedure clear_LastCashout;
    property LastCashout: UInt32 read FLastCashout write SetLastCashout;

  end;

  TPB_BuyinErrorList = class(TObjectList<TPB_BuyinError>)
    procedure Assign(const APB_BuyinErrorList: TList<TPB_BuyinError>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_BuyinError.Create(const AFrom: TPB_BuyinError; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_BuyinError.Destroy;
begin
  inherited;
end;

procedure TPB_BuyinError.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kGameIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGameId := AProtobufReader.readBytes;
        set_has_GameId;
      end;
      kLastCashoutFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FLastCashout := AProtobufReader.readUInt32;
        set_has_LastCashout;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_BuyinError.MergeFrom(const AFrom: TPB_BuyinError);
begin
  if AFrom.has_GameId then
    SetGameId(AFrom.GameId);
  if AFrom.has_LastCashout then
    SetLastCashout(AFrom.LastCashout);
end;

function TPB_BuyinError.IsInitialized: Boolean;
begin
  if (_has_bits_ and $3) <> $3 then
    Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_BuyinError.clear_GameId;
begin
  SetLength(FGameId, 0);
  clear_has_GameId;
end;

function TPB_BuyinError.has_GameId: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_BuyinError.set_has_GameId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_BuyinError.clear_has_GameId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_BuyinError.SetGameId(const AValue: TBytes);
begin
  Assert(not has_GameId);
  FGameId := Copy(AValue, 0, Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kGameIdFieldNumber, AValue);
  set_has_GameId;
end;

procedure TPB_BuyinError.clear_LastCashout;
begin
  FLastCashout := 0;
  clear_has_LastCashout;
end;

function TPB_BuyinError.has_LastCashout: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_BuyinError.set_has_LastCashout;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_BuyinError.clear_has_LastCashout;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_BuyinError.SetLastCashout(const AValue: UInt32);
begin
  Assert(not has_LastCashout);
  FLastCashout := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kLastCashoutFieldNumber, AValue);
  set_has_LastCashout;
end;

procedure TPB_BuyinError.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_GameId;
  clear_LastCashout;
end;

procedure TPB_BuyinErrorList.Assign(const APB_BuyinErrorList: TList<TPB_BuyinError>);
var
  pbobj: TPB_BuyinError;
begin
  Clear;
  for pbobj in APB_BuyinErrorList do
    Add(TPB_BuyinError.Create(pbobj, TRUE));
end;

end.
