// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HandHistory;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.PlayerHandHistory,Poker.Protobufs.Objects.MoveRow,Poker.Protobufs.Objects.Game;

type
  TPB_HandHistory = class(TProtobufBaseObject)
  private
    const
      FN__ID = 1;
      FN_SEQ = 2;
      FN_TOTALRAKE = 3;
      FN_PLAYERS = 4;
      FN_CARDS = 5;
      FN_ENDTIME = 6;
      FN_BALANCE_CHANGES = 7;
      FN_MOVES = 8;
      FN_DEALER = 9;
      FN_GAME = 10;
      FN_CURRENT_GAME = 11;
      FN_RAKE = 12;

    var
      FId: TBytes;
      FSeq: UINT32;
      FTotalrake: UINT32;
      FPlayers: TObjectList<TPB_PlayerHandHistory>;
      FCards: TBytes;
      FEndtime: UINT32;
      FBalanceChanges: TArray<Integer>;
      FMoves: TObjectList<TPB_MoveRow>;
      FDealer: UINT32;
      FGame: TPB_Game;
      FCurrentGame: TGameType;
      FRake: Integer;

    procedure SetMongoId(const AValue: TBytes);
    procedure SetSeq(const AValue: UINT32);
    procedure SetTotalrake(const AValue: UINT32);
    procedure SetCards(const AValue: TBytes);
    procedure SetEndtime(const AValue: UINT32);
    procedure SetBalanceChanges(const AValue: TArray<Integer>);
    procedure SetDealer(const AValue: UINT32);
    procedure SetGame(const AValue: TPB_Game);
    procedure SetCurrentGame(const AValue: TGameType);
    procedure SetRake(const AValue: Integer);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
    procedure MovesNotifyEvent(Sender: TObject; const Item: TPB_MoveRow; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property MongoId: TBytes read FId write SetMongoId;
    property Seq: UINT32 read FSeq write SetSeq;
    property Totalrake: UINT32 read FTotalrake write SetTotalrake;
    property Players: TObjectList<TPB_PlayerHandHistory> read FPlayers;
    property Cards: TBytes read FCards write SetCards;
    property Endtime: UINT32 read FEndtime write SetEndtime;
    property BalanceChanges: TArray<Integer> read FBalanceChanges write SetBalanceChanges;
    property Moves: TObjectList<TPB_MoveRow> read FMoves;
    property Dealer: UINT32 read FDealer write SetDealer;
    property Game: TPB_Game read FGame write SetGame;
    property CurrentGame: TGameType read FCurrentGame write SetCurrentGame;
    property Rake: Integer read FRake write SetRake;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HandHistory.InitObjects;
begin
  FPlayers := TObjectList<TPB_PlayerHandHistory>.Create;
  FPlayers.OnNotify := PlayersNotifyEvent;
  FMoves := TObjectList<TPB_MoveRow>.Create;
  FMoves.OnNotify := MovesNotifyEvent;
end;

destructor TPB_HandHistory.Destroy;
begin
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  if Assigned(FMoves) then
  begin
    FMoves.OnNotify := nil;
    FreeAndNil(FMoves);
  end;
  if Assigned(FGame) then FreeAndNil(FGame);
  inherited;
end;

procedure TPB_HandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN__ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FId);
      end;
      FN_SEQ: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeq := AProtobufReader.readUInt32;
      end;
      FN_TOTALRAKE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FTotalrake := AProtobufReader.readUInt32;
      end;
      FN_PLAYERS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_PlayerHandHistory.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_CARDS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FCards);
      end;
      FN_ENDTIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEndtime := AProtobufReader.readUInt32;
      end;
      FN_BALANCE_CHANGES: begin
        Assert(wire_type = WIRETYPE_VARINT);
        SetLength(FBalanceChanges, Length(FBalanceChanges) + 1);
        FBalanceChanges[Length(FBalanceChanges)-1] := AProtobufReader.readInt32;
      end;
      FN_MOVES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FMoves.Add(TPB_MoveRow.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_DEALER: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDealer := AProtobufReader.readUInt32;
      end;
      FN_GAME: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FGame) then
          FGame := TPB_Game.Create;
        FGame.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
      end;
      FN_CURRENT_GAME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentGame := TGameType(AProtobufReader.readEnum);
      end;
      FN_RAKE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FRake := AProtobufReader.readInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HandHistory.SetMongoId(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FId,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FId[C1] := AValue[C1];
  ProtobufOutput.writeBytes(FN__ID, AValue);
end;

procedure TPB_HandHistory.SetSeq(const AValue: UINT32);
begin
  FSeq := AValue;
  ProtobufOutput.writeUInt32(FN_SEQ, AValue);
end;

procedure TPB_HandHistory.SetTotalrake(const AValue: UINT32);
begin
  FTotalrake := AValue;
  ProtobufOutput.writeUInt32(FN_TOTALRAKE, AValue);
end;

procedure TPB_HandHistory.PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_PLAYERS,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_HandHistory.SetCards(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FCards,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FCards[C1] := AValue[C1];
  ProtobufOutput.writeBytes(FN_CARDS, AValue);
end;

procedure TPB_HandHistory.SetEndtime(const AValue: UINT32);
begin
  FEndtime := AValue;
  ProtobufOutput.writeUInt32(FN_ENDTIME, AValue);
end;

procedure TPB_HandHistory.SetBalanceChanges(const AValue: TArray<Integer>);
var
  C1: Integer;
begin
  SetLength(FBalanceChanges,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FBalanceChanges[C1] := AValue[C1];
  for C1 := 0 to Length(FBalanceChanges) - 1 do
    ProtobufOutput.writeInt32(FN_BALANCE_CHANGES, AValue[C1]);
end;

procedure TPB_HandHistory.MovesNotifyEvent(Sender: TObject; const Item: TPB_MoveRow; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_MOVES,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_HandHistory.SetDealer(const AValue: UINT32);
begin
  FDealer := AValue;
  ProtobufOutput.writeUInt32(FN_DEALER, AValue);
end;

procedure TPB_HandHistory.SetGame(const AValue: TPB_Game);
begin
  FGame := AValue;
  ProtobufOutput.writeMessage(FN_GAME, AValue.ProtobufOutput);
end;

procedure TPB_HandHistory.SetCurrentGame(const AValue: TGameType);
begin
  FCurrentGame := AValue;
  ProtobufOutput.writeInt32(FN_CURRENT_GAME, Integer(AValue));
end;

procedure TPB_HandHistory.SetRake(const AValue: Integer);
begin
  FRake := AValue;
  ProtobufOutput.writeInt32(FN_RAKE, AValue);
end;

end.
