// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.PlayerHandHistory;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_PlayerHandHistory = class(TProtobufBaseObject)
  private
    const
      FN__ID = 1;
      FN_SEAT = 2;
      FN_CARDS = 3;
      FN_CHIPS = 4;
      FN_NICK = 5;

    var
      FId: TBytes;
      FSeat: UINT32;
      FCards: TBytes;
      FChips: UINT32;
      FNick: String;

    procedure SetMongoId(const AValue: TBytes);
    procedure SetSeat(const AValue: UINT32);
    procedure SetCards(const AValue: TBytes);
    procedure SetChips(const AValue: UINT32);
    procedure SetNick(const AValue: String);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property MongoId: TBytes read FId write SetMongoId;
    property Seat: UINT32 read FSeat write SetSeat;
    property Cards: TBytes read FCards write SetCards;
    property Chips: UINT32 read FChips write SetChips;
    property Nick: String read FNick write SetNick;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_PlayerHandHistory.Destroy;
begin
  inherited;
end;

procedure TPB_PlayerHandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN__ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FId);
      end;
      FN_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readUInt32;
      end;
      FN_CARDS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FCards);
      end;
      FN_CHIPS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChips := AProtobufReader.readUInt32;
      end;
      FN_NICK: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FNick := AProtobufReader.readUtf8String;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_PlayerHandHistory.SetMongoId(const AValue: TBytes);
begin
  FId := AValue;
  ProtobufOutput.writeBytes(FN__ID, AValue);
end;

procedure TPB_PlayerHandHistory.SetSeat(const AValue: UINT32);
begin
  FSeat := AValue;
  ProtobufOutput.writeUInt32(FN_SEAT, AValue);
end;

procedure TPB_PlayerHandHistory.SetCards(const AValue: TBytes);
begin
  FCards := AValue;
  ProtobufOutput.writeBytes(FN_CARDS, AValue);
end;

procedure TPB_PlayerHandHistory.SetChips(const AValue: UINT32);
begin
  FChips := AValue;
  ProtobufOutput.writeUInt32(FN_CHIPS, AValue);
end;

procedure TPB_PlayerHandHistory.SetNick(const AValue: String);
begin
  FNick := AValue;
  ProtobufOutput.writeString(FN_NICK, AValue);
end;

end.
