// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.ClubPlayerStats;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_ClubPlayerStats = class(TProtobufBaseObject)
  private
    const
      kUseridFieldNumber = 1;
      kClubBalanceFieldNumber = 2;

    var
      FUserid: TBytes;
      FClubBalance: Integer;
      _has_bits_: Integer;

    procedure set_has_Userid;
    procedure clear_has_Userid;
    procedure SetUserid(const AValue: TBytes);
    procedure set_has_ClubBalance;
    procedure clear_has_ClubBalance;
    procedure SetClubBalance(const AValue: Integer);

  public
    constructor Create(const AFrom: TPB_ClubPlayerStats; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_ClubPlayerStats);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required bytes Userid = 1;
    function has_Userid: Boolean;
    procedure clear_Userid;
    property Userid: TBytes read FUserid write SetUserid;

    // required int32 ClubBalance = 2;
    function has_ClubBalance: Boolean;
    procedure clear_ClubBalance;
    property ClubBalance: Integer read FClubBalance write SetClubBalance;

  end;
  TPB_ClubPlayerStatsList = class (TObjectList<TPB_ClubPlayerStats>)
    procedure Assign(const APB_ClubPlayerStatsList: TList<TPB_ClubPlayerStats>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



constructor TPB_ClubPlayerStats.Create(const AFrom: TPB_ClubPlayerStats; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_ClubPlayerStats.Destroy;
begin
  inherited;
end;

procedure TPB_ClubPlayerStats.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kUseridFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUserid := AProtobufReader.readBytes;
        set_has_Userid;
      end;
      kClubBalanceFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FClubBalance := AProtobufReader.readInt32;
        set_has_ClubBalance;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_ClubPlayerStats.MergeFrom(const from: TPB_ClubPlayerStats);
begin
  if (from.has_Userid) then
    SetUserid(from.Userid);
  if (from.has_ClubBalance) then
    SetClubBalance(from.ClubBalance);
end;

function TPB_ClubPlayerStats.IsInitialized: Boolean;
begin
  if ((_has_bits_ and $3) <> $3) Then Exit(false);
  Exit(True);
end;

procedure TPB_ClubPlayerStats.clear_Userid;
begin
  SetLength(FUserid,0);
  clear_has_Userid;
end;

function TPB_ClubPlayerStats.has_Userid: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_ClubPlayerStats.set_has_Userid;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_ClubPlayerStats.clear_has_Userid;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_ClubPlayerStats.SetUserid(const AValue: TBytes);
begin
  Assert(not has_Userid);
  FUserid := Copy(AValue,0,Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kUseridFieldNumber, AValue);
  set_has_Userid;
end;

procedure TPB_ClubPlayerStats.clear_ClubBalance;
begin
  FClubBalance := 0;
  clear_has_ClubBalance;
end;

function TPB_ClubPlayerStats.has_ClubBalance: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_ClubPlayerStats.set_has_ClubBalance;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_ClubPlayerStats.clear_has_ClubBalance;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_ClubPlayerStats.SetClubBalance(const AValue: Integer);
begin
  Assert(not has_ClubBalance);
  FClubBalance := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kClubBalanceFieldNumber, AValue);
  set_has_ClubBalance;
end;

procedure TPB_ClubPlayerStatsList.Assign(const APB_ClubPlayerStatsList: TList<TPB_ClubPlayerStats>);
var
  pbobj: TPB_ClubPlayerStats;
begin
  Clear;
  for pbobj in APB_ClubPlayerStatsList do
    Add(TPB_ClubPlayerStats.Create(pbobj, TRUE));
end;

procedure TPB_ClubPlayerStats.Clear;
begin
  if (_has_bits_ <> 0) then
  begin
    clear_Userid;
    clear_ClubBalance;
  end;
end;

end.
