// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.TableStatsReplies;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.TableStatsReply,Poker.Protobufs.Objects.User;

type
  TPB_TableStatsReplies = class(TProtobufBaseObject)
  private
    const
      FN_REPLY = 1;
      FN_PLAYERS = 2;

    var
      FReply: TObjectList<TPB_TableStatsReply>;
      FPlayers: TObjectList<TPB_User>;

    procedure ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Reply: TObjectList<TPB_TableStatsReply> read FReply;
    property Players: TObjectList<TPB_User> read FPlayers;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_TableStatsReplies.InitObjects;
begin
  FReply := TObjectList<TPB_TableStatsReply>.Create;
  FReply.OnNotify := ReplyNotifyEvent;
  FPlayers := TObjectList<TPB_User>.Create;
  FPlayers.OnNotify := PlayersNotifyEvent;
end;

destructor TPB_TableStatsReplies.Destroy;
begin
  if Assigned(FReply) then
  begin
    FReply.OnNotify := nil;
    FreeAndNil(FReply);
  end;
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  inherited;
end;

procedure TPB_TableStatsReplies.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_REPLY: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FReply.Add(TPB_TableStatsReply.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_PLAYERS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_TableStatsReplies.ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_REPLY,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_TableStatsReplies.PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_PLAYERS,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
