// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HelloReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.StringSizes,Poker.Protobufs.Objects.UpdateFileInfo,Poker.Protobufs.Objects.ValidCharsRegex;

type
  TPB_HelloReply = class(TProtobufBaseObject)
  private
    const
      kStringSizesFieldNumber = 1;
      kChangeExpireTimeFieldNumber = 2;
      kForgotExpireTimeFieldNumber = 3;
      kMaxPlayTimeFieldNumber = 4;
      kMaxTimebankFieldNumber = 5;
      kMinSizesFieldNumber = 6;
      kUpdateFilesFieldNumber = 7;
      kValidCharsRegexFieldNumber = 8;

    var
      FStringSizes: TPB_StringSizes;
      FChangeExpireTime: Integer;
      FForgotExpireTime: Integer;
      FMaxPlayTime: Integer;
      FMaxTimebank: Integer;
      FMinSizes: TPB_StringSizes;
      FUpdateFiles: TList<TPB_UpdateFileInfo>;
      FValidCharsRegex: TPB_ValidCharsRegex;
      _has_bits_: Integer;

    procedure set_has_StringSizes;
    procedure clear_has_StringSizes;
    procedure SetStringSizes(const AValue: TPB_StringSizes);
    procedure set_has_ChangeExpireTime;
    procedure clear_has_ChangeExpireTime;
    procedure SetChangeExpireTime(const AValue: Integer);
    procedure set_has_ForgotExpireTime;
    procedure clear_has_ForgotExpireTime;
    procedure SetForgotExpireTime(const AValue: Integer);
    procedure set_has_MaxPlayTime;
    procedure clear_has_MaxPlayTime;
    procedure SetMaxPlayTime(const AValue: Integer);
    procedure set_has_MaxTimebank;
    procedure clear_has_MaxTimebank;
    procedure SetMaxTimebank(const AValue: Integer);
    procedure set_has_MinSizes;
    procedure clear_has_MinSizes;
    procedure SetMinSizes(const AValue: TPB_StringSizes);
    procedure set_has_UpdateFiles;
    procedure clear_has_UpdateFiles;
    procedure set_has_ValidCharsRegex;
    procedure clear_has_ValidCharsRegex;
    procedure SetValidCharsRegex(const AValue: TPB_ValidCharsRegex);
    procedure UpdateFilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_HelloReply); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_HelloReply);
    function IsInitialized: Boolean; override;

    // required FIXME StringSizes = 1;
    function has_StringSizes: Boolean;
    procedure clear_StringSizes;
    property StringSizes: TPB_StringSizes read FStringSizes write SetStringSizes;

    // required int32 ChangeExpireTime = 2;
    function has_ChangeExpireTime: Boolean;
    procedure clear_ChangeExpireTime;
    property ChangeExpireTime: Integer read FChangeExpireTime write SetChangeExpireTime;

    // required int32 ForgotExpireTime = 3;
    function has_ForgotExpireTime: Boolean;
    procedure clear_ForgotExpireTime;
    property ForgotExpireTime: Integer read FForgotExpireTime write SetForgotExpireTime;

    // required int32 MaxPlayTime = 4;
    function has_MaxPlayTime: Boolean;
    procedure clear_MaxPlayTime;
    property MaxPlayTime: Integer read FMaxPlayTime write SetMaxPlayTime;

    // required int32 MaxTimebank = 5;
    function has_MaxTimebank: Boolean;
    procedure clear_MaxTimebank;
    property MaxTimebank: Integer read FMaxTimebank write SetMaxTimebank;

    // required FIXME MinSizes = 6;
    function has_MinSizes: Boolean;
    procedure clear_MinSizes;
    property MinSizes: TPB_StringSizes read FMinSizes write SetMinSizes;

    // repeated FIXME UpdateFiles = 7;
    function has_UpdateFiles: Boolean;
    procedure clear_UpdateFiles;
    property UpdateFiles: TList<TPB_UpdateFileInfo> read FUpdateFiles;

    // required FIXME ValidCharsRegex = 8;
    function has_ValidCharsRegex: Boolean;
    procedure clear_ValidCharsRegex;
    property ValidCharsRegex: TPB_ValidCharsRegex read FValidCharsRegex write SetValidCharsRegex;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HelloReply.InitObjects;
begin
  inherited;
  FUpdateFiles := TObjectList<TPB_UpdateFileInfo>.Create;
end;
procedure TPB_HelloReply.HookNotifiers;
begin
  inherited;
  FUpdateFiles.OnNotify := UpdateFilesNotifyEvent;
end;

constructor TPB_HelloReply.Create(const AFrom: TPB_HelloReply);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_HelloReply.Destroy;
begin
  if Assigned(FStringSizes) then
    FreeAndNil(FStringSizes);
  if Assigned(FMinSizes) then
    FreeAndNil(FMinSizes);
  if Assigned(FUpdateFiles) then
  begin
    FUpdateFiles.OnNotify := nil;
    FreeAndNil(FUpdateFiles);
  end;
  if Assigned(FValidCharsRegex) then
    FreeAndNil(FValidCharsRegex);
  inherited;
end;

procedure TPB_HelloReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kStringSizesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FStringSizes) then
          FStringSizes := TPB_StringSizes.Create;
        FStringSizes.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
        set_has_StringSizes;
      end;
      kChangeExpireTimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChangeExpireTime := AProtobufReader.readInt32;
        set_has_ChangeExpireTime;
      end;
      kForgotExpireTimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FForgotExpireTime := AProtobufReader.readInt32;
        set_has_ForgotExpireTime;
      end;
      kMaxPlayTimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMaxPlayTime := AProtobufReader.readInt32;
        set_has_MaxPlayTime;
      end;
      kMaxTimebankFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMaxTimebank := AProtobufReader.readInt32;
        set_has_MaxTimebank;
      end;
      kMinSizesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FMinSizes) then
          FMinSizes := TPB_StringSizes.Create;
        FMinSizes.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
        set_has_MinSizes;
      end;
      kUpdateFilesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUpdateFiles.Add(TPB_UpdateFileInfo.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_UpdateFiles;
      end;
      kValidCharsRegexFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FValidCharsRegex) then
          FValidCharsRegex := TPB_ValidCharsRegex.Create;
        FValidCharsRegex.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
        set_has_ValidCharsRegex;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HelloReply.MergeFrom(const from: TPB_HelloReply);
var
  temp6: TPB_UpdateFileInfo;
begin
  if (from.has_StringSizes) then
    FStringSizes.MergeFrom(from.StringSizes);
  if (from.has_ChangeExpireTime) then
    SetChangeExpireTime(from.ChangeExpireTime);
  if (from.has_ForgotExpireTime) then
    SetForgotExpireTime(from.ForgotExpireTime);
  if (from.has_MaxPlayTime) then
    SetMaxPlayTime(from.MaxPlayTime);
  if (from.has_MaxTimebank) then
    SetMaxTimebank(from.MaxTimebank);
  if (from.has_MinSizes) then
    FMinSizes.MergeFrom(from.MinSizes);
  for temp6 in from.UpdateFiles do
    FUpdateFiles.Add(TPB_UpdateFileInfo.Create(temp6));
  if (from.has_ValidCharsRegex) then
    FValidCharsRegex.MergeFrom(from.ValidCharsRegex);
end;

function TPB_HelloReply.IsInitialized: Boolean;
var
  temp: TProtobufBaseObject;
begin
  if ((_has_bits_ and $bf) <> $bf) Then Exit(false);
  if (has_StringSizes) then
    if (not FStringSizes.IsInitialized) then Exit(false);
  if (has_MinSizes) then
    if (not FMinSizes.IsInitialized) then Exit(false);
  for temp in UpdateFiles do
    if (not temp.IsInitialized) then Exit(false);
  if (has_ValidCharsRegex) then
    if (not FValidCharsRegex.IsInitialized) then Exit(false);
  Exit(True);
end;

procedure TPB_HelloReply.clear_StringSizes;
begin
  FreeAndNil(FStringSizes);
  clear_has_StringSizes;
end;

function TPB_HelloReply.has_StringSizes: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_HelloReply.set_has_StringSizes;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_HelloReply.clear_has_StringSizes;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_HelloReply.SetStringSizes(const AValue: TPB_StringSizes);
begin
  Assert(!has_StringSizes);
  FStringSizes := AValue;
  ProtobufOutput.writeMessage(kStringSizesFieldNumber, AValue.ProtobufOutput);
  set_has_StringSizes;
end;

procedure TPB_HelloReply.clear_ChangeExpireTime;
begin
  FChangeExpireTime := 0;
  clear_has_ChangeExpireTime;
end;

function TPB_HelloReply.has_ChangeExpireTime: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_HelloReply.set_has_ChangeExpireTime;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_HelloReply.clear_has_ChangeExpireTime;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_HelloReply.SetChangeExpireTime(const AValue: Integer);
begin
  Assert(!has_ChangeExpireTime);
  FChangeExpireTime := AValue;
  ProtobufOutput.writeInt32(kChangeExpireTimeFieldNumber, AValue);
  set_has_ChangeExpireTime;
end;

procedure TPB_HelloReply.clear_ForgotExpireTime;
begin
  FForgotExpireTime := 0;
  clear_has_ForgotExpireTime;
end;

function TPB_HelloReply.has_ForgotExpireTime: Boolean;
begin
  Result := (_has_bits_ and 4) > 0;
end;

procedure TPB_HelloReply.set_has_ForgotExpireTime;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_HelloReply.clear_has_ForgotExpireTime;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_HelloReply.SetForgotExpireTime(const AValue: Integer);
begin
  Assert(!has_ForgotExpireTime);
  FForgotExpireTime := AValue;
  ProtobufOutput.writeInt32(kForgotExpireTimeFieldNumber, AValue);
  set_has_ForgotExpireTime;
end;

procedure TPB_HelloReply.clear_MaxPlayTime;
begin
  FMaxPlayTime := 0;
  clear_has_MaxPlayTime;
end;

function TPB_HelloReply.has_MaxPlayTime: Boolean;
begin
  Result := (_has_bits_ and 8) > 0;
end;

procedure TPB_HelloReply.set_has_MaxPlayTime;
begin
  _has_bits_ := _has_bits_ or 8;
end;

procedure TPB_HelloReply.clear_has_MaxPlayTime;
begin
  _has_bits_ := _has_bits_ and not 8;
end;

procedure TPB_HelloReply.SetMaxPlayTime(const AValue: Integer);
begin
  Assert(!has_MaxPlayTime);
  FMaxPlayTime := AValue;
  ProtobufOutput.writeInt32(kMaxPlayTimeFieldNumber, AValue);
  set_has_MaxPlayTime;
end;

procedure TPB_HelloReply.clear_MaxTimebank;
begin
  FMaxTimebank := 0;
  clear_has_MaxTimebank;
end;

function TPB_HelloReply.has_MaxTimebank: Boolean;
begin
  Result := (_has_bits_ and 16) > 0;
end;

procedure TPB_HelloReply.set_has_MaxTimebank;
begin
  _has_bits_ := _has_bits_ or 16;
end;

procedure TPB_HelloReply.clear_has_MaxTimebank;
begin
  _has_bits_ := _has_bits_ and not 16;
end;

procedure TPB_HelloReply.SetMaxTimebank(const AValue: Integer);
begin
  Assert(!has_MaxTimebank);
  FMaxTimebank := AValue;
  ProtobufOutput.writeInt32(kMaxTimebankFieldNumber, AValue);
  set_has_MaxTimebank;
end;

procedure TPB_HelloReply.clear_MinSizes;
begin
  FreeAndNil(FMinSizes);
  clear_has_MinSizes;
end;

function TPB_HelloReply.has_MinSizes: Boolean;
begin
  Result := (_has_bits_ and 32) > 0;
end;

procedure TPB_HelloReply.set_has_MinSizes;
begin
  _has_bits_ := _has_bits_ or 32;
end;

procedure TPB_HelloReply.clear_has_MinSizes;
begin
  _has_bits_ := _has_bits_ and not 32;
end;

procedure TPB_HelloReply.SetMinSizes(const AValue: TPB_StringSizes);
begin
  Assert(!has_MinSizes);
  FMinSizes := AValue;
  ProtobufOutput.writeMessage(kMinSizesFieldNumber, AValue.ProtobufOutput);
  set_has_MinSizes;
end;

procedure TPB_HelloReply.clear_UpdateFiles;
begin
  FUpdateFiles.Clear;
  clear_has_UpdateFiles;
end;

function TPB_HelloReply.has_UpdateFiles: Boolean;
begin
  Result := (_has_bits_ and 64) > 0;
end;

procedure TPB_HelloReply.set_has_UpdateFiles;
begin
  _has_bits_ := _has_bits_ or 64;
end;

procedure TPB_HelloReply.clear_has_UpdateFiles;
begin
  _has_bits_ := _has_bits_ and not 64;
end;

procedure TPB_HelloReply.UpdateFilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kUpdateFilesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_HelloReply.clear_ValidCharsRegex;
begin
  FreeAndNil(FValidCharsRegex);
  clear_has_ValidCharsRegex;
end;

function TPB_HelloReply.has_ValidCharsRegex: Boolean;
begin
  Result := (_has_bits_ and 128) > 0;
end;

procedure TPB_HelloReply.set_has_ValidCharsRegex;
begin
  _has_bits_ := _has_bits_ or 128;
end;

procedure TPB_HelloReply.clear_has_ValidCharsRegex;
begin
  _has_bits_ := _has_bits_ and not 128;
end;

procedure TPB_HelloReply.SetValidCharsRegex(const AValue: TPB_ValidCharsRegex);
begin
  Assert(!has_ValidCharsRegex);
  FValidCharsRegex := AValue;
  ProtobufOutput.writeMessage(kValidCharsRegexFieldNumber, AValue.ProtobufOutput);
  set_has_ValidCharsRegex;
end;

end.
