// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.ChangePasswordParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_ChangePasswordParams = class(TProtobufBaseObject)
  private
    const
      FN_NEW_PASSWORD = 1;

    var
      FNewPassword: String;

    procedure SetNewPassword(const AValue: String);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property NewPassword: String read FNewPassword write SetNewPassword;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_ChangePasswordParams.Destroy;
begin
  inherited;
end;
procedure TPB_ChangePasswordParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_NEW_PASSWORD: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FNewPassword := AProtobufReader.readUtf8String;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_ChangePasswordParams.SetNewPassword(const AValue: String);
begin
  FNewPassword := AValue;
  ProtobufOutput.writeString(FN_NEW_PASSWORD, AValue);
end;

end.
