// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.Pot;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,
  Poker.Protobufs.Objects.WinnerData;

type
  TPB_Pot = class(TProtobufBaseObject)
  private
    const
      kValueFieldNumber = 1;
      kMembersFieldNumber = 2;
      kWinnerDataFieldNumber = 3;
      kRakeFieldNumber = 4;

    var
      FValue: UInt32;
      FMembers: TList<Integer>;
      FWinnerData: TList<TPB_WinnerData>;
      FRake: UInt32;
      _has_bits_: UINT32;

    procedure set_has_Value;
    procedure clear_has_Value;
    procedure SetValue(const AValue: UInt32);
    procedure set_has_Members;
    procedure clear_has_Members;
    procedure set_has_WinnerData;
    procedure clear_has_WinnerData;
    procedure set_has_Rake;
    procedure clear_has_Rake;
    procedure SetRake(const AValue: UInt32);
    procedure MembersNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
    procedure WinnerDataNotifyEvent(Sender: TObject; const Item: TPB_WinnerData; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_Pot; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_Pot);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required uint32 Value = 1;
    function has_Value: Boolean;
    procedure clear_Value;
    property Value: UInt32 read FValue write SetValue;

    // repeated int32 Members = 2;
    function has_Members: Boolean;
    procedure clear_Members;
    property Members: TList<Integer> read FMembers;

    // repeated WinnerData WinnerData = 3;
    function has_WinnerData: Boolean;
    procedure clear_WinnerData;
    property WinnerData: TList<TPB_WinnerData> read FWinnerData;

    // optional uint32 Rake = 4;
    function has_Rake: Boolean;
    procedure clear_Rake;
    property Rake: UInt32 read FRake write SetRake;

  end;

  TPB_PotList = class(TObjectList<TPB_Pot>)
    procedure Assign(const APB_PotList: TList<TPB_Pot>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_Pot.Create(const AFrom: TPB_Pot; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_Pot.Destroy;
begin
  if Assigned(FMembers) then
  begin
    FMembers.OnNotify := nil;
    FreeAndNil(FMembers);
  end;
  if Assigned(FWinnerData) then
  begin
    FWinnerData.OnNotify := nil;
    FreeAndNil(FWinnerData);
  end;
  inherited;
end;

procedure TPB_Pot.InitObjects;
begin
  inherited;
  FMembers := TList<Integer>.Create;
  FWinnerData := TObjectList<TPB_WinnerData>.Create;
end;

procedure TPB_Pot.HookNotifiers;
begin
  inherited;
  FMembers.OnNotify := MembersNotifyEvent;
  FWinnerData.OnNotify := WinnerDataNotifyEvent;
end;
procedure TPB_Pot.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kValueFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FValue := AProtobufReader.readUInt32;
        set_has_Value;
      end;
      kMembersFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMembers.Add(AProtobufReader.readInt32);
        set_has_Members;
      end;
      kWinnerDataFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FWinnerData.Add(TPB_WinnerData.Create(AProtobufReader,AProtobufReader.readInt32, Lightweight));
        set_has_WinnerData;
      end;
      kRakeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FRake := AProtobufReader.readUInt32;
        set_has_Rake;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_Pot.MergeFrom(const AFrom: TPB_Pot);
var
  pbobj2: TPB_WinnerData;
begin
  if AFrom.has_Value then
    SetValue(AFrom.Value);
  FMembers.AddRange(AFrom.Members);
  for pbobj2 in AFrom.WinnerData do
    FWinnerData.Add(TPB_WinnerData.Create(pbobj2));
  if AFrom.has_Rake then
    SetRake(AFrom.Rake);
end;

function TPB_Pot.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $1) <> $1 then
    Exit(FALSE);
  for pbobj in WinnerData do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_Pot.clear_Value;
begin
  FValue := 0;
  clear_has_Value;
end;

function TPB_Pot.has_Value: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_Pot.set_has_Value;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_Pot.clear_has_Value;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_Pot.SetValue(const AValue: UInt32);
begin
  Assert(not has_Value);
  FValue := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kValueFieldNumber, AValue);
  set_has_Value;
end;

procedure TPB_Pot.clear_Members;
begin
  FMembers.Clear;
  clear_has_Members;
end;

function TPB_Pot.has_Members: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_Pot.set_has_Members;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_Pot.clear_has_Members;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_Pot.MembersNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Members;
  if not Lightweight then
    ProtobufOutput.writeInt32(kMembersFieldNumber,Item);
end;

procedure TPB_Pot.clear_WinnerData;
begin
  FWinnerData.Clear;
  clear_has_WinnerData;
end;

function TPB_Pot.has_WinnerData: Boolean;
begin
  result := (_has_bits_ and 4) > 0;
end;

procedure TPB_Pot.set_has_WinnerData;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_Pot.clear_has_WinnerData;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_Pot.WinnerDataNotifyEvent(Sender: TObject; const Item: TPB_WinnerData; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_WinnerData;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kWinnerDataFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_Pot.clear_Rake;
begin
  FRake := 0;
  clear_has_Rake;
end;

function TPB_Pot.has_Rake: Boolean;
begin
  result := (_has_bits_ and 8) > 0;
end;

procedure TPB_Pot.set_has_Rake;
begin
  _has_bits_ := _has_bits_ or 8;
end;

procedure TPB_Pot.clear_has_Rake;
begin
  _has_bits_ := _has_bits_ and not 8;
end;

procedure TPB_Pot.SetRake(const AValue: UInt32);
begin
  Assert(not has_Rake);
  FRake := AValue;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kRakeFieldNumber, AValue);
  set_has_Rake;
end;

procedure TPB_Pot.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Value;
  clear_Members;
  clear_WinnerData;
  clear_Rake;
end;

procedure TPB_PotList.Assign(const APB_PotList: TList<TPB_Pot>);
var
  pbobj: TPB_Pot;
begin
  Clear;
  for pbobj in APB_PotList do
    Add(TPB_Pot.Create(pbobj, TRUE));
end;

end.
