// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TableEvent;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,
  Poker.Protobufs.Objects.Pot;

type
  TTableEventType = (teFold = 0,teSit = 1,teStandUp = 2,teWinning = 3,teDealing = 4,teCheck = 5,teCall = 6,teRaise = 7,teAllIn = 8,teFlop = 9,teTurn = 10,teRiver = 11,tePostRiver = 12,tePreWin = 13,teExistingCards = 14,teDisconnect = 15,teSB = 16,teBB = 17,teForced = 18);

  TPB_TableEvent = class(TProtobufBaseObject)
  private
    const
      kEventFieldNumber = 1;
      kSeatFieldNumber = 2;
      kPotsFieldNumber = 4;
      kBetsFieldNumber = 5;
      kCardsFieldNumber = 6;

    var
      FEvent: TTableEventType;
      FSeat: Integer;
      FPots: TList<TPB_Pot>;
      FBets: TList<UInt32>;
      FCards: TBytes;
      _has_bits_: UINT32;

    procedure set_has_Event;
    procedure clear_has_Event;
    procedure SetEvent(const AValue: TTableEventType);
    procedure set_has_Seat;
    procedure clear_has_Seat;
    procedure SetSeat(const AValue: Integer);
    procedure set_has_Pots;
    procedure clear_has_Pots;
    procedure set_has_Bets;
    procedure clear_has_Bets;
    procedure set_has_Cards;
    procedure clear_has_Cards;
    procedure SetCards(const AValue: TBytes);
    procedure PotsNotifyEvent(Sender: TObject; const Item: TPB_Pot; Action: TCollectionNotification);
    procedure BetsNotifyEvent(Sender: TObject; const Item: UInt32; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_TableEvent; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TableEvent);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // required TableEventType Event = 1;
    function has_Event: Boolean;
    procedure clear_Event;
    property Event: TTableEventType read FEvent write SetEvent;

    // optional int32 Seat = 2;
    function has_Seat: Boolean;
    procedure clear_Seat;
    property Seat: Integer read FSeat write SetSeat;

    // repeated Pot Pots = 4;
    function has_Pots: Boolean;
    procedure clear_Pots;
    property Pots: TList<TPB_Pot> read FPots;

    // repeated uint32 Bets = 5;
    function has_Bets: Boolean;
    procedure clear_Bets;
    property Bets: TList<UInt32> read FBets;

    // optional bytes Cards = 6;
    function has_Cards: Boolean;
    procedure clear_Cards;
    property Cards: TBytes read FCards write SetCards;

  end;

  TPB_TableEventList = class(TObjectList<TPB_TableEvent>)
    procedure Assign(const APB_TableEventList: TList<TPB_TableEvent>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TableEvent.Create(const AFrom: TPB_TableEvent; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TableEvent.Destroy;
begin
  if Assigned(FPots) then
  begin
    FPots.OnNotify := nil;
    FreeAndNil(FPots);
  end;
  if Assigned(FBets) then
  begin
    FBets.OnNotify := nil;
    FreeAndNil(FBets);
  end;
  inherited;
end;

procedure TPB_TableEvent.InitObjects;
begin
  inherited;
  FPots := TObjectList<TPB_Pot>.Create;
  FBets := TList<UInt32>.Create;
end;

procedure TPB_TableEvent.HookNotifiers;
begin
  inherited;
  FPots.OnNotify := PotsNotifyEvent;
  FBets.OnNotify := BetsNotifyEvent;
end;
procedure TPB_TableEvent.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kEventFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEvent := TTableEventType(AProtobufReader.readEnum);
        set_has_Event;
      end;
      kSeatFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readInt32;
        set_has_Seat;
      end;
      kPotsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPots.Add(TPB_Pot.Create(AProtobufReader,AProtobufReader.readInt32, Lightweight));
        set_has_Pots;
      end;
      kBetsFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBets.Add(AProtobufReader.readUInt32);
        set_has_Bets;
      end;
      kCardsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FCards := AProtobufReader.readBytes;
        set_has_Cards;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TableEvent.MergeFrom(const AFrom: TPB_TableEvent);
var
  pbobj2: TPB_Pot;
begin
  if AFrom.has_Event then
    SetEvent(AFrom.Event);
  if AFrom.has_Seat then
    SetSeat(AFrom.Seat);
  for pbobj2 in AFrom.Pots do
    FPots.Add(TPB_Pot.Create(pbobj2));
  FBets.AddRange(AFrom.Bets);
  if AFrom.has_Cards then
    SetCards(AFrom.Cards);
end;

function TPB_TableEvent.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $1) <> $1 then
    Exit(FALSE);
  for pbobj in Pots do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TableEvent.clear_Event;
begin
  FEvent := TTableEventType(0);
  clear_has_Event;
end;

function TPB_TableEvent.has_Event: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TableEvent.set_has_Event;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TableEvent.clear_has_Event;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_TableEvent.SetEvent(const AValue: TTableEventType);
begin
  Assert(not has_Event);
  FEvent := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kEventFieldNumber, Integer(AValue));
  set_has_Event;
end;

procedure TPB_TableEvent.clear_Seat;
begin
  FSeat := 0;
  clear_has_Seat;
end;

function TPB_TableEvent.has_Seat: Boolean;
begin
  result := (_has_bits_ and 2) > 0;
end;

procedure TPB_TableEvent.set_has_Seat;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_TableEvent.clear_has_Seat;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_TableEvent.SetSeat(const AValue: Integer);
begin
  Assert(not has_Seat);
  FSeat := AValue;
  if not Lightweight then
    ProtobufOutput.writeInt32(kSeatFieldNumber, AValue);
  set_has_Seat;
end;

procedure TPB_TableEvent.clear_Pots;
begin
  FPots.Clear;
  clear_has_Pots;
end;

function TPB_TableEvent.has_Pots: Boolean;
begin
  result := (_has_bits_ and 8) > 0;
end;

procedure TPB_TableEvent.set_has_Pots;
begin
  _has_bits_ := _has_bits_ or 8;
end;

procedure TPB_TableEvent.clear_has_Pots;
begin
  _has_bits_ := _has_bits_ and not 8;
end;

procedure TPB_TableEvent.PotsNotifyEvent(Sender: TObject; const Item: TPB_Pot; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Pots;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kPotsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_TableEvent.clear_Bets;
begin
  FBets.Clear;
  clear_has_Bets;
end;

function TPB_TableEvent.has_Bets: Boolean;
begin
  result := (_has_bits_ and 16) > 0;
end;

procedure TPB_TableEvent.set_has_Bets;
begin
  _has_bits_ := _has_bits_ or 16;
end;

procedure TPB_TableEvent.clear_has_Bets;
begin
  _has_bits_ := _has_bits_ and not 16;
end;

procedure TPB_TableEvent.BetsNotifyEvent(Sender: TObject; const Item: UInt32; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Bets;
  if not Lightweight then
    ProtobufOutput.writeUInt32(kBetsFieldNumber,Item);
end;

procedure TPB_TableEvent.clear_Cards;
begin
  SetLength(FCards, 0);
  clear_has_Cards;
end;

function TPB_TableEvent.has_Cards: Boolean;
begin
  result := (_has_bits_ and 32) > 0;
end;

procedure TPB_TableEvent.set_has_Cards;
begin
  _has_bits_ := _has_bits_ or 32;
end;

procedure TPB_TableEvent.clear_has_Cards;
begin
  _has_bits_ := _has_bits_ and not 32;
end;

procedure TPB_TableEvent.SetCards(const AValue: TBytes);
begin
  Assert(not has_Cards);
  FCards := Copy(AValue, 0, Length(AValue));
  if not Lightweight then
    ProtobufOutput.writeBytes(kCardsFieldNumber, AValue);
  set_has_Cards;
end;

procedure TPB_TableEvent.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Event;
  clear_Seat;
  clear_Pots;
  clear_Bets;
  clear_Cards;
end;

procedure TPB_TableEventList.Assign(const APB_TableEventList: TList<TPB_TableEvent>);
var
  pbobj: TPB_TableEvent;
begin
  Clear;
  for pbobj in APB_TableEventList do
    Add(TPB_TableEvent.Create(pbobj, TRUE));
end;

end.
