// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.UserChangeParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.User;

type
  TPB_UserChangeParams = class(TProtobufBaseObject)
  private
    const
      kUsersFieldNumber = 1;

    var
      FUsers: TList<TPB_User>;
      _has_bits_: Integer;

    procedure set_has_Users;
    procedure clear_has_Users;
    procedure UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_UserChangeParams);

    // LABEL TYPE Users = 1;
    function has_Users: Boolean;
    procedure clear_Users;
    property Users: TList<TPB_User> read FUsers;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_UserChangeParams.InitObjects;
begin
  inherited;
  FUsers := TObjectList<TPB_User>.Create;
end;
procedure TPB_UserChangeParams.HookNotifiers;
begin
  inherited;
  FUsers.OnNotify := UsersNotifyEvent;
end;

destructor TPB_UserChangeParams.Destroy;
begin
  if Assigned(FUsers) then
  begin
    FUsers.OnNotify := nil;
    FreeAndNil(FUsers);
  end;
  inherited;
end;

procedure TPB_UserChangeParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kUsersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_UserChangeParams.MergeFrom(const from: TPB_UserChangeParams);
begin
end;

procedure TPB_UserChangeParams.clear_Users;
begin
  FUsers.Clear;
  clear_has_Users;
end;

function TPB_UserChangeParams.has_Users: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_UserChangeParams.set_has_Users;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_UserChangeParams.clear_has_Users;
begin
  _has_bits_ := _has_bits_ xor 1;
end;

procedure TPB_UserChangeParams.UsersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kUsersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
