// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.FetchHandHistory;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.ClubQuery;

type
  TPB_FetchHandHistory = class(TProtobufBaseObject)
  private
    const
      FN_CLUBS = 1;

    var
      FClubs: TObjectList<TPB_ClubQuery>;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Clubs: TObjectList<TPB_ClubQuery> read FClubs write FClubs;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_FetchHandHistory.Destroy;
begin
  if Assigned(FClubs) then
    FClubs.Free;
  inherited;
end;
procedure TPB_FetchHandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  if not Assigned(FClubs) then
    FClubs := TObjectList<TPB_ClubQuery>.Create;

  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_CLUBS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubs.Add(TPB_ClubQuery.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
end.
