// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.SeatInfo;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPlayerStatus = (psOutOfPlay = 1,psOutOfHand = 2,psInHand = 3,psFolded = 4,psAllIn = 5,psStandingUp = 6);
  TPB_SeatInfo = class(TProtobufBaseObject)
  private
    const
      FN_SEAT = 1;
      FN_PLAYER_MONGO_ID = 2;
      FN_CHIPS = 3;
      FN_CARD_COUNT = 4;
      FN_CARDS = 5;
      FN_STATUS = 6;
      FN_TIMEBANK = 7;
      FN_CARDS_VISIBLE = 8;

    var
      FSeat: Integer;
      FPlayerMongoId: TBytes;
      FChips: UINT32;
      FCardCount: Integer;
      FCards: TBytes;
      FStatus: TPlayerStatus;
      FTimebank: UINT32;
      FCardsVisible: Boolean;

    procedure SetSeat(const AValue: Integer);
    procedure SetPlayerMongoId(const AValue: TBytes);
    procedure SetChips(const AValue: UINT32);
    procedure SetCardCount(const AValue: Integer);
    procedure SetCards(const AValue: TBytes);
    procedure SetStatus(const AValue: TPlayerStatus);
    procedure SetTimebank(const AValue: UINT32);
    procedure SetCardsVisible(const AValue: Boolean);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Seat: Integer read FSeat write SetSeat;
    property PlayerMongoId: TBytes read FPlayerMongoId write SetPlayerMongoId;
    property Chips: UINT32 read FChips write SetChips;
    property CardCount: Integer read FCardCount write SetCardCount;
    property Cards: TBytes read FCards write SetCards;
    property Status: TPlayerStatus read FStatus write SetStatus;
    property Timebank: UINT32 read FTimebank write SetTimebank;
    property CardsVisible: Boolean read FCardsVisible write SetCardsVisible;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_SeatInfo.Destroy;
begin
  inherited;
end;

procedure TPB_SeatInfo.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readInt32;
      end;
      FN_PLAYER_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FPlayerMongoId);
      end;
      FN_CHIPS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChips := AProtobufReader.readUInt32;
      end;
      FN_CARD_COUNT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCardCount := AProtobufReader.readInt32;
      end;
      FN_CARDS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FCards);
      end;
      FN_STATUS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FStatus := TPlayerStatus(AProtobufReader.readEnum);
      end;
      FN_TIMEBANK: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FTimebank := AProtobufReader.readUInt32;
      end;
      FN_CARDS_VISIBLE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCardsVisible := AProtobufReader.readBoolean;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_SeatInfo.SetSeat(const AValue: Integer);
begin
  FSeat := AValue;
  ProtobufOutput.writeInt32(FN_SEAT, AValue);
end;

procedure TPB_SeatInfo.SetPlayerMongoId(const AValue: TBytes);
begin
  FPlayerMongoId := AValue;
  ProtobufOutput.writeBytes(FN_PLAYER_MONGO_ID, AValue);
end;

procedure TPB_SeatInfo.SetChips(const AValue: UINT32);
begin
  FChips := AValue;
  ProtobufOutput.writeUInt32(FN_CHIPS, AValue);
end;

procedure TPB_SeatInfo.SetCardCount(const AValue: Integer);
begin
  FCardCount := AValue;
  ProtobufOutput.writeInt32(FN_CARD_COUNT, AValue);
end;

procedure TPB_SeatInfo.SetCards(const AValue: TBytes);
begin
  FCards := AValue;
  ProtobufOutput.writeBytes(FN_CARDS, AValue);
end;

procedure TPB_SeatInfo.SetStatus(const AValue: TPlayerStatus);
begin
  FStatus := AValue;
  ProtobufOutput.writeInt32(FN_STATUS, Integer(AValue));
end;

procedure TPB_SeatInfo.SetTimebank(const AValue: UINT32);
begin
  FTimebank := AValue;
  ProtobufOutput.writeUInt32(FN_TIMEBANK, AValue);
end;

procedure TPB_SeatInfo.SetCardsVisible(const AValue: Boolean);
begin
  FCardsVisible := AValue;
  ProtobufOutput.writeBoolean(FN_CARDS_VISIBLE, AValue);
end;

end.
