// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.WinnerRow;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_WinnerRow = class(TProtobufBaseObject)
  private
    const
      FN_MSG = 1;
      FN_SEAT = 2;

    var
      FMsg: String;
      FSeat: UINT32;

    procedure SetMsg(const AValue: String);
    procedure SetSeat(const AValue: UINT32);

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Msg: String read FMsg write SetMsg;
    property Seat: UINT32 read FSeat write SetSeat;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;



destructor TPB_WinnerRow.Destroy;
begin
  inherited;
end;

procedure TPB_WinnerRow.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_MSG: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FMsg := AProtobufReader.readUtf8String;
      end;
      FN_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readUInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_WinnerRow.SetMsg(const AValue: String);
begin
  FMsg := AValue;
  ProtobufOutput.writeString(FN_MSG, AValue);
end;

procedure TPB_WinnerRow.SetSeat(const AValue: UINT32);
begin
  FSeat := AValue;
  ProtobufOutput.writeUInt32(FN_SEAT, AValue);
end;

end.
