// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HelloReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.StringSizes,Poker.Protobufs.Objects.UpdateFileInfo;

type
  TPB_HelloReply = class(TProtobufBaseObject)
  private
    const
      FN_STRINGSIZES = 2;
      FN_CHANGEEXPIRETIME = 3;
      FN_FORGOTEXPIRETIME = 4;
      FN_MAX_PLAY_TIME = 5;
      FN_MAX_TIMEBANK = 6;
      FN_LATESTVERSION = 7;
      FN_LATESTDEBUGVERSION = 8;
      FN_MINSIZES = 9;
      FN_UPDATE_FILES = 10;

    var
      FStringSizes: TPB_StringSizes;
      FChangeExpireTime: Integer;
      FForgotExpireTime: Integer;
      FMaxPlayTime: Integer;
      FMaxTimebank: Integer;
      FLatestVersion: String;
      FLatestDebugVersion: String;
      FMinSizes: TPB_StringSizes;
      FUpdateFiles: TObjectList<TPB_UpdateFileInfo>;

    procedure SetStringSizes(const AValue: TPB_StringSizes);
    procedure SetChangeExpireTime(const AValue: Integer);
    procedure SetForgotExpireTime(const AValue: Integer);
    procedure SetMaxPlayTime(const AValue: Integer);
    procedure SetMaxTimebank(const AValue: Integer);
    procedure SetLatestVersion(const AValue: String);
    procedure SetLatestDebugVersion(const AValue: String);
    procedure SetMinSizes(const AValue: TPB_StringSizes);
    procedure UpdateFilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;

  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property StringSizes: TPB_StringSizes read FStringSizes write SetStringSizes;
    property ChangeExpireTime: Integer read FChangeExpireTime write SetChangeExpireTime;
    property ForgotExpireTime: Integer read FForgotExpireTime write SetForgotExpireTime;
    property MaxPlayTime: Integer read FMaxPlayTime write SetMaxPlayTime;
    property MaxTimebank: Integer read FMaxTimebank write SetMaxTimebank;
    property LatestVersion: String read FLatestVersion write SetLatestVersion;
    property LatestDebugVersion: String read FLatestDebugVersion write SetLatestDebugVersion;
    property MinSizes: TPB_StringSizes read FMinSizes write SetMinSizes;
    property UpdateFiles: TObjectList<TPB_UpdateFileInfo> read FUpdateFiles;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HelloReply.InitObjects;
begin
  FUpdateFiles := TObjectList<TPB_UpdateFileInfo>.Create;
  FUpdateFiles.OnNotify := UpdateFilesNotifyEvent;
end;

destructor TPB_HelloReply.Destroy;
begin
  if Assigned(FStringSizes) then
    FreeAndNil(FStringSizes);
  if Assigned(FMinSizes) then
    FreeAndNil(FMinSizes);
  if Assigned(FUpdateFiles) then
  begin
    FUpdateFiles.OnNotify := nil;
    FreeAndNil(FUpdateFiles);
  end;
  inherited;
end;

procedure TPB_HelloReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_STRINGSIZES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FStringSizes) then
          FStringSizes := TPB_StringSizes.Create;
        FStringSizes.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
      end;
      FN_CHANGEEXPIRETIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChangeExpireTime := AProtobufReader.readInt32;
      end;
      FN_FORGOTEXPIRETIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FForgotExpireTime := AProtobufReader.readInt32;
      end;
      FN_MAX_PLAY_TIME: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMaxPlayTime := AProtobufReader.readInt32;
      end;
      FN_MAX_TIMEBANK: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMaxTimebank := AProtobufReader.readInt32;
      end;
      FN_LATESTVERSION: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FLatestVersion := AProtobufReader.readUtf8String;
      end;
      FN_LATESTDEBUGVERSION: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FLatestDebugVersion := AProtobufReader.readUtf8String;
      end;
      FN_MINSIZES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FMinSizes) then
          FMinSizes := TPB_StringSizes.Create;
        FMinSizes.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
      end;
      FN_UPDATE_FILES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUpdateFiles.Add(TPB_UpdateFileInfo.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HelloReply.SetStringSizes(const AValue: TPB_StringSizes);
begin
  FStringSizes := AValue;
  ProtobufOutput.writeMessage(FN_STRINGSIZES, AValue.ProtobufOutput);
end;

procedure TPB_HelloReply.SetChangeExpireTime(const AValue: Integer);
begin
  FChangeExpireTime := AValue;
  ProtobufOutput.writeInt32(FN_CHANGEEXPIRETIME, AValue);
end;

procedure TPB_HelloReply.SetForgotExpireTime(const AValue: Integer);
begin
  FForgotExpireTime := AValue;
  ProtobufOutput.writeInt32(FN_FORGOTEXPIRETIME, AValue);
end;

procedure TPB_HelloReply.SetMaxPlayTime(const AValue: Integer);
begin
  FMaxPlayTime := AValue;
  ProtobufOutput.writeInt32(FN_MAX_PLAY_TIME, AValue);
end;

procedure TPB_HelloReply.SetMaxTimebank(const AValue: Integer);
begin
  FMaxTimebank := AValue;
  ProtobufOutput.writeInt32(FN_MAX_TIMEBANK, AValue);
end;

procedure TPB_HelloReply.SetLatestVersion(const AValue: String);
begin
  FLatestVersion := AValue;
  ProtobufOutput.writeString(FN_LATESTVERSION, AValue);
end;

procedure TPB_HelloReply.SetLatestDebugVersion(const AValue: String);
begin
  FLatestDebugVersion := AValue;
  ProtobufOutput.writeString(FN_LATESTDEBUGVERSION, AValue);
end;

procedure TPB_HelloReply.SetMinSizes(const AValue: TPB_StringSizes);
begin
  FMinSizes := AValue;
  ProtobufOutput.writeMessage(FN_MINSIZES, AValue.ProtobufOutput);
end;

procedure TPB_HelloReply.UpdateFilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(FN_UPDATE_FILES,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
