// Generated by the protocol buffer compiler.  DO NOT EDIT!
// Source: message.proto

unit Poker.Protobufs.Objects.TournamentList;

interface

uses
  System.SysUtils, System.Classes, {$IFNDEF FPC} System.Generics.Collections {$ELSE} Contnrs {$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader, Poker.Types,
  Poker.Protobufs.Objects.TournamentInfo;

type
  TPB_TournamentList = class(TProtobufBaseObject)
  private
    const
      kItemsFieldNumber = 1;

    var
      FItems: TList<TPB_TournamentInfo>;
      _has_bits_: UINT32;

    procedure set_has_Items;
    procedure clear_has_Items;
    procedure ItemsNotifyEvent(Sender: TObject; const Item: TPB_TournamentInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_TournamentList; const ALightweight: Boolean = FALSE); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const AFrom: TPB_TournamentList);
    procedure Clear;
    function IsInitialized: Boolean; override;

    // repeated TournamentInfo Items = 1;
    function has_Items: Boolean;
    procedure clear_Items;
    property Items: TList<TPB_TournamentInfo> read FItems;

  end;

  TPB_TournamentListList = class(TObjectList<TPB_TournamentList>)
    procedure Assign(const APB_TournamentListList: TList<TPB_TournamentList>);
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


constructor TPB_TournamentList.Create(const AFrom: TPB_TournamentList; const ALightweight: Boolean = FALSE);
begin
  inherited Create(ALightweight);
  MergeFrom(AFrom);
end;

destructor TPB_TournamentList.Destroy;
begin
  if Assigned(FItems) then
  begin
    FItems.OnNotify := nil;
    FreeAndNil(FItems);
  end;
  inherited;
end;

procedure TPB_TournamentList.InitObjects;
begin
  inherited;
  FItems := TObjectList<TPB_TournamentInfo>.Create;
end;

procedure TPB_TournamentList.HookNotifiers;
begin
  inherited;
  FItems.OnNotify := ItemsNotifyEvent;
end;

procedure TPB_TournamentList.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag, field_number, wire_type, endpos: Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do
    case field_number of
      kItemsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FItems.Add(TPB_TournamentInfo.Create(AProtobufReader, AProtobufReader.readInt32, Lightweight));
        set_has_Items;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
end;

procedure TPB_TournamentList.MergeFrom(const AFrom: TPB_TournamentList);
var
  pbobj0: TPB_TournamentInfo;
begin
  for pbobj0 in AFrom.Items do
    FItems.Add(TPB_TournamentInfo.Create(pbobj0));
end;

function TPB_TournamentList.IsInitialized: Boolean;
var
  pbobj: TProtobufBaseObject;
begin
  if (_has_bits_ and $0) <> $0 then
    Exit(FALSE);
  for pbobj in Items do
    if not pbobj.IsInitialized then
      Exit(FALSE);
  Exit(TRUE);
end;

procedure TPB_TournamentList.clear_Items;
var
  on_notify: TCollectionNotifyEvent<TPB_TournamentInfo>;
begin
  on_notify := FItems.OnNotify;
  FItems.OnNotify := nil;
  FItems.Clear;
  FItems.OnNotify := on_notify;
  clear_has_Items;
end;

function TPB_TournamentList.has_Items: Boolean;
begin
  result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TournamentList.set_has_Items;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TournamentList.clear_has_Items;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_TournamentList.ItemsNotifyEvent(Sender: TObject; const Item: TPB_TournamentInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  set_has_Items;
  if not Lightweight then
  begin
    ProtobufOutput.writeTag(kItemsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
    ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
    Item.ProtobufOutput.writeTo(ProtobufOutput);
  end;
end;

procedure TPB_TournamentList.Clear;
begin
  if _has_bits_ = 0 then
    Exit;

  clear_Items;
end;

procedure TPB_TournamentListList.Assign(const APB_TournamentListList: TList<TPB_TournamentList>);
var
  pbobj: TPB_TournamentList;
begin
  Clear;
  for pbobj in APB_TournamentListList do
    Add(TPB_TournamentList.Create(pbobj, TRUE));
end;

end.
