// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.Pot;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader;

type
  TPB_Pot = class(TProtobufBaseObject)
  private
    const
      FN_VALUE = 1;
      FN_MEMBERS = 2;

    var
      FValue: UINT32;
      FMembers: TArray<UINT32>;

    procedure SetValue(const AValue: UINT32);
    procedure SetMembers(const AValue: TArray<UINT32>);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Value: UINT32 read FValue write SetValue;
    property Members: TArray<UINT32> read FMembers write SetMembers;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_Pot.Destroy;
begin
  inherited;
end;
procedure TPB_Pot.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_VALUE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FValue := AProtobufReader.readUInt32;
      end;
      FN_MEMBERS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        SetLength(FMembers, Length(FMembers) + 1);
        FMembers[Length(FMembers)-1] := AProtobufReader.readUInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_Pot.SetValue(const AValue: UINT32);
begin
  FValue := AValue;
  ProtobufOutput.writeUInt32(FN_VALUE, AValue);
end;

procedure TPB_Pot.SetMembers(const AValue: TArray<UINT32>);
var
  C1: Integer;
begin
  FMembers := AValue;
  for C1 := 0 to Length(FMembers) - 1 do
    ProtobufOutput.writeUInt32(FN_MEMBERS, AValue[C1]);
end;

end.
