// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.StatusReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.Club,Poker.Protobufs.Objects.User,Poker.Protobufs.Objects.Game;

type
  TPB_StatusReply = class(TProtobufBaseObject)
  private
    const
      FN_CLUBS = 1;
      FN_USERS = 2;
      FN_SELF = 3;
      FN_GAMES = 4;

    var
      FClubs: TObjectList<TPB_Club>;
      FUsers: TObjectList<TPB_User>;
      FSelf: TPB_User;
      FGames: TObjectList<TPB_Game>;

    procedure SetSelf(const AValue: TPB_User);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Clubs: TObjectList<TPB_Club> read FClubs write FClubs;
    property Users: TObjectList<TPB_User> read FUsers write FUsers;
    property Self: TPB_User read FSelf write SetSelf;
    property Games: TObjectList<TPB_Game> read FGames write FGames;
  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


destructor TPB_StatusReply.Destroy;
begin
  if Assigned(FClubs) then
    FClubs.Free;
  if Assigned(FUsers) then
    FUsers.Free;
  if Assigned(FSelf) then FSelf.Free;
  if Assigned(FGames) then
    FGames.Free;
  inherited;
end;
procedure TPB_StatusReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  if not Assigned(FClubs) then
    FClubs := TObjectList<TPB_Club>.Create;

  if not Assigned(FUsers) then
    FUsers := TObjectList<TPB_User>.Create;

  if not Assigned(FGames) then
    FGames := TObjectList<TPB_Game>.Create;

  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_CLUBS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubs.Add(TPB_Club.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_USERS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FUsers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_SELF: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FSelf) then
          FSelf := TPB_User.Create;
        FSelf.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
      end;
      FN_GAMES: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FGames.Add(TPB_Game.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_StatusReply.SetSelf(const AValue: TPB_User);
begin
  FSelf := AValue;
  ProtobufOutput.writeMessage(FN_SELF, AValue.ProtobufOutput);
end;

end.
