// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HandHistory;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.PlayerHandHistory,Poker.Protobufs.Objects.MoveRow,Poker.Protobufs.Objects.Game;

type
  TPB_HandHistory = class(TProtobufBaseObject)
  private
    const
      kIdFieldNumber = 1;
      kSeqFieldNumber = 2;
      kTotalrakeFieldNumber = 3;
      kPlayersFieldNumber = 4;
      kCardsFieldNumber = 5;
      kEndtimeFieldNumber = 6;
      kBalanceChangesFieldNumber = 7;
      kMovesFieldNumber = 8;
      kDealerFieldNumber = 9;
      kGameFieldNumber = 10;
      kCurrentGameFieldNumber = 11;
      kRakeFieldNumber = 12;

    var
      FId: TBytes;
      FSeq: UINT32;
      FTotalrake: UINT32;
      FPlayers: TList<TPB_PlayerHandHistory>;
      FCards: TBytes;
      FEndtime: UINT32;
      FBalanceChanges: TList<Integer>;
      FMoves: TList<TPB_MoveRow>;
      FDealer: UINT32;
      FGame: TPB_Game;
      FCurrentGame: TGameType;
      FRake: Integer;
      _has_bits_: Integer;

    procedure set_has_MongoId;
    procedure clear_has_MongoId;
    procedure SetMongoId(const AValue: TBytes);
    procedure set_has_Seq;
    procedure clear_has_Seq;
    procedure SetSeq(const AValue: UINT32);
    procedure set_has_Totalrake;
    procedure clear_has_Totalrake;
    procedure SetTotalrake(const AValue: UINT32);
    procedure set_has_Players;
    procedure clear_has_Players;
    procedure set_has_Cards;
    procedure clear_has_Cards;
    procedure SetCards(const AValue: TBytes);
    procedure set_has_Endtime;
    procedure clear_has_Endtime;
    procedure SetEndtime(const AValue: UINT32);
    procedure set_has_BalanceChanges;
    procedure clear_has_BalanceChanges;
    procedure set_has_Moves;
    procedure clear_has_Moves;
    procedure set_has_Dealer;
    procedure clear_has_Dealer;
    procedure SetDealer(const AValue: UINT32);
    procedure set_has_Game;
    procedure clear_has_Game;
    procedure SetGame(const AValue: TPB_Game);
    procedure set_has_CurrentGame;
    procedure clear_has_CurrentGame;
    procedure SetCurrentGame(const AValue: TGameType);
    procedure set_has_Rake;
    procedure clear_has_Rake;
    procedure SetRake(const AValue: Integer);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
    procedure BalanceChangesNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
    procedure MovesNotifyEvent(Sender: TObject; const Item: TPB_MoveRow; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_HandHistory); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_HandHistory);

    // required bytes MongoId = 1;
    function has_MongoId: Boolean;
    procedure clear_MongoId;
    property MongoId: TBytes read FId write SetMongoId;

    // required uint32 Seq = 2;
    function has_Seq: Boolean;
    procedure clear_Seq;
    property Seq: UINT32 read FSeq write SetSeq;

    // required uint32 Totalrake = 3;
    function has_Totalrake: Boolean;
    procedure clear_Totalrake;
    property Totalrake: UINT32 read FTotalrake write SetTotalrake;

    // repeated FIXME Players = 4;
    function has_Players: Boolean;
    procedure clear_Players;
    property Players: TList<TPB_PlayerHandHistory> read FPlayers;

    // required bytes Cards = 5;
    function has_Cards: Boolean;
    procedure clear_Cards;
    property Cards: TBytes read FCards write SetCards;

    // required uint32 Endtime = 6;
    function has_Endtime: Boolean;
    procedure clear_Endtime;
    property Endtime: UINT32 read FEndtime write SetEndtime;

    // repeated int32 BalanceChanges = 7;
    function has_BalanceChanges: Boolean;
    procedure clear_BalanceChanges;
    property BalanceChanges: TList<Integer> read FBalanceChanges;

    // repeated FIXME Moves = 8;
    function has_Moves: Boolean;
    procedure clear_Moves;
    property Moves: TList<TPB_MoveRow> read FMoves;

    // required uint32 Dealer = 9;
    function has_Dealer: Boolean;
    procedure clear_Dealer;
    property Dealer: UINT32 read FDealer write SetDealer;

    // optional FIXME Game = 10;
    function has_Game: Boolean;
    procedure clear_Game;
    property Game: TPB_Game read FGame write SetGame;

    // optional FIXME CurrentGame = 11;
    function has_CurrentGame: Boolean;
    procedure clear_CurrentGame;
    property CurrentGame: TGameType read FCurrentGame write SetCurrentGame;

    // required int32 Rake = 12;
    function has_Rake: Boolean;
    procedure clear_Rake;
    property Rake: Integer read FRake write SetRake;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HandHistory.InitObjects;
begin
  inherited;
  FPlayers := TObjectList<TPB_PlayerHandHistory>.Create;
  FBalanceChanges := TList<Integer>.Create;
  FMoves := TObjectList<TPB_MoveRow>.Create;
end;
procedure TPB_HandHistory.HookNotifiers;
begin
  inherited;
  FPlayers.OnNotify := PlayersNotifyEvent;
  FBalanceChanges.OnNotify := BalanceChangesNotifyEvent;
  FMoves.OnNotify := MovesNotifyEvent;
end;

constructor TPB_HandHistory.Create(const AFrom: TPB_HandHistory);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_HandHistory.Destroy;
begin
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  if Assigned(FBalanceChanges) then
  begin
    FBalanceChanges.OnNotify := nil;
    FreeAndNil(FBalanceChanges);
  end;
  if Assigned(FMoves) then
  begin
    FMoves.OnNotify := nil;
    FreeAndNil(FMoves);
  end;
  if Assigned(FGame) then FreeAndNil(FGame);
  inherited;
end;

procedure TPB_HandHistory.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kIdFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FId := AProtobufReader.readBytes;
        set_has_MongoId;
      end;
      kSeqFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeq := AProtobufReader.readUInt32;
        set_has_Seq;
      end;
      kTotalrakeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FTotalrake := AProtobufReader.readUInt32;
        set_has_Totalrake;
      end;
      kPlayersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_PlayerHandHistory.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Players;
      end;
      kCardsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FCards := AProtobufReader.readBytes;
        set_has_Cards;
      end;
      kEndtimeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEndtime := AProtobufReader.readUInt32;
        set_has_Endtime;
      end;
      kBalanceChangesFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBalanceChanges.Add(AProtobufReader.readInt32);
        set_has_BalanceChanges;
      end;
      kMovesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FMoves.Add(TPB_MoveRow.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Moves;
      end;
      kDealerFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDealer := AProtobufReader.readUInt32;
        set_has_Dealer;
      end;
      kGameFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        if not Assigned(FGame) then
          FGame := TPB_Game.Create;
        FGame.LoadFromProtobufReader(AProtobufReader,AProtobufReader.readInt32);
        set_has_Game;
      end;
      kCurrentGameFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentGame := TGameType(AProtobufReader.readEnum);
        set_has_CurrentGame;
      end;
      kRakeFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FRake := AProtobufReader.readInt32;
        set_has_Rake;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HandHistory.MergeFrom(const from: TPB_HandHistory);
var
  temp3: TPB_PlayerHandHistory;
  temp6: Integer;
  temp7: TPB_MoveRow;
begin
  if (from.has_MongoId) then
    SetMongoId(from.MongoId);
  if (from.has_Seq) then
    SetSeq(from.Seq);
  if (from.has_Totalrake) then
    SetTotalrake(from.Totalrake);
  for temp3 in from.Players do
    FPlayers.Add(TPB_PlayerHandHistory.Create(temp3));
  if (from.has_Cards) then
    SetCards(from.Cards);
  if (from.has_Endtime) then
    SetEndtime(from.Endtime);
  for temp6 in from.BalanceChanges do
    FBalanceChanges.Add(temp6); // FIXME?
  for temp7 in from.Moves do
    FMoves.Add(TPB_MoveRow.Create(temp7));
  if (from.has_Dealer) then
    SetDealer(from.Dealer);
  if (from.has_Game) then
    FGame.MergeFrom(from.Game);
  if (from.has_CurrentGame) then
    SetCurrentGame(from.CurrentGame);
  if (from.has_Rake) then
    SetRake(from.Rake);
end;

procedure TPB_HandHistory.clear_MongoId;
begin
  SetLength(FId,0);
  clear_has_MongoId;
end;

function TPB_HandHistory.has_MongoId: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_HandHistory.set_has_MongoId;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_HandHistory.clear_has_MongoId;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_HandHistory.SetMongoId(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FId,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FId[C1] := AValue[C1];
  ProtobufOutput.writeBytes(kIdFieldNumber, AValue);
end;

procedure TPB_HandHistory.clear_Seq;
begin
  FSeq := 0;
  clear_has_Seq;
end;

function TPB_HandHistory.has_Seq: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_HandHistory.set_has_Seq;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_HandHistory.clear_has_Seq;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_HandHistory.SetSeq(const AValue: UINT32);
begin
  FSeq := AValue;
  ProtobufOutput.writeUInt32(kSeqFieldNumber, AValue);
  set_has_Seq;
end;

procedure TPB_HandHistory.clear_Totalrake;
begin
  FTotalrake := 0;
  clear_has_Totalrake;
end;

function TPB_HandHistory.has_Totalrake: Boolean;
begin
  Result := (_has_bits_ and 4) > 0;
end;

procedure TPB_HandHistory.set_has_Totalrake;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_HandHistory.clear_has_Totalrake;
begin
  _has_bits_ := _has_bits_ and not 4;
end;

procedure TPB_HandHistory.SetTotalrake(const AValue: UINT32);
begin
  FTotalrake := AValue;
  ProtobufOutput.writeUInt32(kTotalrakeFieldNumber, AValue);
  set_has_Totalrake;
end;

procedure TPB_HandHistory.clear_Players;
begin
  FPlayers.Clear;
  clear_has_Players;
end;

function TPB_HandHistory.has_Players: Boolean;
begin
  Result := (_has_bits_ and 8) > 0;
end;

procedure TPB_HandHistory.set_has_Players;
begin
  _has_bits_ := _has_bits_ or 8;
end;

procedure TPB_HandHistory.clear_has_Players;
begin
  _has_bits_ := _has_bits_ and not 8;
end;

procedure TPB_HandHistory.PlayersNotifyEvent(Sender: TObject; const Item: TPB_PlayerHandHistory; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kPlayersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_HandHistory.clear_Cards;
begin
  SetLength(FCards,0);
  clear_has_Cards;
end;

function TPB_HandHistory.has_Cards: Boolean;
begin
  Result := (_has_bits_ and 16) > 0;
end;

procedure TPB_HandHistory.set_has_Cards;
begin
  _has_bits_ := _has_bits_ or 16;
end;

procedure TPB_HandHistory.clear_has_Cards;
begin
  _has_bits_ := _has_bits_ and not 16;
end;

procedure TPB_HandHistory.SetCards(const AValue: TBytes);
var
  C1: Integer;
begin
  SetLength(FCards,Length(AValue));
  for C1 := 0 to Length(AValue) - 1 do
    FCards[C1] := AValue[C1];
  ProtobufOutput.writeBytes(kCardsFieldNumber, AValue);
end;

procedure TPB_HandHistory.clear_Endtime;
begin
  FEndtime := 0;
  clear_has_Endtime;
end;

function TPB_HandHistory.has_Endtime: Boolean;
begin
  Result := (_has_bits_ and 32) > 0;
end;

procedure TPB_HandHistory.set_has_Endtime;
begin
  _has_bits_ := _has_bits_ or 32;
end;

procedure TPB_HandHistory.clear_has_Endtime;
begin
  _has_bits_ := _has_bits_ and not 32;
end;

procedure TPB_HandHistory.SetEndtime(const AValue: UINT32);
begin
  FEndtime := AValue;
  ProtobufOutput.writeUInt32(kEndtimeFieldNumber, AValue);
  set_has_Endtime;
end;

procedure TPB_HandHistory.clear_BalanceChanges;
begin
  FBalanceChanges.Clear;
  clear_has_BalanceChanges;
end;

function TPB_HandHistory.has_BalanceChanges: Boolean;
begin
  Result := (_has_bits_ and 64) > 0;
end;

procedure TPB_HandHistory.set_has_BalanceChanges;
begin
  _has_bits_ := _has_bits_ or 64;
end;

procedure TPB_HandHistory.clear_has_BalanceChanges;
begin
  _has_bits_ := _has_bits_ and not 64;
end;

procedure TPB_HandHistory.BalanceChangesNotifyEvent(Sender: TObject; const Item: Integer; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeInt32(kBalanceChangesFieldNumber,Item);
end;

procedure TPB_HandHistory.clear_Moves;
begin
  FMoves.Clear;
  clear_has_Moves;
end;

function TPB_HandHistory.has_Moves: Boolean;
begin
  Result := (_has_bits_ and 128) > 0;
end;

procedure TPB_HandHistory.set_has_Moves;
begin
  _has_bits_ := _has_bits_ or 128;
end;

procedure TPB_HandHistory.clear_has_Moves;
begin
  _has_bits_ := _has_bits_ and not 128;
end;

procedure TPB_HandHistory.MovesNotifyEvent(Sender: TObject; const Item: TPB_MoveRow; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kMovesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_HandHistory.clear_Dealer;
begin
  FDealer := 0;
  clear_has_Dealer;
end;

function TPB_HandHistory.has_Dealer: Boolean;
begin
  Result := (_has_bits_ and 256) > 0;
end;

procedure TPB_HandHistory.set_has_Dealer;
begin
  _has_bits_ := _has_bits_ or 256;
end;

procedure TPB_HandHistory.clear_has_Dealer;
begin
  _has_bits_ := _has_bits_ and not 256;
end;

procedure TPB_HandHistory.SetDealer(const AValue: UINT32);
begin
  FDealer := AValue;
  ProtobufOutput.writeUInt32(kDealerFieldNumber, AValue);
  set_has_Dealer;
end;

procedure TPB_HandHistory.clear_Game;
begin
  FreeAndNil(FGame);
  clear_has_Game;
end;

function TPB_HandHistory.has_Game: Boolean;
begin
  Result := (_has_bits_ and 512) > 0;
end;

procedure TPB_HandHistory.set_has_Game;
begin
  _has_bits_ := _has_bits_ or 512;
end;

procedure TPB_HandHistory.clear_has_Game;
begin
  _has_bits_ := _has_bits_ and not 512;
end;

procedure TPB_HandHistory.SetGame(const AValue: TPB_Game);
begin
  FGame := AValue;
  ProtobufOutput.writeMessage(kGameFieldNumber, AValue.ProtobufOutput);
  set_has_Game;
end;

procedure TPB_HandHistory.clear_CurrentGame;
begin
  FCurrentGame := TGameType(0);
  clear_has_CurrentGame;
end;

function TPB_HandHistory.has_CurrentGame: Boolean;
begin
  Result := (_has_bits_ and 1024) > 0;
end;

procedure TPB_HandHistory.set_has_CurrentGame;
begin
  _has_bits_ := _has_bits_ or 1024;
end;

procedure TPB_HandHistory.clear_has_CurrentGame;
begin
  _has_bits_ := _has_bits_ and not 1024;
end;

procedure TPB_HandHistory.SetCurrentGame(const AValue: TGameType);
begin
  FCurrentGame := AValue;
  ProtobufOutput.writeInt32(kCurrentGameFieldNumber, Integer(AValue));
  set_has_CurrentGame;
end;

procedure TPB_HandHistory.clear_Rake;
begin
  FRake := 0;
  clear_has_Rake;
end;

function TPB_HandHistory.has_Rake: Boolean;
begin
  Result := (_has_bits_ and 2048) > 0;
end;

procedure TPB_HandHistory.set_has_Rake;
begin
  _has_bits_ := _has_bits_ or 2048;
end;

procedure TPB_HandHistory.clear_has_Rake;
begin
  _has_bits_ := _has_bits_ and not 2048;
end;

procedure TPB_HandHistory.SetRake(const AValue: Integer);
begin
  FRake := AValue;
  ProtobufOutput.writeInt32(kRakeFieldNumber, AValue);
  set_has_Rake;
end;

end.
