// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.HelloParams;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.UpdateFileInfo;

type
  TPB_HelloParams = class(TProtobufBaseObject)
  private
    const
      kDebugFieldNumber = 1;
      kFilesFieldNumber = 2;

    var
      FDebug: Boolean;
      FFiles: TList<TPB_UpdateFileInfo>;
      _has_bits_: Integer;

    procedure set_has_Debug;
    procedure clear_has_Debug;
    procedure SetDebug(const AValue: Boolean);
    procedure set_has_Files;
    procedure clear_has_Files;
    procedure FilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_HelloParams); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_HelloParams);
    function IsInitialized: Boolean; override;

    // required bool Debug = 1;
    function has_Debug: Boolean;
    procedure clear_Debug;
    property Debug: Boolean read FDebug write SetDebug;

    // repeated FIXME Files = 2;
    function has_Files: Boolean;
    procedure clear_Files;
    property Files: TList<TPB_UpdateFileInfo> read FFiles;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_HelloParams.InitObjects;
begin
  inherited;
  FFiles := TObjectList<TPB_UpdateFileInfo>.Create;
end;
procedure TPB_HelloParams.HookNotifiers;
begin
  inherited;
  FFiles.OnNotify := FilesNotifyEvent;
end;

constructor TPB_HelloParams.Create(const AFrom: TPB_HelloParams);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_HelloParams.Destroy;
begin
  if Assigned(FFiles) then
  begin
    FFiles.OnNotify := nil;
    FreeAndNil(FFiles);
  end;
  inherited;
end;

procedure TPB_HelloParams.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kDebugFieldNumber: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDebug := AProtobufReader.readBoolean;
        set_has_Debug;
      end;
      kFilesFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FFiles.Add(TPB_UpdateFileInfo.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Files;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_HelloParams.MergeFrom(const from: TPB_HelloParams);
var
  temp1: TPB_UpdateFileInfo;
begin
  if (from.has_Debug) then
    SetDebug(from.Debug);
  for temp1 in from.Files do
    FFiles.Add(TPB_UpdateFileInfo.Create(temp1));
end;

function TPB_HelloParams.IsInitialized: Boolean;
var
  temp: TProtobufBaseObject;
begin
  if ((_has_bits_ and $1) <> $1) Then Exit(false);
  for temp in Files do
    if (not temp.IsInitialized) then Exit(false);
  Exit(True);
end;

procedure TPB_HelloParams.clear_Debug;
begin
  FDebug := false;
  clear_has_Debug;
end;

function TPB_HelloParams.has_Debug: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_HelloParams.set_has_Debug;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_HelloParams.clear_has_Debug;
begin
  _has_bits_ := _has_bits_ and not 1;
end;

procedure TPB_HelloParams.SetDebug(const AValue: Boolean);
begin
  Assert(!has_Debug);
  FDebug := AValue;
  ProtobufOutput.writeBoolean(kDebugFieldNumber, AValue);
  set_has_Debug;
end;

procedure TPB_HelloParams.clear_Files;
begin
  FFiles.Clear;
  clear_has_Files;
end;

function TPB_HelloParams.has_Files: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_HelloParams.set_has_Files;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_HelloParams.clear_has_Files;
begin
  _has_bits_ := _has_bits_ and not 2;
end;

procedure TPB_HelloParams.FilesNotifyEvent(Sender: TObject; const Item: TPB_UpdateFileInfo; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kFilesFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
