// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit Poker.Protobufs.Objects.TableStatsReplies;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, Poker.Protobufs.Objects.Base, Poker.Protobufs.Reader,Poker.Protobufs.Objects.TableStatsReply,Poker.Protobufs.Objects.User,Poker.Protobufs.Objects.ClubStatsReply;

type
  TPB_TableStatsReplies = class(TProtobufBaseObject)
  private
    const
      kReplyFieldNumber = 1;
      kPlayersFieldNumber = 2;
      kClubStatsFieldNumber = 3;

    var
      FReply: TList<TPB_TableStatsReply>;
      FPlayers: TList<TPB_User>;
      FClubStats: TList<TPB_ClubStatsReply>;
      _has_bits_: Integer;

    procedure set_has_Reply;
    procedure clear_has_Reply;
    procedure set_has_Players;
    procedure clear_has_Players;
    procedure set_has_ClubStats;
    procedure clear_has_ClubStats;
    procedure ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
    procedure PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
    procedure ClubStatsNotifyEvent(Sender: TObject; const Item: TPB_ClubStatsReply; Action: TCollectionNotification);

  protected
    procedure InitObjects; override;
    procedure HookNotifiers; override;

  public
    constructor Create(const AFrom: TPB_TableStatsReplies); overload;
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    procedure MergeFrom(const from: TPB_TableStatsReplies);

    // LABEL TYPE Reply = 1;
    function has_Reply: Boolean;
    procedure clear_Reply;
    property Reply: TList<TPB_TableStatsReply> read FReply;

    // LABEL TYPE Players = 2;
    function has_Players: Boolean;
    procedure clear_Players;
    property Players: TList<TPB_User> read FPlayers;

    // LABEL TYPE ClubStats = 3;
    function has_ClubStats: Boolean;
    procedure clear_ClubStats;
    property ClubStats: TList<TPB_ClubStatsReply> read FClubStats;

  end;

implementation

uses
  pbPublic, Poker.Common.Misc;


procedure TPB_TableStatsReplies.InitObjects;
begin
  inherited;
  FReply := TObjectList<TPB_TableStatsReply>.Create;
  FPlayers := TObjectList<TPB_User>.Create;
  FClubStats := TObjectList<TPB_ClubStatsReply>.Create;
end;
procedure TPB_TableStatsReplies.HookNotifiers;
begin
  inherited;
  FReply.OnNotify := ReplyNotifyEvent;
  FPlayers.OnNotify := PlayersNotifyEvent;
  FClubStats.OnNotify := ClubStatsNotifyEvent;
end;

constructor TPB_TableStatsReplies.Create(const AFrom: TPB_TableStatsReplies);
begin
  inherited Create;
  MergeFrom(AFrom);
end;

destructor TPB_TableStatsReplies.Destroy;
begin
  if Assigned(FReply) then
  begin
    FReply.OnNotify := nil;
    FreeAndNil(FReply);
  end;
  if Assigned(FPlayers) then
  begin
    FPlayers.OnNotify := nil;
    FreeAndNil(FPlayers);
  end;
  if Assigned(FClubStats) then
  begin
    FClubStats.OnNotify := nil;
    FreeAndNil(FClubStats);
  end;
  inherited;
end;

procedure TPB_TableStatsReplies.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      kReplyFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FReply.Add(TPB_TableStatsReply.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Reply;
      end;
      kPlayersFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPlayers.Add(TPB_User.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_Players;
      end;
      kClubStatsFieldNumber: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FClubStats.Add(TPB_ClubStatsReply.Create(AProtobufReader,AProtobufReader.readInt32));
        set_has_ClubStats;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;

procedure TPB_TableStatsReplies.MergeFrom(const from: TPB_TableStatsReplies);
var
  temp0: TPB_TableStatsReply;
  temp1: TPB_User;
  temp2: TPB_ClubStatsReply;
begin
  for temp0 in from.Reply do
    FReply.Add(TPB_TableStatsReply.Create(temp0));
  for temp1 in from.Players do
    FPlayers.Add(TPB_User.Create(temp1));
  for temp2 in from.ClubStats do
    FClubStats.Add(TPB_ClubStatsReply.Create(temp2));
end;

procedure TPB_TableStatsReplies.clear_Reply;
begin
  FReply.Clear;
  clear_has_Reply;
end;

function TPB_TableStatsReplies.has_Reply: Boolean;
begin
  Result := (_has_bits_ and 1) > 0;
end;

procedure TPB_TableStatsReplies.set_has_Reply;
begin
  _has_bits_ := _has_bits_ or 1;
end;

procedure TPB_TableStatsReplies.clear_has_Reply;
begin
  _has_bits_ := _has_bits_ xor 1;
end;

procedure TPB_TableStatsReplies.ReplyNotifyEvent(Sender: TObject; const Item: TPB_TableStatsReply; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kReplyFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_TableStatsReplies.clear_Players;
begin
  FPlayers.Clear;
  clear_has_Players;
end;

function TPB_TableStatsReplies.has_Players: Boolean;
begin
  Result := (_has_bits_ and 2) > 0;
end;

procedure TPB_TableStatsReplies.set_has_Players;
begin
  _has_bits_ := _has_bits_ or 2;
end;

procedure TPB_TableStatsReplies.clear_has_Players;
begin
  _has_bits_ := _has_bits_ xor 2;
end;

procedure TPB_TableStatsReplies.PlayersNotifyEvent(Sender: TObject; const Item: TPB_User; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kPlayersFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

procedure TPB_TableStatsReplies.clear_ClubStats;
begin
  FClubStats.Clear;
  clear_has_ClubStats;
end;

function TPB_TableStatsReplies.has_ClubStats: Boolean;
begin
  Result := (_has_bits_ and 4) > 0;
end;

procedure TPB_TableStatsReplies.set_has_ClubStats;
begin
  _has_bits_ := _has_bits_ or 4;
end;

procedure TPB_TableStatsReplies.clear_has_ClubStats;
begin
  _has_bits_ := _has_bits_ xor 4;
end;

procedure TPB_TableStatsReplies.ClubStatsNotifyEvent(Sender: TObject; const Item: TPB_ClubStatsReply; Action: TCollectionNotification);
begin
  Assert(Action = cnAdded);
  ProtobufOutput.writeTag(kClubStatsFieldNumber,WIRETYPE_LENGTH_DELIMITED);
  ProtobufOutput.writeRawVarint32(Item.ProtobufOutput.getSerializedSize);
  Item.ProtobufOutput.writeTo(ProtobufOutput);
end;

end.
