// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_SetAvatarReply;

interface

uses
  WinApi.Windows, System.Classes, System.SysUtils, System.Generics.Collections, pbOutput, uProtobufBaseObject, uProtobufReader;

type
  TSetAvatarStatus = (saSuccess = 1,saNotFound = 2);
  TPB_SetAvatarReply = class(TProtobufBaseObject)
  private
    const
      FN_STATUS = 1;

    var
      FStatus: TSetAvatarStatus;

    procedure SetStatus(const AValue: TSetAvatarStatus);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Status: TSetAvatarStatus read FStatus write SetStatus;
  end;

  TPB_SetAvatarReplys = TObjectList<TPB_SetAvatarReply>;

implementation

uses
  pbPublic, uCommon;


destructor TPB_SetAvatarReply.Destroy;
begin
  inherited;
end;
procedure TPB_SetAvatarReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_STATUS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FStatus := TSetAvatarStatus(AProtobufReader.readEnum);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_SetAvatarReply.SetStatus(const AValue: TSetAvatarStatus);
begin
  FStatus := AValue;
  ProtobufOutput.writeInt32(FN_STATUS, Integer(AValue));
end;

end.
