// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_TableEvent;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, uProtobufBaseObject, uProtobufReader,uPB_PotInfo;

type
  TTableEventType = (teFold = 1,teSit = 2,teStandUp = 3,teWinning = 4,teDealing = 5,teCheck = 6,teCall = 7,teRaise = 8,teAllIn = 9,teFlop = 10,teTurn = 11,teRiver = 12);
  TPB_TableEvent = class(TProtobufBaseObject)
  private
    const
      FN_EVENT = 1;
      FN_SEAT = 2;
      FN_POTS = 4;

    var
      FEvent: TTableEventType;
      FSeat: Integer;
      FPots: TObjectList<TPB_PotInfo>;

    procedure SetEvent(const AValue: TTableEventType);
    procedure SetSeat(const AValue: Integer);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Event: TTableEventType read FEvent write SetEvent;
    property Seat: Integer read FSeat write SetSeat;
    property Pots: TObjectList<TPB_PotInfo> read FPots write FPots;
  end;

implementation

uses
  pbPublic, uCommon;


destructor TPB_TableEvent.Destroy;
begin
  if Assigned(FPots) then
    FPots.Free;
  inherited;
end;
procedure TPB_TableEvent.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  if not Assigned(FPots) then
    FPots := TObjectList<TPB_PotInfo>.Create;

  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_EVENT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FEvent := TTableEventType(AProtobufReader.readEnum);
      end;
      FN_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeat := AProtobufReader.readInt32;
      end;
      FN_POTS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FPots.Add(TPB_PotInfo.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_TableEvent.SetEvent(const AValue: TTableEventType);
begin
  FEvent := AValue;
  ProtobufOutput.writeInt32(FN_EVENT, Integer(AValue));
end;

procedure TPB_TableEvent.SetSeat(const AValue: Integer);
begin
  FSeat := AValue;
  ProtobufOutput.writeInt32(FN_SEAT, AValue);
end;

end.
