// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_ChangeMailReply;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, uProtobufBaseObject, uProtobufReader;

type
  TChangeMailStatus = (cmSuccess = 0,cmDuplicateMail = 1,cmInvalidEmail = 2);
  TPB_ChangeMailReply = class(TProtobufBaseObject)
  private
    const
      FN_STATUS = 1;

    var
      FStatus: TChangeMailStatus;

    procedure SetStatus(const AValue: TChangeMailStatus);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property Status: TChangeMailStatus read FStatus write SetStatus;
  end;

implementation

uses
  pbPublic, uCommon;


destructor TPB_ChangeMailReply.Destroy;
begin
  inherited;
end;
procedure TPB_ChangeMailReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_STATUS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FStatus := TChangeMailStatus(AProtobufReader.readEnum);
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_ChangeMailReply.SetStatus(const AValue: TChangeMailStatus);
begin
  FStatus := AValue;
  ProtobufOutput.writeInt32(FN_STATUS, Integer(AValue));
end;

end.
