// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_TableStatus;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, uProtobufBaseObject, uProtobufReader,uPB_SeatInfo;

type
  TTableState = (tsIdle = 1,tsPreFlop = 2,tsFlop = 3,tsTurn = 4,tsRiver = 5,tsWinning = 6,tsWinning2 = 7);
  TPB_TableStatus = class(TProtobufBaseObject)
  private
    const
      FN_TABLE_MONGO_ID = 1;
      FN_SEATS = 2;
      FN_STATE = 3;
      FN_DEALER = 4;
      FN_CURRENT_SEAT = 5;
      FN_BETS = 6;
      FN_FLOP = 7;
      FN_TURN = 8;
      FN_RIVER = 9;
      FN_POTS = 10;
      FN_LOCKED = 11;
      FN_SEQ = 12;
      FN_MINIMUM_BET = 13;
      FN_SMALL_BLIND = 14;
      FN_BIG_BLIND = 15;
      FN_HANDID = 16;
      FN_BET_LIMIT = 17;

    var
      FTableMongoId: TBytes;
      FSeats: TObjectList<TPB_SeatInfo>;
      FState: TTableState;
      FDealer: Integer;
      FCurrentSeat: Integer;
      FBets: TArray<Integer>;
      FFlop: TBytes;
      FTurn: TBytes;
      FRiver: TBytes;
      FPots: TArray<Integer>;
      FLocked: Boolean;
      FSeq: Integer;
      FMinimumBet: Integer;
      FSmallBlind: Integer;
      FBigBlind: Integer;
      FHandid: UINT32;
      FBetLimit: UINT32;

    procedure SetTableMongoId(const AValue: TBytes);
    procedure SetState(const AValue: TTableState);
    procedure SetDealer(const AValue: Integer);
    procedure SetCurrentSeat(const AValue: Integer);
    procedure SetBets(const AValue: TArray<Integer>);
    procedure SetFlop(const AValue: TBytes);
    procedure SetTurn(const AValue: TBytes);
    procedure SetRiver(const AValue: TBytes);
    procedure SetPots(const AValue: TArray<Integer>);
    procedure SetLocked(const AValue: Boolean);
    procedure SetSeq(const AValue: Integer);
    procedure SetMinimumBet(const AValue: Integer);
    procedure SetSmallBlind(const AValue: Integer);
    procedure SetBigBlind(const AValue: Integer);
    procedure SetHandid(const AValue: UINT32);
    procedure SetBetLimit(const AValue: UINT32);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property TableMongoId: TBytes read FTableMongoId write SetTableMongoId;
    property Seats: TObjectList<TPB_SeatInfo> read FSeats write FSeats;
    property State: TTableState read FState write SetState;
    property Dealer: Integer read FDealer write SetDealer;
    property CurrentSeat: Integer read FCurrentSeat write SetCurrentSeat;
    property Bets: TArray<Integer> read FBets write SetBets;
    property Flop: TBytes read FFlop write SetFlop;
    property Turn: TBytes read FTurn write SetTurn;
    property River: TBytes read FRiver write SetRiver;
    property Pots: TArray<Integer> read FPots write SetPots;
    property Locked: Boolean read FLocked write SetLocked;
    property Seq: Integer read FSeq write SetSeq;
    property MinimumBet: Integer read FMinimumBet write SetMinimumBet;
    property SmallBlind: Integer read FSmallBlind write SetSmallBlind;
    property BigBlind: Integer read FBigBlind write SetBigBlind;
    property Handid: UINT32 read FHandid write SetHandid;
    property BetLimit: UINT32 read FBetLimit write SetBetLimit;
  end;

implementation

uses
  pbPublic, uCommon;


destructor TPB_TableStatus.Destroy;
begin
  if Assigned(FSeats) then
    FSeats.Free;
  inherited;
end;
procedure TPB_TableStatus.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  if not Assigned(FSeats) then
    FSeats := TObjectList<TPB_SeatInfo>.Create;

  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_TABLE_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FTableMongoId);
      end;
      FN_SEATS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FSeats.Add(TPB_SeatInfo.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_STATE: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FState := TTableState(AProtobufReader.readEnum);
      end;
      FN_DEALER: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDealer := AProtobufReader.readInt32;
      end;
      FN_CURRENT_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentSeat := AProtobufReader.readInt32;
      end;
      FN_BETS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        SetLength(FBets, Length(FBets) + 1);
        FBets[Length(FBets)-1] := AProtobufReader.readInt32;
      end;
      FN_FLOP: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FFlop);
      end;
      FN_TURN: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FTurn);
      end;
      FN_RIVER: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FRiver);
      end;
      FN_POTS: begin
        Assert(wire_type = WIRETYPE_VARINT);
        SetLength(FPots, Length(FPots) + 1);
        FPots[Length(FPots)-1] := AProtobufReader.readInt32;
      end;
      FN_LOCKED: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FLocked := AProtobufReader.readBoolean;
      end;
      FN_SEQ: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSeq := AProtobufReader.readInt32;
      end;
      FN_MINIMUM_BET: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FMinimumBet := AProtobufReader.readInt32;
      end;
      FN_SMALL_BLIND: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FSmallBlind := AProtobufReader.readInt32;
      end;
      FN_BIG_BLIND: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBigBlind := AProtobufReader.readInt32;
      end;
      FN_HANDID: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FHandid := AProtobufReader.readUInt32;
      end;
      FN_BET_LIMIT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FBetLimit := AProtobufReader.readUInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_TableStatus.SetTableMongoId(const AValue: TBytes);
begin
  FTableMongoId := AValue;
  ProtobufOutput.writeBytes(FN_TABLE_MONGO_ID, AValue);
end;

procedure TPB_TableStatus.SetState(const AValue: TTableState);
begin
  FState := AValue;
  ProtobufOutput.writeInt32(FN_STATE, Integer(AValue));
end;

procedure TPB_TableStatus.SetDealer(const AValue: Integer);
begin
  FDealer := AValue;
  ProtobufOutput.writeInt32(FN_DEALER, AValue);
end;

procedure TPB_TableStatus.SetCurrentSeat(const AValue: Integer);
begin
  FCurrentSeat := AValue;
  ProtobufOutput.writeInt32(FN_CURRENT_SEAT, AValue);
end;

procedure TPB_TableStatus.SetBets(const AValue: TArray<Integer>);
var
  C1: Integer;
begin
  FBets := AValue;
  for C1 := 0 to Length(FBets) - 1 do
    ProtobufOutput.writeInt32(FN_BETS, AValue[C1]);
end;

procedure TPB_TableStatus.SetFlop(const AValue: TBytes);
begin
  FFlop := AValue;
  ProtobufOutput.writeBytes(FN_FLOP, AValue);
end;

procedure TPB_TableStatus.SetTurn(const AValue: TBytes);
begin
  FTurn := AValue;
  ProtobufOutput.writeBytes(FN_TURN, AValue);
end;

procedure TPB_TableStatus.SetRiver(const AValue: TBytes);
begin
  FRiver := AValue;
  ProtobufOutput.writeBytes(FN_RIVER, AValue);
end;

procedure TPB_TableStatus.SetPots(const AValue: TArray<Integer>);
var
  C1: Integer;
begin
  FPots := AValue;
  for C1 := 0 to Length(FPots) - 1 do
    ProtobufOutput.writeInt32(FN_POTS, AValue[C1]);
end;

procedure TPB_TableStatus.SetLocked(const AValue: Boolean);
begin
  FLocked := AValue;
  ProtobufOutput.writeBoolean(FN_LOCKED, AValue);
end;

procedure TPB_TableStatus.SetSeq(const AValue: Integer);
begin
  FSeq := AValue;
  ProtobufOutput.writeInt32(FN_SEQ, AValue);
end;

procedure TPB_TableStatus.SetMinimumBet(const AValue: Integer);
begin
  FMinimumBet := AValue;
  ProtobufOutput.writeInt32(FN_MINIMUM_BET, AValue);
end;

procedure TPB_TableStatus.SetSmallBlind(const AValue: Integer);
begin
  FSmallBlind := AValue;
  ProtobufOutput.writeInt32(FN_SMALL_BLIND, AValue);
end;

procedure TPB_TableStatus.SetBigBlind(const AValue: Integer);
begin
  FBigBlind := AValue;
  ProtobufOutput.writeInt32(FN_BIG_BLIND, AValue);
end;

procedure TPB_TableStatus.SetHandid(const AValue: UINT32);
begin
  FHandid := AValue;
  ProtobufOutput.writeUInt32(FN_HANDID, AValue);
end;

procedure TPB_TableStatus.SetBetLimit(const AValue: UINT32);
begin
  FBetLimit := AValue;
  ProtobufOutput.writeUInt32(FN_BET_LIMIT, AValue);
end;

end.
