// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_ListClubsReply;
interface
uses
  WinApi.Windows, System.Classes, System.SysUtils, System.Generics.Collections, pbOutput, uProtobufBaseObject, uProtobufReader,uPB_Club;
type
  TPB_ListClubsReply = class(TProtobufBaseObject)
  private
    const
      FN_clubs = 1;
    var
      Fclubs: TPB_Clubs;
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;
    function GetProtobuf: TProtoBufOutput; override;

    property clubs: TPB_Clubs read Fclubs;
  end;
  TPB_ListClubsReplys = TObjectList<TPB_ListClubsReply>;
  implementation
uses
  pbInput,pbPublic, EncdDecd;
{ TPBR_ListClubsReply }
destructor TPB_ListClubsReply.Destroy;
begin
  Fclubs.Free;
  inherited;
end;
procedure TPB_ListClubsReply.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
        FN_clubs:
          begin
            Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
            if not Assigned(Fclubs) then
              Fclubs := TPB_Clubs.Create;
            Fclubs.Add(TPB_Club.Create(AProtobufReader,AProtobufReader.readInt32));
          end;
      else
        AProtobufReader.skipField(tag);
    end;
  end;
end;
function TPB_ListClubsReply.GetProtobuf: TProtoBufOutput;
var
  pboutput: TProtoBufOutput;
begin
  pboutput := TProtoBufOutput.Create;
  result := pboutput;
end;
end.
