// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_TableStatus;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, uProtobufBaseObject, uProtobufReader,uPB_SeatInfo;

type
  TPB_TableStatus = class(TProtobufBaseObject)
  private
    const
      FN_TABLE_MONGO_ID = 1;
      FN_SEATS = 2;
      FN_STATE = 3;
      FN_DEALER = 4;
      FN_CURRENT_SEAT = 5;

    var
      FTableMongoId: TBytes;
      FSeats: TObjectList<TPB_SeatInfo>;
      FState: String;
      FDealer: Integer;
      FCurrentSeat: Integer;

    procedure SetTableMongoId(const AValue: TBytes);
    procedure SetState(const AValue: String);
    procedure SetDealer(const AValue: Integer);
    procedure SetCurrentSeat(const AValue: Integer);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property TableMongoId: TBytes read FTableMongoId write SetTableMongoId;
    property Seats: TObjectList<TPB_SeatInfo> read FSeats write FSeats;
    property State: String read FState write SetState;
    property Dealer: Integer read FDealer write SetDealer;
    property CurrentSeat: Integer read FCurrentSeat write SetCurrentSeat;
  end;

implementation

uses
  pbPublic, uCommon;


destructor TPB_TableStatus.Destroy;
begin
  if Assigned(FSeats) then
    FSeats.Free;
  inherited;
end;
procedure TPB_TableStatus.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  if not Assigned(FSeats) then
    FSeats := TObjectList<TPB_SeatInfo>.Create;

  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_TABLE_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AprotobufReader.readBytes(FTableMongoId);
      end;
      FN_SEATS: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FSeats.Add(TPB_SeatInfo.Create(AProtobufReader,AProtobufReader.readInt32));
      end;
      FN_STATE: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        FState := String(AProtobufReader.readUtf8String);
      end;
      FN_DEALER: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FDealer := AProtobufReader.readInt32;
      end;
      FN_CURRENT_SEAT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FCurrentSeat := AProtobufReader.readInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_TableStatus.SetTableMongoId(const AValue: TBytes);
begin
  FTableMongoId := AValue;
  ProtobufOutput.writeBytes(FN_TABLE_MONGO_ID, AValue);
end;

procedure TPB_TableStatus.SetState(const AValue: String);
begin
  FState := AValue;
  ProtobufOutput.writeString(FN_STATE, AValue);
end;

procedure TPB_TableStatus.SetDealer(const AValue: Integer);
begin
  FDealer := AValue;
  ProtobufOutput.writeInt32(FN_DEALER, AValue);
end;

procedure TPB_TableStatus.SetCurrentSeat(const AValue: Integer);
begin
  FCurrentSeat := AValue;
  ProtobufOutput.writeInt32(FN_CURRENT_SEAT, AValue);
end;

end.
