// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

unit uPB_PutChips;

interface

uses
  Classes, SysUtils, {$IFNDEF FPC}System.Generics.Collections{$ELSE}Contnrs{$ENDIF}, pbOutput, uProtobufBaseObject, uProtobufReader;

type
  TPB_PutChips = class(TProtobufBaseObject)
  private
    const
      FN_TABLE_MONGO_ID = 1;
      FN_CHIP_AMOUNT = 2;

    var
      FTableMongoId: TBytes;
      FChipAmount: Integer;

    procedure SetTableMongoId(const AValue: TBytes);
    procedure SetChipAmount(const AValue: Integer);
  public
    destructor Destroy; override;
    procedure LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer); override;

    property TableMongoId: TBytes read FTableMongoId write SetTableMongoId;
    property ChipAmount: Integer read FChipAmount write SetChipAmount;
  end;

implementation

uses
  pbPublic, uCommon;


destructor TPB_PutChips.Destroy;
begin
  inherited;
end;
procedure TPB_PutChips.LoadFromProtobufReader(const AProtobufReader: TProtobufReader; const ASize: Integer);
var
  tag,field_number,wire_type,endpos : Integer;
begin
  endpos := AProtobufReader.getPos + ASize;
  while (AProtobufReader.getPos < endpos) and
        (AProtobufReader.GetNext(tag, wire_type, field_number)) do begin
    case field_number of
      FN_TABLE_MONGO_ID: begin
        Assert(wire_type = WIRETYPE_LENGTH_DELIMITED);
        AProtobufReader.readBytes(FTableMongoId);
      end;
      FN_CHIP_AMOUNT: begin
        Assert(wire_type = WIRETYPE_VARINT);
        FChipAmount := AProtobufReader.readInt32;
      end;
    else
      AProtobufReader.skipField(tag);
    end;
  end;
end;
procedure TPB_PutChips.SetTableMongoId(const AValue: TBytes);
begin
  FTableMongoId := AValue;
  ProtobufOutput.writeBytes(FN_TABLE_MONGO_ID, AValue);
end;

procedure TPB_PutChips.SetChipAmount(const AValue: Integer);
begin
  FChipAmount := AValue;
  ProtobufOutput.writeInt32(FN_CHIP_AMOUNT, AValue);
end;

end.
